// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package clidrivermock

import (
	"context"

	"github.com/alexandremahdhaoui/forge-ci/internal/controller/reconcilecontroller"
	"github.com/alexandremahdhaoui/forge-ci/pkg/citypes"
	"github.com/alexandremahdhaoui/forge-ci/pkg/config"
	mock "github.com/stretchr/testify/mock"
)

// NewMockReconciler creates a new instance of MockReconciler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockReconciler(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockReconciler {
	mock := &MockReconciler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockReconciler is an autogenerated mock type for the Reconciler type
type MockReconciler struct {
	mock.Mock
}

type MockReconciler_Expecter struct {
	mock *mock.Mock
}

func (_m *MockReconciler) EXPECT() *MockReconciler_Expecter {
	return &MockReconciler_Expecter{mock: &_m.Mock}
}

// Apply provides a mock function for the type MockReconciler
func (_mock *MockReconciler) Apply(context1 context.Context, pipeline config.Pipeline, s string) (reconcilecontroller.Report, error) {
	ret := _mock.Called(context1, pipeline, s)

	if len(ret) == 0 {
		panic("no return value specified for Apply")
	}

	var r0 reconcilecontroller.Report
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, config.Pipeline, string) (reconcilecontroller.Report, error)); ok {
		return returnFunc(context1, pipeline, s)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, config.Pipeline, string) reconcilecontroller.Report); ok {
		r0 = returnFunc(context1, pipeline, s)
	} else {
		r0 = ret.Get(0).(reconcilecontroller.Report)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, config.Pipeline, string) error); ok {
		r1 = returnFunc(context1, pipeline, s)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockReconciler_Apply_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Apply'
type MockReconciler_Apply_Call struct {
	*mock.Call
}

// Apply is a helper method to define mock.On call
//   - context1 context.Context
//   - pipeline config.Pipeline
//   - s string
func (_e *MockReconciler_Expecter) Apply(context1 any, pipeline any, s any) *MockReconciler_Apply_Call {
	return &MockReconciler_Apply_Call{Call: _e.mock.On("Apply", context1, pipeline, s)}
}

func (_c *MockReconciler_Apply_Call) Run(run func(context1 context.Context, pipeline config.Pipeline, s string)) *MockReconciler_Apply_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 config.Pipeline
		if args[1] != nil {
			arg1 = args[1].(config.Pipeline)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockReconciler_Apply_Call) Return(report reconcilecontroller.Report, err error) *MockReconciler_Apply_Call {
	_c.Call.Return(report, err)
	return _c
}

func (_c *MockReconciler_Apply_Call) RunAndReturn(run func(context1 context.Context, pipeline config.Pipeline, s string) (reconcilecontroller.Report, error)) *MockReconciler_Apply_Call {
	_c.Call.Return(run)
	return _c
}

// Bootstrap provides a mock function for the type MockReconciler
func (_mock *MockReconciler) Bootstrap(context1 context.Context, pipeline config.Pipeline, s string) (reconcilecontroller.Report, error) {
	ret := _mock.Called(context1, pipeline, s)

	if len(ret) == 0 {
		panic("no return value specified for Bootstrap")
	}

	var r0 reconcilecontroller.Report
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, config.Pipeline, string) (reconcilecontroller.Report, error)); ok {
		return returnFunc(context1, pipeline, s)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, config.Pipeline, string) reconcilecontroller.Report); ok {
		r0 = returnFunc(context1, pipeline, s)
	} else {
		r0 = ret.Get(0).(reconcilecontroller.Report)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, config.Pipeline, string) error); ok {
		r1 = returnFunc(context1, pipeline, s)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockReconciler_Bootstrap_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Bootstrap'
type MockReconciler_Bootstrap_Call struct {
	*mock.Call
}

// Bootstrap is a helper method to define mock.On call
//   - context1 context.Context
//   - pipeline config.Pipeline
//   - s string
func (_e *MockReconciler_Expecter) Bootstrap(context1 any, pipeline any, s any) *MockReconciler_Bootstrap_Call {
	return &MockReconciler_Bootstrap_Call{Call: _e.mock.On("Bootstrap", context1, pipeline, s)}
}

func (_c *MockReconciler_Bootstrap_Call) Run(run func(context1 context.Context, pipeline config.Pipeline, s string)) *MockReconciler_Bootstrap_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 config.Pipeline
		if args[1] != nil {
			arg1 = args[1].(config.Pipeline)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockReconciler_Bootstrap_Call) Return(report reconcilecontroller.Report, err error) *MockReconciler_Bootstrap_Call {
	_c.Call.Return(report, err)
	return _c
}

func (_c *MockReconciler_Bootstrap_Call) RunAndReturn(run func(context1 context.Context, pipeline config.Pipeline, s string) (reconcilecontroller.Report, error)) *MockReconciler_Bootstrap_Call {
	_c.Call.Return(run)
	return _c
}

// Poll provides a mock function for the type MockReconciler
func (_mock *MockReconciler) Poll(context1 context.Context, pipeline config.Pipeline, s string) (citypes.TriggerOutput, error) {
	ret := _mock.Called(context1, pipeline, s)

	if len(ret) == 0 {
		panic("no return value specified for Poll")
	}

	var r0 citypes.TriggerOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, config.Pipeline, string) (citypes.TriggerOutput, error)); ok {
		return returnFunc(context1, pipeline, s)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, config.Pipeline, string) citypes.TriggerOutput); ok {
		r0 = returnFunc(context1, pipeline, s)
	} else {
		r0 = ret.Get(0).(citypes.TriggerOutput)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, config.Pipeline, string) error); ok {
		r1 = returnFunc(context1, pipeline, s)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockReconciler_Poll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Poll'
type MockReconciler_Poll_Call struct {
	*mock.Call
}

// Poll is a helper method to define mock.On call
//   - context1 context.Context
//   - pipeline config.Pipeline
//   - s string
func (_e *MockReconciler_Expecter) Poll(context1 any, pipeline any, s any) *MockReconciler_Poll_Call {
	return &MockReconciler_Poll_Call{Call: _e.mock.On("Poll", context1, pipeline, s)}
}

func (_c *MockReconciler_Poll_Call) Run(run func(context1 context.Context, pipeline config.Pipeline, s string)) *MockReconciler_Poll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 config.Pipeline
		if args[1] != nil {
			arg1 = args[1].(config.Pipeline)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockReconciler_Poll_Call) Return(triggerOutput citypes.TriggerOutput, err error) *MockReconciler_Poll_Call {
	_c.Call.Return(triggerOutput, err)
	return _c
}

func (_c *MockReconciler_Poll_Call) RunAndReturn(run func(context1 context.Context, pipeline config.Pipeline, s string) (citypes.TriggerOutput, error)) *MockReconciler_Poll_Call {
	_c.Call.Return(run)
	return _c
}

// Status provides a mock function for the type MockReconciler
func (_mock *MockReconciler) Status(context1 context.Context, pipeline config.Pipeline, s string) (reconcilecontroller.Report, error) {
	ret := _mock.Called(context1, pipeline, s)

	if len(ret) == 0 {
		panic("no return value specified for Status")
	}

	var r0 reconcilecontroller.Report
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, config.Pipeline, string) (reconcilecontroller.Report, error)); ok {
		return returnFunc(context1, pipeline, s)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, config.Pipeline, string) reconcilecontroller.Report); ok {
		r0 = returnFunc(context1, pipeline, s)
	} else {
		r0 = ret.Get(0).(reconcilecontroller.Report)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, config.Pipeline, string) error); ok {
		r1 = returnFunc(context1, pipeline, s)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockReconciler_Status_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Status'
type MockReconciler_Status_Call struct {
	*mock.Call
}

// Status is a helper method to define mock.On call
//   - context1 context.Context
//   - pipeline config.Pipeline
//   - s string
func (_e *MockReconciler_Expecter) Status(context1 any, pipeline any, s any) *MockReconciler_Status_Call {
	return &MockReconciler_Status_Call{Call: _e.mock.On("Status", context1, pipeline, s)}
}

func (_c *MockReconciler_Status_Call) Run(run func(context1 context.Context, pipeline config.Pipeline, s string)) *MockReconciler_Status_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 config.Pipeline
		if args[1] != nil {
			arg1 = args[1].(config.Pipeline)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockReconciler_Status_Call) Return(report reconcilecontroller.Report, err error) *MockReconciler_Status_Call {
	_c.Call.Return(report, err)
	return _c
}

func (_c *MockReconciler_Status_Call) RunAndReturn(run func(context1 context.Context, pipeline config.Pipeline, s string) (reconcilecontroller.Report, error)) *MockReconciler_Status_Call {
	_c.Call.Return(run)
	return _c
}
