package docscontroller

import (
	"errors"
	"fmt"
	"path/filepath"
	"sort"
	"strings"

	"github.com/alexandremahdhaoui/forge-ci/internal/types/docstypes"
)

const header = "<!-- Code generated by docgen. DO NOT EDIT. Source: %s -->\n\n"

var ErrEngine = errors.New("an engine spec needs a name, a port, a tagline and at least one tool")

func Engine(e docstypes.Engine) ([]docstypes.File, error) {
	if e.Name == "" || e.Port == "" || e.Tagline == "" || len(e.Tools) == 0 {
		return nil, fmt.Errorf("%s: %w", e.Name, ErrEngine)
	}

	dir := filepath.Join("cmd", e.Name, "docs")
	source := filepath.Join("cmd", e.Name, "spec.yaml")

	return []docstypes.File{
		{Path: filepath.Join(dir, "usage.md"), Content: usage(e, source)},
		{Path: filepath.Join(dir, "schema.md"), Content: schema(e, source)},
		{Path: filepath.Join(dir, "list.yaml"), Content: list(e, source)},
	}, nil
}

func usage(e docstypes.Engine, source string) string {
	var b strings.Builder

	fmt.Fprintf(&b, header, source)
	fmt.Fprintf(&b, "# %s\n\n**%s**\n\nA forge-ci `%s` engine.\n\n", e.Name, e.Tagline, e.Port)

	if e.Why != "" {
		fmt.Fprintf(&b, "## Why it exists\n\n%s\n\n", strings.TrimSpace(e.Why))
	}

	fmt.Fprintf(&b, "## Tools\n\n| Tool | Does |\n|---|---|\n")

	for _, t := range e.Tools {
		fmt.Fprintf(&b, "| `%s` | %s |\n", t.Name, t.Does)
	}

	fmt.Fprintf(&b, "\n## By hand\n\n```sh\necho '%s' \\\n  | %s %s\n```\n\n",
		e.Example.Input, e.Name, e.Example.Tool)

	fmt.Fprintf(&b, "## In a pipeline\n\n```yaml\nengines:\n  - alias: my-%s\n    type: %s\n"+
		"    engine: \"go://github.com/alexandremahdhaoui/forge-ci/cmd/%s@%s\"\n    manager: local\n",
		e.Port, e.Port, e.Name, e.Version)

	if len(e.Spec) > 0 {
		fmt.Fprintf(&b, "    spec:\n")

		for _, k := range e.Spec {
			fmt.Fprintf(&b, "      %s: <%s>\n", k.Key, k.Type)
		}
	}

	fmt.Fprintf(&b, "```\n")

	if e.Notes != "" {
		fmt.Fprintf(&b, "\n## Worth knowing\n\n%s\n", strings.TrimSpace(e.Notes))
	}

	return b.String()
}

func schema(e docstypes.Engine, source string) string {
	var b strings.Builder

	fmt.Fprintf(&b, header, source)
	fmt.Fprintf(&b, "# %s spec\n\nThe `spec` block on this engine's entry in `pipeline.yaml`.\n\n", e.Name)

	if len(e.Spec) == 0 {
		fmt.Fprintf(&b, "It reads none.\n")

		return b.String()
	}

	fmt.Fprintf(&b, "| Key | Type | Required | Means |\n|---|---|---|---|\n")

	for _, k := range e.Spec {
		required := "no"
		if k.Required {
			required = "yes"
		}

		fmt.Fprintf(&b, "| `%s` | %s | %s | %s |\n", k.Key, k.Type, required, k.Means)
	}

	fmt.Fprintf(&b, "\nforge-ci never validates a spec. This engine does, because only it knows "+
		"what the keys mean.\n")

	return b.String()
}

func list(e docstypes.Engine, source string) string {
	var b strings.Builder

	fmt.Fprintf(&b, "# Code generated by docgen. DO NOT EDIT. Source: %s\n\n", source)
	fmt.Fprintf(&b, "version: \"1.0\"\nengine: %q\n", e.Name)
	fmt.Fprintf(&b, "baseURL: \"https://raw.githubusercontent.com/alexandremahdhaoui/forge-ci/refs/heads/main\"\n\n")
	fmt.Fprintf(&b, "docs:\n")
	fmt.Fprintf(&b, "  - name: \"usage\"\n    title: %q\n    description: %q\n"+
		"    url: \"cmd/%s/docs/usage.md\"\n    tags: [\"usage\", %q]\n    required: true\n\n",
		e.Name+" usage", e.Tagline, e.Name, e.Port)
	fmt.Fprintf(&b, "  - name: \"schema\"\n    title: %q\n    description: \"The spec block this engine reads.\"\n"+
		"    url: \"cmd/%s/docs/schema.md\"\n    tags: [\"configuration\", \"schema\", %q]\n    required: true\n",
		e.Name+" spec", e.Name, e.Port)

	return b.String()
}

func Concepts(schemaYAML []byte, source string) (docstypes.File, error) {
	terms, ports, err := termsOf(schemaYAML)
	if err != nil {
		return docstypes.File{}, err
	}

	var b strings.Builder

	fmt.Fprintf(&b, header, source)
	fmt.Fprintf(&b, "# Concepts\n\nEvery term in the pipeline schema, and what it means.\n\n")
	fmt.Fprintf(&b, "## Ports\n\nThe question an engine answers. The list is closed.\n\n")
	fmt.Fprintf(&b, "%s\n\n", strings.Join(ports, ", "))
	fmt.Fprintf(&b, "## Keys\n\n| Term | Means |\n|---|---|\n")

	for _, t := range terms {
		fmt.Fprintf(&b, "| `%s` | %s |\n", t.name, t.desc)
	}

	fmt.Fprintf(&b, "\nSee [architecture.md](architecture.md) for how they fit together, and\n")
	fmt.Fprintf(&b, "[decisions.md](decisions.md) for why.\n")

	return docstypes.File{Path: filepath.Join("docs", "concepts.md"), Content: b.String()}, nil
}

func Decisions(d docstypes.Decisions, source string) docstypes.File {
	var b strings.Builder

	fmt.Fprintf(&b, header, source)
	fmt.Fprintf(&b, "# Decisions\n\nWhat was decided, why, and what it costs. "+
		"A ↩ marks one that reversed an earlier position.\n")

	for _, g := range d.Groups {
		fmt.Fprintf(&b, "\n## %s\n\n", g.Name)

		for _, dec := range g.Decisions {
			mark := ""
			if dec.Reversed {
				mark = " ↩"
			}

			fmt.Fprintf(&b, "### %s%s\n\n", dec.Title, mark)
			fmt.Fprintf(&b, "**Decided.** %s\n\n", dec.Decided)
			fmt.Fprintf(&b, "**Why.** %s\n\n", dec.Why)
			fmt.Fprintf(&b, "**Costs.** %s\n\n", dec.Costs)
		}
	}

	return docstypes.File{Path: filepath.Join("docs", "decisions.md"), Content: b.String()}
}

type term struct {
	name string
	desc string
}

func termsOf(schemaYAML []byte) ([]term, []string, error) {
	lines := strings.Split(string(schemaYAML), "\n")

	found := map[string]string{}
	var ports []string

	for i, line := range lines {
		if strings.Contains(line, "enum: [compute") {
			ports = portsFrom(line)
		}

		name, indent := anyKey(line)
		if name == "" {
			continue
		}

		desc := describe(lines, i, indent)
		if desc == "" {
			continue
		}

		if _, seen := found[name]; !seen {
			found[name] = desc
		}
	}

	if len(found) == 0 {
		return nil, nil, errors.New("the schema has no described keys")
	}

	if len(ports) == 0 {
		return nil, nil, errors.New("the schema has no port enum")
	}

	names := make([]string, 0, len(found))
	for n := range found {
		names = append(names, n)
	}

	sort.Strings(names)

	out := make([]term, 0, len(names))
	for _, n := range names {
		out = append(out, term{name: n, desc: found[n]})
	}

	return out, ports, nil
}

func portsFrom(line string) []string {
	_, rest, ok := strings.Cut(line, "enum: [")
	if !ok {
		return nil
	}

	rest = strings.TrimSuffix(strings.TrimSpace(rest), "]")

	parts := strings.Split(rest, ",")
	out := make([]string, 0, len(parts))

	for _, p := range parts {
		if trimmed := strings.TrimSpace(p); trimmed != "" {
			out = append(out, "`"+trimmed+"`")
		}
	}

	return out
}

func anyKey(line string) (string, int) {
	trimmed := strings.TrimLeft(line, " ")
	indent := len(line) - len(trimmed)

	if trimmed == "" || strings.HasPrefix(trimmed, "#") || strings.HasPrefix(trimmed, "-") {
		return "", 0
	}

	name, _, ok := strings.Cut(trimmed, ":")
	if !ok || name == "" || strings.ContainsAny(name, " $\"") {
		return "", 0
	}

	switch name {
	case "type", "properties", "items", "description", "enum", "pattern", "required",
		"additionalProperties", "minItems", "minLength", "default", "title", "oneOf",
		"propertyNames", "maxItems":
		return "", 0
	}

	return name, indent
}

func describe(lines []string, from, indent int) string {
	for i := from + 1; i < len(lines); i++ {
		trimmed := strings.TrimLeft(lines[i], " ")
		if trimmed == "" {
			continue
		}

		if len(lines[i])-len(trimmed) <= indent {
			return ""
		}

		if !strings.HasPrefix(trimmed, "description:") {
			continue
		}

		rest := strings.TrimSpace(strings.TrimPrefix(trimmed, "description:"))
		if rest != "" && rest != ">-" && rest != ">" && rest != "|" {
			return rest
		}

		var parts []string

		for j := i + 1; j < len(lines); j++ {
			next := strings.TrimLeft(lines[j], " ")
			if next == "" || len(lines[j])-len(next) <= indent+2 {
				break
			}

			parts = append(parts, strings.TrimSpace(next))
		}

		return strings.Join(parts, " ")
	}

	return ""
}
