package docscontroller_test

import (
	"strings"
	"testing"

	"github.com/alexandremahdhaoui/forge-ci/internal/controller/docscontroller"
	"github.com/alexandremahdhaoui/forge-ci/internal/types/docstypes"
	"github.com/stretchr/testify/require"
)

func engine() docstypes.Engine {
	return docstypes.Engine{
		Name:    "ci-state-git",
		Port:    "state",
		Version: "v0.1.4",
		Tagline: "Read and write CI state in a git repo.",
		Why:     "Git gives history for nothing.",
		Tools:   []docstypes.Tool{{Name: "get", Does: "Read one record."}},
		Spec:    []docstypes.SpecKey{{Key: "path", Type: "string", Required: true, Means: "The state repo."}},
		Example: docstypes.Example{Tool: "get", Input: `{"kind":"revision"}`},
		Notes:   "A missing record is not an error.",
	}
}

func byPath(t *testing.T, files []docstypes.File, suffix string) string {
	t.Helper()

	for _, f := range files {
		if strings.HasSuffix(f.Path, suffix) {
			return f.Content
		}
	}

	t.Fatalf("no generated file ending in %s", suffix)

	return ""
}

func TestAnEngineGeneratesThreeFiles(t *testing.T) {
	files, err := docscontroller.Engine(engine())
	require.NoError(t, err)
	require.Len(t, files, 3)

	for _, f := range files {
		require.Contains(t, f.Path, "cmd/ci-state-git/docs/")
	}
}

func TestEveryGeneratedFileSaysSo(t *testing.T) {
	files, err := docscontroller.Engine(engine())
	require.NoError(t, err)

	for _, f := range files {
		require.Contains(t, f.Content, "Code generated by docgen. DO NOT EDIT.")
		require.Contains(t, f.Content, "cmd/ci-state-git/spec.yaml")
	}
}

func TestUsageCarriesTheToolsAndTheExample(t *testing.T) {
	files, err := docscontroller.Engine(engine())
	require.NoError(t, err)

	usage := byPath(t, files, "usage.md")
	require.Contains(t, usage, "**Read and write CI state in a git repo.**")
	require.Contains(t, usage, "A forge-ci `state` engine")
	require.Contains(t, usage, "| `get` | Read one record. |")
	require.Contains(t, usage, `echo '{"kind":"revision"}'`)
	require.Contains(t, usage, "cmd/ci-state-git@v0.1.4")
	require.Contains(t, usage, "      path: <string>")
	require.Contains(t, usage, "A missing record is not an error.")
}

func TestSchemaCarriesTheSpecTable(t *testing.T) {
	files, err := docscontroller.Engine(engine())
	require.NoError(t, err)

	schema := byPath(t, files, "schema.md")
	require.Contains(t, schema, "| `path` | string | yes | The state repo. |")
}

func TestAnEngineWithNoSpecSaysSo(t *testing.T) {
	e := engine()
	e.Spec = nil

	files, err := docscontroller.Engine(e)
	require.NoError(t, err)
	require.Contains(t, byPath(t, files, "schema.md"), "It reads none.")
	require.NotContains(t, byPath(t, files, "usage.md"), "spec:")
}

func TestListNamesBothRequiredDocs(t *testing.T) {
	files, err := docscontroller.Engine(engine())
	require.NoError(t, err)

	list := byPath(t, files, "list.yaml")
	require.Contains(t, list, `engine: "ci-state-git"`)
	require.Contains(t, list, `name: "usage"`)
	require.Contains(t, list, `name: "schema"`)
	require.Equal(t, 2, strings.Count(list, "required: true"))
}

func TestAnIncompleteEngineSpecIsRefused(t *testing.T) {
	for _, broken := range []func(*docstypes.Engine){
		func(e *docstypes.Engine) { e.Name = "" },
		func(e *docstypes.Engine) { e.Port = "" },
		func(e *docstypes.Engine) { e.Tagline = "" },
		func(e *docstypes.Engine) { e.Tools = nil },
	} {
		e := engine()
		broken(&e)

		_, err := docscontroller.Engine(e)
		require.ErrorIs(t, err, docscontroller.ErrEngine)
	}
}

const schemaYAML = `
properties:
  repos:
    type: array
    description: >-
      The repos that form
      a revision.
    items:
      type: object
      properties:
        ref:
          type: string
          description: Branch to track.
  stages:
    type: array
    description: Ordered phases.

$defs:
  port:
    type: string
    enum: [compute, state, trigger, gate, promotion, artifact]
    description: The question an engine answers.
`

func TestConceptsReadsEveryDepthAndThePorts(t *testing.T) {
	got, err := docscontroller.Concepts([]byte(schemaYAML), "spec.yaml")
	require.NoError(t, err)
	require.Equal(t, "docs/concepts.md", got.Path)
	require.Contains(t, got.Content, "`compute`, `state`, `trigger`, `gate`, `promotion`, `artifact`")
	require.Contains(t, got.Content, "| `repos` | The repos that form a revision. |")
	require.Contains(t, got.Content, "| `ref` | Branch to track. |")
	require.Contains(t, got.Content, "| `stages` | Ordered phases. |")
	require.Contains(t, got.Content, "| `port` | The question an engine answers. |")
}

func TestConceptsIsSortedSoTheDiffIsStable(t *testing.T) {
	got, err := docscontroller.Concepts([]byte(schemaYAML), "spec.yaml")
	require.NoError(t, err)

	require.Less(t, strings.Index(got.Content, "| `port`"), strings.Index(got.Content, "| `ref`"))
	require.Less(t, strings.Index(got.Content, "| `ref`"), strings.Index(got.Content, "| `repos`"))
}

func TestASchemaWithNothingDescribedIsRefused(t *testing.T) {
	_, err := docscontroller.Concepts([]byte("properties:\n  a:\n    type: string\n"), "s.yaml")
	require.Error(t, err)

	_, err = docscontroller.Concepts([]byte("properties:\n  a:\n    description: x\n"), "s.yaml")
	require.Error(t, err)
	require.Contains(t, err.Error(), "port enum")
}

func TestDecisionsMarkAReversal(t *testing.T) {
	got := docscontroller.Decisions(docstypes.Decisions{Groups: []docstypes.DecisionGroup{{
		Name: "Reversals",
		Decisions: []docstypes.Decision{
			{Title: "Webhooks", Decided: "Use webhooks.", Why: "Cheaper.", Costs: "A secret.", Reversed: true},
			{Title: "Ordered list", Decided: "No graph.", Why: "Simpler.", Costs: "No fan-in."},
		},
	}}}, "docs/decisions.yaml")

	require.Equal(t, "docs/decisions.md", got.Path)
	require.Contains(t, got.Content, "### Webhooks ↩")
	require.Contains(t, got.Content, "### Ordered list\n")
	require.Contains(t, got.Content, "**Decided.** Use webhooks.")
	require.Contains(t, got.Content, "**Why.** Cheaper.")
	require.Contains(t, got.Content, "**Costs.** A secret.")
}
