// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package githubadaptermock

import (
	"context"
	"time"

	"github.com/alexandremahdhaoui/forge-ci/internal/adapter/githubadapter"
	mock "github.com/stretchr/testify/mock"
)

// NewMockAPI creates a new instance of MockAPI. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAPI(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAPI {
	mock := &MockAPI{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAPI is an autogenerated mock type for the API type
type MockAPI struct {
	mock.Mock
}

type MockAPI_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAPI) EXPECT() *MockAPI_Expecter {
	return &MockAPI_Expecter{mock: &_m.Mock}
}

// CreateDraftRelease provides a mock function for the type MockAPI
func (_mock *MockAPI) CreateDraftRelease(ctx context.Context, repo string, tag string) (githubadapter.Release, error) {
	ret := _mock.Called(ctx, repo, tag)

	if len(ret) == 0 {
		panic("no return value specified for CreateDraftRelease")
	}

	var r0 githubadapter.Release
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (githubadapter.Release, error)); ok {
		return returnFunc(ctx, repo, tag)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) githubadapter.Release); ok {
		r0 = returnFunc(ctx, repo, tag)
	} else {
		r0 = ret.Get(0).(githubadapter.Release)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, repo, tag)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAPI_CreateDraftRelease_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateDraftRelease'
type MockAPI_CreateDraftRelease_Call struct {
	*mock.Call
}

// CreateDraftRelease is a helper method to define mock.On call
//   - ctx context.Context
//   - repo string
//   - tag string
func (_e *MockAPI_Expecter) CreateDraftRelease(ctx any, repo any, tag any) *MockAPI_CreateDraftRelease_Call {
	return &MockAPI_CreateDraftRelease_Call{Call: _e.mock.On("CreateDraftRelease", ctx, repo, tag)}
}

func (_c *MockAPI_CreateDraftRelease_Call) Run(run func(ctx context.Context, repo string, tag string)) *MockAPI_CreateDraftRelease_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockAPI_CreateDraftRelease_Call) Return(release githubadapter.Release, err error) *MockAPI_CreateDraftRelease_Call {
	_c.Call.Return(release, err)
	return _c
}

func (_c *MockAPI_CreateDraftRelease_Call) RunAndReturn(run func(ctx context.Context, repo string, tag string) (githubadapter.Release, error)) *MockAPI_CreateDraftRelease_Call {
	_c.Call.Return(run)
	return _c
}

// Dispatch provides a mock function for the type MockAPI
func (_mock *MockAPI) Dispatch(ctx context.Context, repo string, workflowFile string, ref string, inputs map[string]string) error {
	ret := _mock.Called(ctx, repo, workflowFile, ref, inputs)

	if len(ret) == 0 {
		panic("no return value specified for Dispatch")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, map[string]string) error); ok {
		r0 = returnFunc(ctx, repo, workflowFile, ref, inputs)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAPI_Dispatch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Dispatch'
type MockAPI_Dispatch_Call struct {
	*mock.Call
}

// Dispatch is a helper method to define mock.On call
//   - ctx context.Context
//   - repo string
//   - workflowFile string
//   - ref string
//   - inputs map[string]string
func (_e *MockAPI_Expecter) Dispatch(ctx any, repo any, workflowFile any, ref any, inputs any) *MockAPI_Dispatch_Call {
	return &MockAPI_Dispatch_Call{Call: _e.mock.On("Dispatch", ctx, repo, workflowFile, ref, inputs)}
}

func (_c *MockAPI_Dispatch_Call) Run(run func(ctx context.Context, repo string, workflowFile string, ref string, inputs map[string]string)) *MockAPI_Dispatch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 map[string]string
		if args[4] != nil {
			arg4 = args[4].(map[string]string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockAPI_Dispatch_Call) Return(err error) *MockAPI_Dispatch_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAPI_Dispatch_Call) RunAndReturn(run func(ctx context.Context, repo string, workflowFile string, ref string, inputs map[string]string) error) *MockAPI_Dispatch_Call {
	_c.Call.Return(run)
	return _c
}

// EnableWorkflow provides a mock function for the type MockAPI
func (_mock *MockAPI) EnableWorkflow(ctx context.Context, repo string, workflowFile string) error {
	ret := _mock.Called(ctx, repo, workflowFile)

	if len(ret) == 0 {
		panic("no return value specified for EnableWorkflow")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, repo, workflowFile)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAPI_EnableWorkflow_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EnableWorkflow'
type MockAPI_EnableWorkflow_Call struct {
	*mock.Call
}

// EnableWorkflow is a helper method to define mock.On call
//   - ctx context.Context
//   - repo string
//   - workflowFile string
func (_e *MockAPI_Expecter) EnableWorkflow(ctx any, repo any, workflowFile any) *MockAPI_EnableWorkflow_Call {
	return &MockAPI_EnableWorkflow_Call{Call: _e.mock.On("EnableWorkflow", ctx, repo, workflowFile)}
}

func (_c *MockAPI_EnableWorkflow_Call) Run(run func(ctx context.Context, repo string, workflowFile string)) *MockAPI_EnableWorkflow_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockAPI_EnableWorkflow_Call) Return(err error) *MockAPI_EnableWorkflow_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAPI_EnableWorkflow_Call) RunAndReturn(run func(ctx context.Context, repo string, workflowFile string) error) *MockAPI_EnableWorkflow_Call {
	_c.Call.Return(run)
	return _c
}

// ListRuns provides a mock function for the type MockAPI
func (_mock *MockAPI) ListRuns(ctx context.Context, repo string, workflowFile string, createdAfter time.Time) ([]githubadapter.RunInfo, error) {
	ret := _mock.Called(ctx, repo, workflowFile, createdAfter)

	if len(ret) == 0 {
		panic("no return value specified for ListRuns")
	}

	var r0 []githubadapter.RunInfo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, time.Time) ([]githubadapter.RunInfo, error)); ok {
		return returnFunc(ctx, repo, workflowFile, createdAfter)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, time.Time) []githubadapter.RunInfo); ok {
		r0 = returnFunc(ctx, repo, workflowFile, createdAfter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]githubadapter.RunInfo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, time.Time) error); ok {
		r1 = returnFunc(ctx, repo, workflowFile, createdAfter)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAPI_ListRuns_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListRuns'
type MockAPI_ListRuns_Call struct {
	*mock.Call
}

// ListRuns is a helper method to define mock.On call
//   - ctx context.Context
//   - repo string
//   - workflowFile string
//   - createdAfter time.Time
func (_e *MockAPI_Expecter) ListRuns(ctx any, repo any, workflowFile any, createdAfter any) *MockAPI_ListRuns_Call {
	return &MockAPI_ListRuns_Call{Call: _e.mock.On("ListRuns", ctx, repo, workflowFile, createdAfter)}
}

func (_c *MockAPI_ListRuns_Call) Run(run func(ctx context.Context, repo string, workflowFile string, createdAfter time.Time)) *MockAPI_ListRuns_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 time.Time
		if args[3] != nil {
			arg3 = args[3].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockAPI_ListRuns_Call) Return(runInfos []githubadapter.RunInfo, err error) *MockAPI_ListRuns_Call {
	_c.Call.Return(runInfos, err)
	return _c
}

func (_c *MockAPI_ListRuns_Call) RunAndReturn(run func(ctx context.Context, repo string, workflowFile string, createdAfter time.Time) ([]githubadapter.RunInfo, error)) *MockAPI_ListRuns_Call {
	_c.Call.Return(run)
	return _c
}

// PublicKey provides a mock function for the type MockAPI
func (_mock *MockAPI) PublicKey(ctx context.Context, repo string) (string, string, error) {
	ret := _mock.Called(ctx, repo)

	if len(ret) == 0 {
		panic("no return value specified for PublicKey")
	}

	var r0 string
	var r1 string
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (string, string, error)); ok {
		return returnFunc(ctx, repo)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = returnFunc(ctx, repo)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) string); ok {
		r1 = returnFunc(ctx, repo)
	} else {
		r1 = ret.Get(1).(string)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string) error); ok {
		r2 = returnFunc(ctx, repo)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockAPI_PublicKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PublicKey'
type MockAPI_PublicKey_Call struct {
	*mock.Call
}

// PublicKey is a helper method to define mock.On call
//   - ctx context.Context
//   - repo string
func (_e *MockAPI_Expecter) PublicKey(ctx any, repo any) *MockAPI_PublicKey_Call {
	return &MockAPI_PublicKey_Call{Call: _e.mock.On("PublicKey", ctx, repo)}
}

func (_c *MockAPI_PublicKey_Call) Run(run func(ctx context.Context, repo string)) *MockAPI_PublicKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAPI_PublicKey_Call) Return(keyID string, keyB64 string, err error) *MockAPI_PublicKey_Call {
	_c.Call.Return(keyID, keyB64, err)
	return _c
}

func (_c *MockAPI_PublicKey_Call) RunAndReturn(run func(ctx context.Context, repo string) (string, string, error)) *MockAPI_PublicKey_Call {
	_c.Call.Return(run)
	return _c
}

// PublishRelease provides a mock function for the type MockAPI
func (_mock *MockAPI) PublishRelease(ctx context.Context, repo string, id int64) (githubadapter.Release, error) {
	ret := _mock.Called(ctx, repo, id)

	if len(ret) == 0 {
		panic("no return value specified for PublishRelease")
	}

	var r0 githubadapter.Release
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int64) (githubadapter.Release, error)); ok {
		return returnFunc(ctx, repo, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int64) githubadapter.Release); ok {
		r0 = returnFunc(ctx, repo, id)
	} else {
		r0 = ret.Get(0).(githubadapter.Release)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, int64) error); ok {
		r1 = returnFunc(ctx, repo, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAPI_PublishRelease_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PublishRelease'
type MockAPI_PublishRelease_Call struct {
	*mock.Call
}

// PublishRelease is a helper method to define mock.On call
//   - ctx context.Context
//   - repo string
//   - id int64
func (_e *MockAPI_Expecter) PublishRelease(ctx any, repo any, id any) *MockAPI_PublishRelease_Call {
	return &MockAPI_PublishRelease_Call{Call: _e.mock.On("PublishRelease", ctx, repo, id)}
}

func (_c *MockAPI_PublishRelease_Call) Run(run func(ctx context.Context, repo string, id int64)) *MockAPI_PublishRelease_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockAPI_PublishRelease_Call) Return(release githubadapter.Release, err error) *MockAPI_PublishRelease_Call {
	_c.Call.Return(release, err)
	return _c
}

func (_c *MockAPI_PublishRelease_Call) RunAndReturn(run func(ctx context.Context, repo string, id int64) (githubadapter.Release, error)) *MockAPI_PublishRelease_Call {
	_c.Call.Return(run)
	return _c
}

// PutSecret provides a mock function for the type MockAPI
func (_mock *MockAPI) PutSecret(ctx context.Context, repo string, name string, keyID string, sealedB64 string) error {
	ret := _mock.Called(ctx, repo, name, keyID, sealedB64)

	if len(ret) == 0 {
		panic("no return value specified for PutSecret")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, string) error); ok {
		r0 = returnFunc(ctx, repo, name, keyID, sealedB64)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAPI_PutSecret_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PutSecret'
type MockAPI_PutSecret_Call struct {
	*mock.Call
}

// PutSecret is a helper method to define mock.On call
//   - ctx context.Context
//   - repo string
//   - name string
//   - keyID string
//   - sealedB64 string
func (_e *MockAPI_Expecter) PutSecret(ctx any, repo any, name any, keyID any, sealedB64 any) *MockAPI_PutSecret_Call {
	return &MockAPI_PutSecret_Call{Call: _e.mock.On("PutSecret", ctx, repo, name, keyID, sealedB64)}
}

func (_c *MockAPI_PutSecret_Call) Run(run func(ctx context.Context, repo string, name string, keyID string, sealedB64 string)) *MockAPI_PutSecret_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockAPI_PutSecret_Call) Return(err error) *MockAPI_PutSecret_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAPI_PutSecret_Call) RunAndReturn(run func(ctx context.Context, repo string, name string, keyID string, sealedB64 string) error) *MockAPI_PutSecret_Call {
	_c.Call.Return(run)
	return _c
}

// ReleaseByTag provides a mock function for the type MockAPI
func (_mock *MockAPI) ReleaseByTag(ctx context.Context, repo string, tag string) (githubadapter.Release, bool, error) {
	ret := _mock.Called(ctx, repo, tag)

	if len(ret) == 0 {
		panic("no return value specified for ReleaseByTag")
	}

	var r0 githubadapter.Release
	var r1 bool
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (githubadapter.Release, bool, error)); ok {
		return returnFunc(ctx, repo, tag)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) githubadapter.Release); ok {
		r0 = returnFunc(ctx, repo, tag)
	} else {
		r0 = ret.Get(0).(githubadapter.Release)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) bool); ok {
		r1 = returnFunc(ctx, repo, tag)
	} else {
		r1 = ret.Get(1).(bool)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string, string) error); ok {
		r2 = returnFunc(ctx, repo, tag)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockAPI_ReleaseByTag_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReleaseByTag'
type MockAPI_ReleaseByTag_Call struct {
	*mock.Call
}

// ReleaseByTag is a helper method to define mock.On call
//   - ctx context.Context
//   - repo string
//   - tag string
func (_e *MockAPI_Expecter) ReleaseByTag(ctx any, repo any, tag any) *MockAPI_ReleaseByTag_Call {
	return &MockAPI_ReleaseByTag_Call{Call: _e.mock.On("ReleaseByTag", ctx, repo, tag)}
}

func (_c *MockAPI_ReleaseByTag_Call) Run(run func(ctx context.Context, repo string, tag string)) *MockAPI_ReleaseByTag_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockAPI_ReleaseByTag_Call) Return(release githubadapter.Release, b bool, err error) *MockAPI_ReleaseByTag_Call {
	_c.Call.Return(release, b, err)
	return _c
}

func (_c *MockAPI_ReleaseByTag_Call) RunAndReturn(run func(ctx context.Context, repo string, tag string) (githubadapter.Release, bool, error)) *MockAPI_ReleaseByTag_Call {
	_c.Call.Return(run)
	return _c
}

// Run provides a mock function for the type MockAPI
func (_mock *MockAPI) Run(ctx context.Context, repo string, id int64) (githubadapter.RunInfo, error) {
	ret := _mock.Called(ctx, repo, id)

	if len(ret) == 0 {
		panic("no return value specified for Run")
	}

	var r0 githubadapter.RunInfo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int64) (githubadapter.RunInfo, error)); ok {
		return returnFunc(ctx, repo, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int64) githubadapter.RunInfo); ok {
		r0 = returnFunc(ctx, repo, id)
	} else {
		r0 = ret.Get(0).(githubadapter.RunInfo)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, int64) error); ok {
		r1 = returnFunc(ctx, repo, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAPI_Run_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Run'
type MockAPI_Run_Call struct {
	*mock.Call
}

// Run is a helper method to define mock.On call
//   - ctx context.Context
//   - repo string
//   - id int64
func (_e *MockAPI_Expecter) Run(ctx any, repo any, id any) *MockAPI_Run_Call {
	return &MockAPI_Run_Call{Call: _e.mock.On("Run", ctx, repo, id)}
}

func (_c *MockAPI_Run_Call) Run(run func(ctx context.Context, repo string, id int64)) *MockAPI_Run_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockAPI_Run_Call) Return(runInfo githubadapter.RunInfo, err error) *MockAPI_Run_Call {
	_c.Call.Return(runInfo, err)
	return _c
}

func (_c *MockAPI_Run_Call) RunAndReturn(run func(ctx context.Context, repo string, id int64) (githubadapter.RunInfo, error)) *MockAPI_Run_Call {
	_c.Call.Return(run)
	return _c
}

// SecretExists provides a mock function for the type MockAPI
func (_mock *MockAPI) SecretExists(ctx context.Context, repo string, name string) (bool, error) {
	ret := _mock.Called(ctx, repo, name)

	if len(ret) == 0 {
		panic("no return value specified for SecretExists")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (bool, error)); ok {
		return returnFunc(ctx, repo, name)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) bool); ok {
		r0 = returnFunc(ctx, repo, name)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, repo, name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAPI_SecretExists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SecretExists'
type MockAPI_SecretExists_Call struct {
	*mock.Call
}

// SecretExists is a helper method to define mock.On call
//   - ctx context.Context
//   - repo string
//   - name string
func (_e *MockAPI_Expecter) SecretExists(ctx any, repo any, name any) *MockAPI_SecretExists_Call {
	return &MockAPI_SecretExists_Call{Call: _e.mock.On("SecretExists", ctx, repo, name)}
}

func (_c *MockAPI_SecretExists_Call) Run(run func(ctx context.Context, repo string, name string)) *MockAPI_SecretExists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockAPI_SecretExists_Call) Return(b bool, err error) *MockAPI_SecretExists_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockAPI_SecretExists_Call) RunAndReturn(run func(ctx context.Context, repo string, name string) (bool, error)) *MockAPI_SecretExists_Call {
	_c.Call.Return(run)
	return _c
}

// UploadAsset provides a mock function for the type MockAPI
func (_mock *MockAPI) UploadAsset(ctx context.Context, uploadURL string, file string, name string) error {
	ret := _mock.Called(ctx, uploadURL, file, name)

	if len(ret) == 0 {
		panic("no return value specified for UploadAsset")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = returnFunc(ctx, uploadURL, file, name)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAPI_UploadAsset_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UploadAsset'
type MockAPI_UploadAsset_Call struct {
	*mock.Call
}

// UploadAsset is a helper method to define mock.On call
//   - ctx context.Context
//   - uploadURL string
//   - file string
//   - name string
func (_e *MockAPI_Expecter) UploadAsset(ctx any, uploadURL any, file any, name any) *MockAPI_UploadAsset_Call {
	return &MockAPI_UploadAsset_Call{Call: _e.mock.On("UploadAsset", ctx, uploadURL, file, name)}
}

func (_c *MockAPI_UploadAsset_Call) Run(run func(ctx context.Context, uploadURL string, file string, name string)) *MockAPI_UploadAsset_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockAPI_UploadAsset_Call) Return(err error) *MockAPI_UploadAsset_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAPI_UploadAsset_Call) RunAndReturn(run func(ctx context.Context, uploadURL string, file string, name string) error) *MockAPI_UploadAsset_Call {
	_c.Call.Return(run)
	return _c
}

// WorkflowState provides a mock function for the type MockAPI
func (_mock *MockAPI) WorkflowState(ctx context.Context, repo string, workflowFile string) (string, error) {
	ret := _mock.Called(ctx, repo, workflowFile)

	if len(ret) == 0 {
		panic("no return value specified for WorkflowState")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (string, error)); ok {
		return returnFunc(ctx, repo, workflowFile)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) string); ok {
		r0 = returnFunc(ctx, repo, workflowFile)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, repo, workflowFile)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAPI_WorkflowState_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WorkflowState'
type MockAPI_WorkflowState_Call struct {
	*mock.Call
}

// WorkflowState is a helper method to define mock.On call
//   - ctx context.Context
//   - repo string
//   - workflowFile string
func (_e *MockAPI_Expecter) WorkflowState(ctx any, repo any, workflowFile any) *MockAPI_WorkflowState_Call {
	return &MockAPI_WorkflowState_Call{Call: _e.mock.On("WorkflowState", ctx, repo, workflowFile)}
}

func (_c *MockAPI_WorkflowState_Call) Run(run func(ctx context.Context, repo string, workflowFile string)) *MockAPI_WorkflowState_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockAPI_WorkflowState_Call) Return(s string, err error) *MockAPI_WorkflowState_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockAPI_WorkflowState_Call) RunAndReturn(run func(ctx context.Context, repo string, workflowFile string) (string, error)) *MockAPI_WorkflowState_Call {
	_c.Call.Return(run)
	return _c
}
