package triggercontroller

import (
	"encoding/json"
	"errors"
	"fmt"
	"path"
	"sort"
	"strings"

	"github.com/alexandremahdhaoui/forge-ci/internal/controller/managercontroller"
	"github.com/alexandremahdhaoui/forge-ci/pkg/citypes"
)

// NotifySpec turns the watch list into the workflows that make it true.
//
// A watched repo is a repo whose movement should make this pipeline work.
// Nothing on GitHub delivers that: a push to one repo starts no workflow in
// another. Only a repository_dispatch does, and only because some workflow
// sends it. So the same list that decides what counts as a move also decides
// who has to report one, and both come from spec.watch.
type NotifySpec struct {
	Owner     string `json:"owner"`
	Factory   string `json:"factory"`
	EventType string `json:"eventType"`
	Secret    string `json:"secret"`
	FromEnv   string `json:"fromEnv,omitempty"`
	Workflow  string `json:"workflow,omitempty"`
	Branch    string `json:"branch,omitempty"`
	// RunsOn is the runner label the dispatch job runs on. Absent means
	// ubuntu-latest, which is what every notify workflow rendered before
	// the key existed.
	RunsOn string `json:"runsOn,omitempty"`
	// APIBaseURL is where the rendered workflow sends the dispatch. It runs
	// on GitHub, so absent means the public API.
	APIBaseURL string `json:"apiBaseURL,omitempty"`
}

type declareSpec struct {
	Notify *NotifySpec `json:"notify,omitempty"`
}

func parseNotify(raw map[string]any) (*NotifySpec, error) {
	payload, err := json.Marshal(raw)
	if err != nil {
		return nil, fmt.Errorf("encoding the spec: %w", err)
	}

	var s declareSpec
	if err := json.Unmarshal(payload, &s); err != nil {
		return nil, fmt.Errorf("parsing the spec: %w", err)
	}

	if s.Notify == nil {
		return nil, nil
	}

	n := s.Notify

	missing := []string{}
	for key, value := range map[string]string{
		"owner": n.Owner, "factory": n.Factory, "eventType": n.EventType, "secret": n.Secret,
	} {
		if strings.TrimSpace(value) == "" {
			missing = append(missing, key)
		}
	}

	if len(missing) > 0 {
		sort.Strings(missing)

		return nil, fmt.Errorf(
			"spec.notify needs %s: a workflow that cannot name its target, its event or its credential sends nothing",
			strings.Join(missing, ", "))
	}

	if n.Workflow == "" {
		n.Workflow = "notify"
	}

	if n.Branch == "" {
		n.Branch = "main"
	}

	if n.RunsOn == "" {
		n.RunsOn = "ubuntu-latest"
	}

	if n.APIBaseURL == "" {
		n.APIBaseURL = "https://api.github.com"
	}

	if n.FromEnv == "" {
		n.FromEnv = n.Secret
	}

	return n, nil
}

var errNotifySelf = errors.New(
	"spec.notify.factory is in spec.watch: a repo that dispatches to itself on every push never settles")

func notifyResources(watched []string, n *NotifySpec) ([]citypes.Resource, error) {
	resources := make([]citypes.Resource, 0, len(watched)*3)
	file := n.Workflow + ".yaml"

	for _, dir := range watched {
		repo := path.Base(dir)
		if repo == n.Factory {
			return nil, errNotifySelf
		}

		full := n.Owner + "/" + repo

		resources = append(resources,
			citypes.Resource{
				Kind: managercontroller.KindFileContent,
				Name: path.Join(dir, ".github", "workflows", file),
				Spec: map[string]any{"content": renderNotify(repo, n)},
			},
			citypes.Resource{
				Kind:          managercontroller.KindActionsSecret,
				Name:          full + "/" + n.Secret,
				BootstrapOnly: true,
				Spec:          map[string]any{"repo": full, "secret": n.Secret, "fromEnv": n.FromEnv},
			},
			citypes.Resource{
				Kind: managercontroller.KindWorkflowEnabled,
				Name: full + "/" + file,
				Spec: map[string]any{"repo": full, "workflow": file},
			},
		)
	}

	return resources, nil
}

func renderNotify(repo string, n *NotifySpec) string {
	var b strings.Builder

	b.WriteString("# Tell " + n.Factory + " that " + repo + " moved. Nothing is built here.\n")
	b.WriteString("#\n")
	b.WriteString("# Generated by forge-ci from spec.watch. Edit the pipeline, not this file:\n")
	b.WriteString("# every apply converges it back.\n")
	b.WriteString("#\n")
	b.WriteString("# A lone checkout of this repo has no siblings and no workspace files,\n")
	b.WriteString("# because they are generated and gitignored. Building here is not possible\n")
	b.WriteString("# and a workflow that tries is red forever.\n")
	b.WriteString("\n")
	b.WriteString("name: " + n.Workflow + "\n")
	b.WriteString("\n")
	b.WriteString("on:\n")
	b.WriteString("  push:\n")
	b.WriteString("    branches: [" + n.Branch + "]\n")
	b.WriteString("\n")
	b.WriteString("permissions:\n")
	b.WriteString("  contents: read\n")
	b.WriteString("\n")
	b.WriteString("jobs:\n")
	b.WriteString("  dispatch:\n")
	b.WriteString("    runs-on: " + n.RunsOn + "\n")
	b.WriteString("    steps:\n")
	// curl, and not a CLI. This file lands in a member repo, which carries no
	// toolchain of its own and never will - the whole point of the workflow
	// is that nothing is built here. curl is the one client every runner and
	// every image has, and it is what the fan-out workflow already uses, so
	// the two dispatchers speak the same way.
	//
	// -f so a rejected dispatch fails the step. Without it curl reports a 404
	// as a successful transfer and the member's checks stay green while the
	// factory is never told anything moved.
	b.WriteString("      - name: Tell " + n.Factory + " to run the pipeline\n")
	b.WriteString("        run: |\n")
	b.WriteString("          curl -fsS -X POST \\\n")
	b.WriteString("            -H \"Authorization: Bearer ${{ secrets." + n.Secret + " }}\" \\\n")
	b.WriteString("            -H \"Accept: application/vnd.github+json\" \\\n")
	b.WriteString("            \"" + n.APIBaseURL + "/repos/" + n.Owner + "/" + n.Factory + "/dispatches\" \\\n")
	b.WriteString("            -d '{\"event_type\":\"" + n.EventType +
		"\",\"client_payload\":{\"repo\":\"${{ github.repository }}\",\"sha\":\"${{ github.sha }}\"}}'\n")

	return b.String()
}
