// Generated by forge-factory. DO NOT EDIT. Source: forge-factory.yaml

module github.com/alexandremahdhaoui/forge-ci

go 1.26.5

require (
	github.com/alexandremahdhaoui/forge v0.45.110-0.20260906204214-4ed45f35ccc1
	github.com/alexandremahdhaoui/forge-revision-spec v0.3.0
	github.com/google/go-containerregistry v0.22.0
	github.com/modelcontextprotocol/go-sdk v1.7.0
	github.com/stretchr/testify v1.12.1
	golang.org/x/crypto v0.55.0
	sigs.k8s.io/yaml v1.6.0
)

require (
	github.com/docker/cli v29.7.2+incompatible // indirect
	github.com/docker/docker-credential-helpers v0.9.3 // indirect
	github.com/google/jsonschema-go v0.4.3 // indirect
	github.com/klauspost/compress v1.19.2 // indirect
	github.com/opencontainers/go-digest v1.0.0 // indirect
	github.com/opencontainers/image-spec v1.1.1 // indirect
	github.com/segmentio/asm v1.1.3 // indirect
	github.com/segmentio/encoding v0.5.4 // indirect
	github.com/sirupsen/logrus v1.9.4 // indirect
	github.com/stretchr/objx v0.5.3 // indirect
	github.com/yosida95/uritemplate/v3 v3.0.2 // indirect
	go.yaml.in/yaml/v2 v2.4.4 // indirect
	go.yaml.in/yaml/v3 v3.0.5 // indirect
	golang.org/x/oauth2 v0.36.0 // indirect
	golang.org/x/sync v0.22.0 // indirect
	golang.org/x/sys v0.47.0 // indirect
	golang.org/x/time v0.15.0 // indirect
)
