// Code generated by forge-dev. DO NOT EDIT.
// Source: spec.openapi.yaml
// SourceChecksum: sha256:e51c93866f9eac006b32557dea23ce00275d5211b130b4e548ac69d14d86d853

package main

import (
	"context"
	"fmt"

	"github.com/alexandremahdhaoui/forge/pkg/mcpserver"
	"github.com/alexandremahdhaoui/forge/pkg/mcptypes"
	"github.com/alexandremahdhaoui/forge/pkg/mcputil"
	"github.com/modelcontextprotocol/go-sdk/mcp"
)

// DeclareFunc is the handler signature for the declare tool.
// Report the resources this promotion needs. It needs none.
type DeclareFunc func(
	ctx context.Context,
	input DeclareInput,
) (*DeclareOutput, error)

// EvaluateFunc is the handler signature for the evaluate tool.
// Decide whether the stage advances.
type EvaluateFunc func(
	ctx context.Context,
	input PromotionInput,
) (*PromotionOutput, error)

// Handlers holds one implementation per tool declared in forge-dev.yaml.
// Every field is required. A nil field makes SetupMCPServer return an error
// rather than registering a tool that panics when called.
type Handlers struct {
	// Declare implements the declare tool.
	Declare DeclareFunc
	// Evaluate implements the evaluate tool.
	Evaluate EvaluateFunc
}

// SetupMCPServer creates the MCP server and registers every declared tool plus
// config-validate.
func SetupMCPServer(name string, version string, handlers Handlers) (*mcpserver.Server, error) {
	server := mcpserver.New(name, version)

	if handlers.Declare == nil {
		return nil, fmt.Errorf("Handlers.Declare is required for the %q tool", "declare")
	}

	mcpserver.RegisterTool(server, &mcp.Tool{
		Name:        "declare",
		Description: "Report the resources this promotion needs. It needs none.",
	}, wrapDeclare(handlers.Declare))

	if handlers.Evaluate == nil {
		return nil, fmt.Errorf("Handlers.Evaluate is required for the %q tool", "evaluate")
	}

	mcpserver.RegisterTool(server, &mcp.Tool{
		Name:        "evaluate",
		Description: "Decide whether the stage advances.",
	}, wrapEvaluate(handlers.Evaluate))

	mcpserver.RegisterTool(server, &mcp.Tool{
		Name:        "config-validate",
		Description: fmt.Sprintf("Validate %s engine-specific spec configuration.", name),
	}, handleConfigValidate)

	return server, nil
}

// wrapDeclare adapts DeclareFunc to the MCP tool handler shape.
func wrapDeclare(fn DeclareFunc) func(
	context.Context, *mcp.CallToolRequest, DeclareInput,
) (*mcp.CallToolResult, any, error) {
	return func(
		ctx context.Context,
		_ *mcp.CallToolRequest,
		input DeclareInput,
	) (*mcp.CallToolResult, any, error) {
		output, err := fn(ctx, input)
		if err != nil {
			return nil, nil, err
		}

		return nil, output, nil
	}
}

// wrapEvaluate adapts EvaluateFunc to the MCP tool handler shape.
func wrapEvaluate(fn EvaluateFunc) func(
	context.Context, *mcp.CallToolRequest, PromotionInput,
) (*mcp.CallToolResult, any, error) {
	return func(
		ctx context.Context,
		_ *mcp.CallToolRequest,
		input PromotionInput,
	) (*mcp.CallToolResult, any, error) {
		output, err := fn(ctx, input)
		if err != nil {
			return nil, nil, err
		}

		return nil, output, nil
	}
}

// handleConfigValidate handles the config-validate MCP tool.
func handleConfigValidate(
	_ context.Context,
	_ *mcp.CallToolRequest,
	input mcptypes.ConfigValidateInput,
) (*mcp.CallToolResult, any, error) {
	output := ValidateMap(input.Spec)

	if output.Valid {
		result, artifact := mcputil.SuccessResultWithArtifact("Configuration is valid", output)

		return result, artifact, nil
	}

	result, artifact := mcputil.SuccessResultWithArtifact(
		fmt.Sprintf("Configuration validation failed with %d error(s)", len(output.Errors)),
		output,
	)

	return result, artifact, nil
}
