// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package managercontrollermock

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"k8s.io/api/core/v1"
)

// NewMockKubernetes creates a new instance of MockKubernetes. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockKubernetes(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockKubernetes {
	mock := &MockKubernetes{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockKubernetes is an autogenerated mock type for the Kubernetes type
type MockKubernetes struct {
	mock.Mock
}

type MockKubernetes_Expecter struct {
	mock *mock.Mock
}

func (_m *MockKubernetes) EXPECT() *MockKubernetes_Expecter {
	return &MockKubernetes_Expecter{mock: &_m.Mock}
}

// CreateSecret provides a mock function for the type MockKubernetes
func (_mock *MockKubernetes) CreateSecret(ctx context.Context, secret *v1.Secret) error {
	ret := _mock.Called(ctx, secret)

	if len(ret) == 0 {
		panic("no return value specified for CreateSecret")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v1.Secret) error); ok {
		r0 = returnFunc(ctx, secret)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockKubernetes_CreateSecret_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateSecret'
type MockKubernetes_CreateSecret_Call struct {
	*mock.Call
}

// CreateSecret is a helper method to define mock.On call
//   - ctx context.Context
//   - secret *v1.Secret
func (_e *MockKubernetes_Expecter) CreateSecret(ctx any, secret any) *MockKubernetes_CreateSecret_Call {
	return &MockKubernetes_CreateSecret_Call{Call: _e.mock.On("CreateSecret", ctx, secret)}
}

func (_c *MockKubernetes_CreateSecret_Call) Run(run func(ctx context.Context, secret *v1.Secret)) *MockKubernetes_CreateSecret_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *v1.Secret
		if args[1] != nil {
			arg1 = args[1].(*v1.Secret)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockKubernetes_CreateSecret_Call) Return(err error) *MockKubernetes_CreateSecret_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockKubernetes_CreateSecret_Call) RunAndReturn(run func(ctx context.Context, secret *v1.Secret) error) *MockKubernetes_CreateSecret_Call {
	_c.Call.Return(run)
	return _c
}

// ReplaceSecret provides a mock function for the type MockKubernetes
func (_mock *MockKubernetes) ReplaceSecret(ctx context.Context, secret *v1.Secret) error {
	ret := _mock.Called(ctx, secret)

	if len(ret) == 0 {
		panic("no return value specified for ReplaceSecret")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v1.Secret) error); ok {
		r0 = returnFunc(ctx, secret)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockKubernetes_ReplaceSecret_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReplaceSecret'
type MockKubernetes_ReplaceSecret_Call struct {
	*mock.Call
}

// ReplaceSecret is a helper method to define mock.On call
//   - ctx context.Context
//   - secret *v1.Secret
func (_e *MockKubernetes_Expecter) ReplaceSecret(ctx any, secret any) *MockKubernetes_ReplaceSecret_Call {
	return &MockKubernetes_ReplaceSecret_Call{Call: _e.mock.On("ReplaceSecret", ctx, secret)}
}

func (_c *MockKubernetes_ReplaceSecret_Call) Run(run func(ctx context.Context, secret *v1.Secret)) *MockKubernetes_ReplaceSecret_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *v1.Secret
		if args[1] != nil {
			arg1 = args[1].(*v1.Secret)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockKubernetes_ReplaceSecret_Call) Return(err error) *MockKubernetes_ReplaceSecret_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockKubernetes_ReplaceSecret_Call) RunAndReturn(run func(ctx context.Context, secret *v1.Secret) error) *MockKubernetes_ReplaceSecret_Call {
	_c.Call.Return(run)
	return _c
}

// Secret provides a mock function for the type MockKubernetes
func (_mock *MockKubernetes) Secret(ctx context.Context, namespace string, name string) (*v1.Secret, bool, error) {
	ret := _mock.Called(ctx, namespace, name)

	if len(ret) == 0 {
		panic("no return value specified for Secret")
	}

	var r0 *v1.Secret
	var r1 bool
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*v1.Secret, bool, error)); ok {
		return returnFunc(ctx, namespace, name)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *v1.Secret); ok {
		r0 = returnFunc(ctx, namespace, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.Secret)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) bool); ok {
		r1 = returnFunc(ctx, namespace, name)
	} else {
		r1 = ret.Get(1).(bool)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string, string) error); ok {
		r2 = returnFunc(ctx, namespace, name)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockKubernetes_Secret_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Secret'
type MockKubernetes_Secret_Call struct {
	*mock.Call
}

// Secret is a helper method to define mock.On call
//   - ctx context.Context
//   - namespace string
//   - name string
func (_e *MockKubernetes_Expecter) Secret(ctx any, namespace any, name any) *MockKubernetes_Secret_Call {
	return &MockKubernetes_Secret_Call{Call: _e.mock.On("Secret", ctx, namespace, name)}
}

func (_c *MockKubernetes_Secret_Call) Run(run func(ctx context.Context, namespace string, name string)) *MockKubernetes_Secret_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockKubernetes_Secret_Call) Return(secret *v1.Secret, found bool, err error) *MockKubernetes_Secret_Call {
	_c.Call.Return(secret, found, err)
	return _c
}

func (_c *MockKubernetes_Secret_Call) RunAndReturn(run func(ctx context.Context, namespace string, name string) (*v1.Secret, bool, error)) *MockKubernetes_Secret_Call {
	_c.Call.Return(run)
	return _c
}
