// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package managercontrollermock

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"k8s.io/api/core/v1"
)

// NewMockKubernetes creates a new instance of MockKubernetes. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockKubernetes(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockKubernetes {
	mock := &MockKubernetes{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockKubernetes is an autogenerated mock type for the Kubernetes type
type MockKubernetes struct {
	mock.Mock
}

type MockKubernetes_Expecter struct {
	mock *mock.Mock
}

func (_m *MockKubernetes) EXPECT() *MockKubernetes_Expecter {
	return &MockKubernetes_Expecter{mock: &_m.Mock}
}

// APIServer provides a mock function for the type MockKubernetes
func (_mock *MockKubernetes) APIServer() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for APIServer")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockKubernetes_APIServer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'APIServer'
type MockKubernetes_APIServer_Call struct {
	*mock.Call
}

// APIServer is a helper method to define mock.On call
func (_e *MockKubernetes_Expecter) APIServer() *MockKubernetes_APIServer_Call {
	return &MockKubernetes_APIServer_Call{Call: _e.mock.On("APIServer")}
}

func (_c *MockKubernetes_APIServer_Call) Run(run func()) *MockKubernetes_APIServer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockKubernetes_APIServer_Call) Return(s string) *MockKubernetes_APIServer_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockKubernetes_APIServer_Call) RunAndReturn(run func() string) *MockKubernetes_APIServer_Call {
	_c.Call.Return(run)
	return _c
}

// Secret provides a mock function for the type MockKubernetes
func (_mock *MockKubernetes) Secret(ctx context.Context, namespace string, name string) (*v1.Secret, bool, error) {
	ret := _mock.Called(ctx, namespace, name)

	if len(ret) == 0 {
		panic("no return value specified for Secret")
	}

	var r0 *v1.Secret
	var r1 bool
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*v1.Secret, bool, error)); ok {
		return returnFunc(ctx, namespace, name)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *v1.Secret); ok {
		r0 = returnFunc(ctx, namespace, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.Secret)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) bool); ok {
		r1 = returnFunc(ctx, namespace, name)
	} else {
		r1 = ret.Get(1).(bool)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string, string) error); ok {
		r2 = returnFunc(ctx, namespace, name)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockKubernetes_Secret_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Secret'
type MockKubernetes_Secret_Call struct {
	*mock.Call
}

// Secret is a helper method to define mock.On call
//   - ctx context.Context
//   - namespace string
//   - name string
func (_e *MockKubernetes_Expecter) Secret(ctx any, namespace any, name any) *MockKubernetes_Secret_Call {
	return &MockKubernetes_Secret_Call{Call: _e.mock.On("Secret", ctx, namespace, name)}
}

func (_c *MockKubernetes_Secret_Call) Run(run func(ctx context.Context, namespace string, name string)) *MockKubernetes_Secret_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockKubernetes_Secret_Call) Return(secret *v1.Secret, found bool, err error) *MockKubernetes_Secret_Call {
	_c.Call.Return(secret, found, err)
	return _c
}

func (_c *MockKubernetes_Secret_Call) RunAndReturn(run func(ctx context.Context, namespace string, name string) (*v1.Secret, bool, error)) *MockKubernetes_Secret_Call {
	_c.Call.Return(run)
	return _c
}
