// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package managercontrollermock

import (
	"context"

	"github.com/alexandremahdhaoui/forge-ci/pkg/citypes"
	mock "github.com/stretchr/testify/mock"
)

// NewMockTalos creates a new instance of MockTalos. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTalos(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTalos {
	mock := &MockTalos{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTalos is an autogenerated mock type for the Talos type
type MockTalos struct {
	mock.Mock
}

type MockTalos_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTalos) EXPECT() *MockTalos_Expecter {
	return &MockTalos_Expecter{mock: &_m.Mock}
}

// ApplyMachineConfig provides a mock function for the type MockTalos
func (_mock *MockTalos) ApplyMachineConfig(ctx context.Context, node string, talosconfig citypes.Secret, config string) error {
	ret := _mock.Called(ctx, node, talosconfig, config)

	if len(ret) == 0 {
		panic("no return value specified for ApplyMachineConfig")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, citypes.Secret, string) error); ok {
		r0 = returnFunc(ctx, node, talosconfig, config)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTalos_ApplyMachineConfig_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ApplyMachineConfig'
type MockTalos_ApplyMachineConfig_Call struct {
	*mock.Call
}

// ApplyMachineConfig is a helper method to define mock.On call
//   - ctx context.Context
//   - node string
//   - talosconfig citypes.Secret
//   - config string
func (_e *MockTalos_Expecter) ApplyMachineConfig(ctx any, node any, talosconfig any, config any) *MockTalos_ApplyMachineConfig_Call {
	return &MockTalos_ApplyMachineConfig_Call{Call: _e.mock.On("ApplyMachineConfig", ctx, node, talosconfig, config)}
}

func (_c *MockTalos_ApplyMachineConfig_Call) Run(run func(ctx context.Context, node string, talosconfig citypes.Secret, config string)) *MockTalos_ApplyMachineConfig_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 citypes.Secret
		if args[2] != nil {
			arg2 = args[2].(citypes.Secret)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockTalos_ApplyMachineConfig_Call) Return(err error) *MockTalos_ApplyMachineConfig_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTalos_ApplyMachineConfig_Call) RunAndReturn(run func(ctx context.Context, node string, talosconfig citypes.Secret, config string) error) *MockTalos_ApplyMachineConfig_Call {
	_c.Call.Return(run)
	return _c
}

// MachineConfig provides a mock function for the type MockTalos
func (_mock *MockTalos) MachineConfig(ctx context.Context, node string, talosconfig citypes.Secret) (string, error) {
	ret := _mock.Called(ctx, node, talosconfig)

	if len(ret) == 0 {
		panic("no return value specified for MachineConfig")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, citypes.Secret) (string, error)); ok {
		return returnFunc(ctx, node, talosconfig)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, citypes.Secret) string); ok {
		r0 = returnFunc(ctx, node, talosconfig)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, citypes.Secret) error); ok {
		r1 = returnFunc(ctx, node, talosconfig)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTalos_MachineConfig_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MachineConfig'
type MockTalos_MachineConfig_Call struct {
	*mock.Call
}

// MachineConfig is a helper method to define mock.On call
//   - ctx context.Context
//   - node string
//   - talosconfig citypes.Secret
func (_e *MockTalos_Expecter) MachineConfig(ctx any, node any, talosconfig any) *MockTalos_MachineConfig_Call {
	return &MockTalos_MachineConfig_Call{Call: _e.mock.On("MachineConfig", ctx, node, talosconfig)}
}

func (_c *MockTalos_MachineConfig_Call) Run(run func(ctx context.Context, node string, talosconfig citypes.Secret)) *MockTalos_MachineConfig_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 citypes.Secret
		if args[2] != nil {
			arg2 = args[2].(citypes.Secret)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockTalos_MachineConfig_Call) Return(s string, err error) *MockTalos_MachineConfig_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockTalos_MachineConfig_Call) RunAndReturn(run func(ctx context.Context, node string, talosconfig citypes.Secret) (string, error)) *MockTalos_MachineConfig_Call {
	_c.Call.Return(run)
	return _c
}
