// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package managercontrollermock

import (
	"context"

	"github.com/hashicorp/terraform-json"
	mock "github.com/stretchr/testify/mock"
)

// NewMockTerraform creates a new instance of MockTerraform. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTerraform(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTerraform {
	mock := &MockTerraform{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTerraform is an autogenerated mock type for the Terraform type
type MockTerraform struct {
	mock.Mock
}

type MockTerraform_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTerraform) EXPECT() *MockTerraform_Expecter {
	return &MockTerraform_Expecter{mock: &_m.Mock}
}

// Apply provides a mock function for the type MockTerraform
func (_mock *MockTerraform) Apply(ctx context.Context, dir string) error {
	ret := _mock.Called(ctx, dir)

	if len(ret) == 0 {
		panic("no return value specified for Apply")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, dir)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTerraform_Apply_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Apply'
type MockTerraform_Apply_Call struct {
	*mock.Call
}

// Apply is a helper method to define mock.On call
//   - ctx context.Context
//   - dir string
func (_e *MockTerraform_Expecter) Apply(ctx any, dir any) *MockTerraform_Apply_Call {
	return &MockTerraform_Apply_Call{Call: _e.mock.On("Apply", ctx, dir)}
}

func (_c *MockTerraform_Apply_Call) Run(run func(ctx context.Context, dir string)) *MockTerraform_Apply_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTerraform_Apply_Call) Return(err error) *MockTerraform_Apply_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTerraform_Apply_Call) RunAndReturn(run func(ctx context.Context, dir string) error) *MockTerraform_Apply_Call {
	_c.Call.Return(run)
	return _c
}

// Init provides a mock function for the type MockTerraform
func (_mock *MockTerraform) Init(ctx context.Context, dir string) error {
	ret := _mock.Called(ctx, dir)

	if len(ret) == 0 {
		panic("no return value specified for Init")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, dir)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTerraform_Init_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Init'
type MockTerraform_Init_Call struct {
	*mock.Call
}

// Init is a helper method to define mock.On call
//   - ctx context.Context
//   - dir string
func (_e *MockTerraform_Expecter) Init(ctx any, dir any) *MockTerraform_Init_Call {
	return &MockTerraform_Init_Call{Call: _e.mock.On("Init", ctx, dir)}
}

func (_c *MockTerraform_Init_Call) Run(run func(ctx context.Context, dir string)) *MockTerraform_Init_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTerraform_Init_Call) Return(err error) *MockTerraform_Init_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTerraform_Init_Call) RunAndReturn(run func(ctx context.Context, dir string) error) *MockTerraform_Init_Call {
	_c.Call.Return(run)
	return _c
}

// Plan provides a mock function for the type MockTerraform
func (_mock *MockTerraform) Plan(ctx context.Context, dir string) (bool, *tfjson.Plan, error) {
	ret := _mock.Called(ctx, dir)

	if len(ret) == 0 {
		panic("no return value specified for Plan")
	}

	var r0 bool
	var r1 *tfjson.Plan
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (bool, *tfjson.Plan, error)); ok {
		return returnFunc(ctx, dir)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = returnFunc(ctx, dir)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) *tfjson.Plan); ok {
		r1 = returnFunc(ctx, dir)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*tfjson.Plan)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string) error); ok {
		r2 = returnFunc(ctx, dir)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockTerraform_Plan_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Plan'
type MockTerraform_Plan_Call struct {
	*mock.Call
}

// Plan is a helper method to define mock.On call
//   - ctx context.Context
//   - dir string
func (_e *MockTerraform_Expecter) Plan(ctx any, dir any) *MockTerraform_Plan_Call {
	return &MockTerraform_Plan_Call{Call: _e.mock.On("Plan", ctx, dir)}
}

func (_c *MockTerraform_Plan_Call) Run(run func(ctx context.Context, dir string)) *MockTerraform_Plan_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTerraform_Plan_Call) Return(reportsChanges bool, document *tfjson.Plan, err error) *MockTerraform_Plan_Call {
	_c.Call.Return(reportsChanges, document, err)
	return _c
}

func (_c *MockTerraform_Plan_Call) RunAndReturn(run func(ctx context.Context, dir string) (bool, *tfjson.Plan, error)) *MockTerraform_Plan_Call {
	_c.Call.Return(run)
	return _c
}
