// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package managercontrollermock

import (
	"context"

	"github.com/alexandremahdhaoui/forge-ci/internal/controller/managercontroller"
	mock "github.com/stretchr/testify/mock"
)

// NewMockHelm creates a new instance of MockHelm. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockHelm(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockHelm {
	mock := &MockHelm{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockHelm is an autogenerated mock type for the Helm type
type MockHelm struct {
	mock.Mock
}

type MockHelm_Expecter struct {
	mock *mock.Mock
}

func (_m *MockHelm) EXPECT() *MockHelm_Expecter {
	return &MockHelm_Expecter{mock: &_m.Mock}
}

// InstallRelease provides a mock function for the type MockHelm
func (_mock *MockHelm) InstallRelease(ctx context.Context, release managercontroller.HelmRelease) error {
	ret := _mock.Called(ctx, release)

	if len(ret) == 0 {
		panic("no return value specified for InstallRelease")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, managercontroller.HelmRelease) error); ok {
		r0 = returnFunc(ctx, release)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockHelm_InstallRelease_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InstallRelease'
type MockHelm_InstallRelease_Call struct {
	*mock.Call
}

// InstallRelease is a helper method to define mock.On call
//   - ctx context.Context
//   - release managercontroller.HelmRelease
func (_e *MockHelm_Expecter) InstallRelease(ctx any, release any) *MockHelm_InstallRelease_Call {
	return &MockHelm_InstallRelease_Call{Call: _e.mock.On("InstallRelease", ctx, release)}
}

func (_c *MockHelm_InstallRelease_Call) Run(run func(ctx context.Context, release managercontroller.HelmRelease)) *MockHelm_InstallRelease_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 managercontroller.HelmRelease
		if args[1] != nil {
			arg1 = args[1].(managercontroller.HelmRelease)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockHelm_InstallRelease_Call) Return(err error) *MockHelm_InstallRelease_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockHelm_InstallRelease_Call) RunAndReturn(run func(ctx context.Context, release managercontroller.HelmRelease) error) *MockHelm_InstallRelease_Call {
	_c.Call.Return(run)
	return _c
}

// Release provides a mock function for the type MockHelm
func (_mock *MockHelm) Release(ctx context.Context, namespace string, name string) (managercontroller.HelmRelease, bool, error) {
	ret := _mock.Called(ctx, namespace, name)

	if len(ret) == 0 {
		panic("no return value specified for Release")
	}

	var r0 managercontroller.HelmRelease
	var r1 bool
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (managercontroller.HelmRelease, bool, error)); ok {
		return returnFunc(ctx, namespace, name)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) managercontroller.HelmRelease); ok {
		r0 = returnFunc(ctx, namespace, name)
	} else {
		r0 = ret.Get(0).(managercontroller.HelmRelease)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) bool); ok {
		r1 = returnFunc(ctx, namespace, name)
	} else {
		r1 = ret.Get(1).(bool)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string, string) error); ok {
		r2 = returnFunc(ctx, namespace, name)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockHelm_Release_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Release'
type MockHelm_Release_Call struct {
	*mock.Call
}

// Release is a helper method to define mock.On call
//   - ctx context.Context
//   - namespace string
//   - name string
func (_e *MockHelm_Expecter) Release(ctx any, namespace any, name any) *MockHelm_Release_Call {
	return &MockHelm_Release_Call{Call: _e.mock.On("Release", ctx, namespace, name)}
}

func (_c *MockHelm_Release_Call) Run(run func(ctx context.Context, namespace string, name string)) *MockHelm_Release_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockHelm_Release_Call) Return(release managercontroller.HelmRelease, found bool, err error) *MockHelm_Release_Call {
	_c.Call.Return(release, found, err)
	return _c
}

func (_c *MockHelm_Release_Call) RunAndReturn(run func(ctx context.Context, namespace string, name string) (managercontroller.HelmRelease, bool, error)) *MockHelm_Release_Call {
	_c.Call.Return(run)
	return _c
}
