// Code generated by forge-dev. DO NOT EDIT.
// Source: forge-dev.yaml + spec.openapi.yaml
// SourceChecksum: sha256:734b41e14571b23af01bd94cc82a05b82929e2a6d55eefb069758a83903a3043

package main

import (
	"context"
	"fmt"

	"github.com/alexandremahdhaoui/forge/pkg/enginecli"
)

// Name is the engine name.
const Name = "ci-state-git"

// Version information (set via ldflags during build).
// Default is "dev" so GetEffectiveVersion() reads actual version from Go's debug.ReadBuildInfo()
// when running via "go run module@version".
var (
	Version        = "dev"
	CommitSHA      = "unknown"
	BuildTimestamp = "unknown"
)

// main is the entry point for the ci-state-git engine.
func main() {
	enginecli.Bootstrap(enginecli.Config{
		Name:           Name,
		Version:        Version,
		CommitSHA:      CommitSHA,
		BuildTimestamp: BuildTimestamp,
		RunCLI:         nil, // Generated engines are MCP-only
		RunMCP:         runMCPServer,
		DocsConfig:     docsConfig,
	})
}

// runMCPServer creates and runs the MCP server.
func runMCPServer() error {
	server, err := SetupMCPServer(Name, Version, NewHandlers())
	if err != nil {
		return fmt.Errorf("setting up MCP server: %w", err)
	}

	// Register docs MCP tools (docs-list, docs-get)
	if err := RegisterDocsMCPTools(server); err != nil {
		return fmt.Errorf("registering docs MCP tools: %w", err)
	}

	if err := server.Run(context.Background()); err != nil {
		return fmt.Errorf("running MCP server: %w", err)
	}

	return nil
}

// NewHandlers must be implemented by the engine author in a separate file.
// It returns one implementation per tool declared in forge-dev.yaml:
//
//	func NewHandlers() Handlers {
//		return Handlers{
//			Declare: func(ctx context.Context, input DeclareInput) (*DeclareOutput, error) {
//				panic("declare is not implemented")
//			},
//			Get: func(ctx context.Context, input StateGetInput) (*StateGetOutput, error) {
//				panic("get is not implemented")
//			},
//			Put: func(ctx context.Context, input StatePutInput) (*StateGetOutput, error) {
//				panic("put is not implemented")
//			},
//			List: func(ctx context.Context, input StateGetInput) (*StateListOutput, error) {
//				panic("list is not implemented")
//			},
//		}
//	}
