// Code generated by forge-dev. DO NOT EDIT.
// Source: spec.openapi.yaml
// SourceChecksum: sha256:7b8d05a887fd25d0820609a406c3ecb4189084473d9719f83d06df4bd17c8eee

package main

import (
	"context"
	"fmt"

	"github.com/alexandremahdhaoui/forge/pkg/mcpserver"
	"github.com/alexandremahdhaoui/forge/pkg/mcptypes"
	"github.com/alexandremahdhaoui/forge/pkg/mcputil"
	"github.com/modelcontextprotocol/go-sdk/mcp"
)

// DeclareFunc is the handler signature for the declare tool.
// Report the directories the state repo needs.
type DeclareFunc func(
	ctx context.Context,
	input DeclareInput,
) (*DeclareOutput, error)

// GetFunc is the handler signature for the get tool.
// Read one record.
type GetFunc func(
	ctx context.Context,
	input StateGetInput,
) (*StateGetOutput, error)

// PutFunc is the handler signature for the put tool.
// Write one record and commit it.
type PutFunc func(
	ctx context.Context,
	input StatePutInput,
) (*StateGetOutput, error)

// ListFunc is the handler signature for the list tool.
// List the keys under one kind.
type ListFunc func(
	ctx context.Context,
	input StateGetInput,
) (*StateListOutput, error)

// Handlers holds one implementation per tool declared in forge-dev.yaml.
// Every field is required. A nil field makes SetupMCPServer return an error
// rather than registering a tool that panics when called.
type Handlers struct {
	// Declare implements the declare tool.
	Declare DeclareFunc
	// Get implements the get tool.
	Get GetFunc
	// Put implements the put tool.
	Put PutFunc
	// List implements the list tool.
	List ListFunc
}

// SetupMCPServer creates the MCP server and registers every declared tool plus
// config-validate.
func SetupMCPServer(name string, version string, handlers Handlers) (*mcpserver.Server, error) {
	server := mcpserver.New(name, version)

	if handlers.Declare == nil {
		return nil, fmt.Errorf("Handlers.Declare is required for the %q tool", "declare")
	}

	mcpserver.RegisterTool(server, &mcp.Tool{
		Name:        "declare",
		Description: "Report the directories the state repo needs.",
	}, wrapDeclare(handlers.Declare))

	if handlers.Get == nil {
		return nil, fmt.Errorf("Handlers.Get is required for the %q tool", "get")
	}

	mcpserver.RegisterTool(server, &mcp.Tool{
		Name:        "get",
		Description: "Read one record.",
	}, wrapGet(handlers.Get))

	if handlers.Put == nil {
		return nil, fmt.Errorf("Handlers.Put is required for the %q tool", "put")
	}

	mcpserver.RegisterTool(server, &mcp.Tool{
		Name:        "put",
		Description: "Write one record and commit it.",
	}, wrapPut(handlers.Put))

	if handlers.List == nil {
		return nil, fmt.Errorf("Handlers.List is required for the %q tool", "list")
	}

	mcpserver.RegisterTool(server, &mcp.Tool{
		Name:        "list",
		Description: "List the keys under one kind.",
	}, wrapList(handlers.List))

	mcpserver.RegisterTool(server, &mcp.Tool{
		Name:        "config-validate",
		Description: fmt.Sprintf("Validate %s engine-specific spec configuration.", name),
	}, handleConfigValidate)

	return server, nil
}

// wrapDeclare adapts DeclareFunc to the MCP tool handler shape.
func wrapDeclare(fn DeclareFunc) func(
	context.Context, *mcp.CallToolRequest, DeclareInput,
) (*mcp.CallToolResult, any, error) {
	return func(
		ctx context.Context,
		_ *mcp.CallToolRequest,
		input DeclareInput,
	) (*mcp.CallToolResult, any, error) {
		output, err := fn(ctx, input)
		if err != nil {
			return nil, nil, err
		}

		return nil, output, nil
	}
}

// wrapGet adapts GetFunc to the MCP tool handler shape.
func wrapGet(fn GetFunc) func(
	context.Context, *mcp.CallToolRequest, StateGetInput,
) (*mcp.CallToolResult, any, error) {
	return func(
		ctx context.Context,
		_ *mcp.CallToolRequest,
		input StateGetInput,
	) (*mcp.CallToolResult, any, error) {
		output, err := fn(ctx, input)
		if err != nil {
			return nil, nil, err
		}

		return nil, output, nil
	}
}

// wrapPut adapts PutFunc to the MCP tool handler shape.
func wrapPut(fn PutFunc) func(
	context.Context, *mcp.CallToolRequest, StatePutInput,
) (*mcp.CallToolResult, any, error) {
	return func(
		ctx context.Context,
		_ *mcp.CallToolRequest,
		input StatePutInput,
	) (*mcp.CallToolResult, any, error) {
		output, err := fn(ctx, input)
		if err != nil {
			return nil, nil, err
		}

		return nil, output, nil
	}
}

// wrapList adapts ListFunc to the MCP tool handler shape.
func wrapList(fn ListFunc) func(
	context.Context, *mcp.CallToolRequest, StateGetInput,
) (*mcp.CallToolResult, any, error) {
	return func(
		ctx context.Context,
		_ *mcp.CallToolRequest,
		input StateGetInput,
	) (*mcp.CallToolResult, any, error) {
		output, err := fn(ctx, input)
		if err != nil {
			return nil, nil, err
		}

		return nil, output, nil
	}
}

// handleConfigValidate handles the config-validate MCP tool.
func handleConfigValidate(
	_ context.Context,
	_ *mcp.CallToolRequest,
	input mcptypes.ConfigValidateInput,
) (*mcp.CallToolResult, any, error) {
	output := ValidateMap(input.Spec)

	if output.Valid {
		result, artifact := mcputil.SuccessResultWithArtifact("Configuration is valid", output)

		return result, artifact, nil
	}

	result, artifact := mcputil.SuccessResultWithArtifact(
		fmt.Sprintf("Configuration validation failed with %d error(s)", len(output.Errors)),
		output,
	)

	return result, artifact, nil
}
