// Code generated by forge-dev. DO NOT EDIT.
// Source: spec.openapi.yaml
// SourceChecksum: sha256:7b8d05a887fd25d0820609a406c3ecb4189084473d9719f83d06df4bd17c8eee

package main

import (
	"fmt"

	"github.com/alexandremahdhaoui/forge/pkg/mcptypes"
)

// ValidateSpec validates a Spec and returns validation results.
// It checks required fields and validates enum values.
func ValidateSpec(s *Spec) *mcptypes.ConfigValidateOutput {
	if s == nil {
		return &mcptypes.ConfigValidateOutput{
			Valid: true,
		}
	}

	var errors []mcptypes.ValidationError

	if len(errors) > 0 {
		return &mcptypes.ConfigValidateOutput{
			Valid:  false,
			Errors: errors,
		}
	}

	return &mcptypes.ConfigValidateOutput{
		Valid: true,
	}
}

// ValidateDeclaredSubstage validates a DeclaredSubstage and returns validation results.
// It checks required fields and validates enum values.
func ValidateDeclaredSubstage(s *DeclaredSubstage) *mcptypes.ConfigValidateOutput {
	if s == nil {
		return &mcptypes.ConfigValidateOutput{
			Valid: true,
		}
	}

	var errors []mcptypes.ValidationError
	// Validate required field: name
	if s.Name == "" {
		errors = append(errors, mcptypes.ValidationError{
			Field:   "spec.name",
			Message: "required field is missing",
		})
	}

	if len(errors) > 0 {
		return &mcptypes.ConfigValidateOutput{
			Valid:  false,
			Errors: errors,
		}
	}

	return &mcptypes.ConfigValidateOutput{
		Valid: true,
	}
}

// ValidateRevision validates a Revision and returns validation results.
// It checks required fields and validates enum values.
func ValidateRevision(s *Revision) *mcptypes.ConfigValidateOutput {
	if s == nil {
		return &mcptypes.ConfigValidateOutput{
			Valid: true,
		}
	}

	var errors []mcptypes.ValidationError
	// Validate required field: createdAt
	if s.CreatedAt == "" {
		errors = append(errors, mcptypes.ValidationError{
			Field:   "spec.createdAt",
			Message: "required field is missing",
		})
	}
	// Validate required field: id
	if s.Id == "" {
		errors = append(errors, mcptypes.ValidationError{
			Field:   "spec.id",
			Message: "required field is missing",
		})
	}

	if len(errors) > 0 {
		return &mcptypes.ConfigValidateOutput{
			Valid:  false,
			Errors: errors,
		}
	}

	return &mcptypes.ConfigValidateOutput{
		Valid: true,
	}
}

// ValidateStateGetOutput validates a StateGetOutput and returns validation results.
// It checks required fields and validates enum values.
func ValidateStateGetOutput(s *StateGetOutput) *mcptypes.ConfigValidateOutput {
	if s == nil {
		return &mcptypes.ConfigValidateOutput{
			Valid: true,
		}
	}

	var errors []mcptypes.ValidationError

	if len(errors) > 0 {
		return &mcptypes.ConfigValidateOutput{
			Valid:  false,
			Errors: errors,
		}
	}

	return &mcptypes.ConfigValidateOutput{
		Valid: true,
	}
}

// ValidateStateListOutput validates a StateListOutput and returns validation results.
// It checks required fields and validates enum values.
func ValidateStateListOutput(s *StateListOutput) *mcptypes.ConfigValidateOutput {
	if s == nil {
		return &mcptypes.ConfigValidateOutput{
			Valid: true,
		}
	}

	var errors []mcptypes.ValidationError
	// Validate required field: keys
	if len(s.Keys) == 0 {
		errors = append(errors, mcptypes.ValidationError{
			Field:   "spec.keys",
			Message: "required field is missing or empty",
		})
	}

	if len(errors) > 0 {
		return &mcptypes.ConfigValidateOutput{
			Valid:  false,
			Errors: errors,
		}
	}

	return &mcptypes.ConfigValidateOutput{
		Valid: true,
	}
}

// ValidateResource validates a Resource and returns validation results.
// It checks required fields and validates enum values.
func ValidateResource(s *Resource) *mcptypes.ConfigValidateOutput {
	if s == nil {
		return &mcptypes.ConfigValidateOutput{
			Valid: true,
		}
	}

	var errors []mcptypes.ValidationError
	// Validate required field: kind
	if s.Kind == "" {
		errors = append(errors, mcptypes.ValidationError{
			Field:   "spec.kind",
			Message: "required field is missing",
		})
	}
	// Validate required field: name
	if s.Name == "" {
		errors = append(errors, mcptypes.ValidationError{
			Field:   "spec.name",
			Message: "required field is missing",
		})
	}
	// Validate nested reference: spec
	{
		nested := s.Spec
		nestedResult := ValidateSpec(&nested)
		if !nestedResult.Valid {
			for _, e := range nestedResult.Errors {
				errors = append(errors, mcptypes.ValidationError{
					Field:   "spec.spec." + e.Field,
					Message: e.Message,
				})
			}
		}
	}

	if len(errors) > 0 {
		return &mcptypes.ConfigValidateOutput{
			Valid:  false,
			Errors: errors,
		}
	}

	return &mcptypes.ConfigValidateOutput{
		Valid: true,
	}
}

// ValidateStateGetInput validates a StateGetInput and returns validation results.
// It checks required fields and validates enum values.
func ValidateStateGetInput(s *StateGetInput) *mcptypes.ConfigValidateOutput {
	if s == nil {
		return &mcptypes.ConfigValidateOutput{
			Valid: true,
		}
	}

	var errors []mcptypes.ValidationError
	// Validate required field: kind
	if s.Kind == "" {
		errors = append(errors, mcptypes.ValidationError{
			Field:   "spec.kind",
			Message: "required field is missing",
		})
	}
	// Validate nested reference: spec
	{
		nested := s.Spec
		nestedResult := ValidateSpec(&nested)
		if !nestedResult.Valid {
			for _, e := range nestedResult.Errors {
				errors = append(errors, mcptypes.ValidationError{
					Field:   "spec.spec." + e.Field,
					Message: e.Message,
				})
			}
		}
	}

	if len(errors) > 0 {
		return &mcptypes.ConfigValidateOutput{
			Valid:  false,
			Errors: errors,
		}
	}

	return &mcptypes.ConfigValidateOutput{
		Valid: true,
	}
}

// ValidateStatePutInput validates a StatePutInput and returns validation results.
// It checks required fields and validates enum values.
func ValidateStatePutInput(s *StatePutInput) *mcptypes.ConfigValidateOutput {
	if s == nil {
		return &mcptypes.ConfigValidateOutput{
			Valid: true,
		}
	}

	var errors []mcptypes.ValidationError
	// Validate required field: key
	if s.Key == "" {
		errors = append(errors, mcptypes.ValidationError{
			Field:   "spec.key",
			Message: "required field is missing",
		})
	}
	// Validate required field: kind
	if s.Kind == "" {
		errors = append(errors, mcptypes.ValidationError{
			Field:   "spec.kind",
			Message: "required field is missing",
		})
	}
	// Validate required field: payload
	if s.Payload == "" {
		errors = append(errors, mcptypes.ValidationError{
			Field:   "spec.payload",
			Message: "required field is missing",
		})
	}
	// Validate nested reference: spec
	{
		nested := s.Spec
		nestedResult := ValidateSpec(&nested)
		if !nestedResult.Valid {
			for _, e := range nestedResult.Errors {
				errors = append(errors, mcptypes.ValidationError{
					Field:   "spec.spec." + e.Field,
					Message: e.Message,
				})
			}
		}
	}

	if len(errors) > 0 {
		return &mcptypes.ConfigValidateOutput{
			Valid:  false,
			Errors: errors,
		}
	}

	return &mcptypes.ConfigValidateOutput{
		Valid: true,
	}
}

// ValidateDeclaredStage validates a DeclaredStage and returns validation results.
// It checks required fields and validates enum values.
func ValidateDeclaredStage(s *DeclaredStage) *mcptypes.ConfigValidateOutput {
	if s == nil {
		return &mcptypes.ConfigValidateOutput{
			Valid: true,
		}
	}

	var errors []mcptypes.ValidationError
	// Validate required field: name
	if s.Name == "" {
		errors = append(errors, mcptypes.ValidationError{
			Field:   "spec.name",
			Message: "required field is missing",
		})
	}
	// Validate array of references: substages
	for i, item := range s.Substages {
		nestedResult := ValidateDeclaredSubstage(&item)
		if !nestedResult.Valid {
			for _, e := range nestedResult.Errors {
				errors = append(errors, mcptypes.ValidationError{
					Field:   fmt.Sprintf("spec.substages[%d].%s", i, e.Field),
					Message: e.Message,
				})
			}
		}
	}

	if len(errors) > 0 {
		return &mcptypes.ConfigValidateOutput{
			Valid:  false,
			Errors: errors,
		}
	}

	return &mcptypes.ConfigValidateOutput{
		Valid: true,
	}
}

// ValidateDeclareOutput validates a DeclareOutput and returns validation results.
// It checks required fields and validates enum values.
func ValidateDeclareOutput(s *DeclareOutput) *mcptypes.ConfigValidateOutput {
	if s == nil {
		return &mcptypes.ConfigValidateOutput{
			Valid: true,
		}
	}

	var errors []mcptypes.ValidationError
	// Validate required array of references: resources
	if len(s.Resources) == 0 {
		errors = append(errors, mcptypes.ValidationError{
			Field:   "spec.resources",
			Message: "required field is missing or empty",
		})
	}
	// Validate array of references: resources
	for i, item := range s.Resources {
		nestedResult := ValidateResource(&item)
		if !nestedResult.Valid {
			for _, e := range nestedResult.Errors {
				errors = append(errors, mcptypes.ValidationError{
					Field:   fmt.Sprintf("spec.resources[%d].%s", i, e.Field),
					Message: e.Message,
				})
			}
		}
	}

	if len(errors) > 0 {
		return &mcptypes.ConfigValidateOutput{
			Valid:  false,
			Errors: errors,
		}
	}

	return &mcptypes.ConfigValidateOutput{
		Valid: true,
	}
}

// ValidateDeclareInput validates a DeclareInput and returns validation results.
// It checks required fields and validates enum values.
func ValidateDeclareInput(s *DeclareInput) *mcptypes.ConfigValidateOutput {
	if s == nil {
		return &mcptypes.ConfigValidateOutput{
			Valid: true,
		}
	}

	var errors []mcptypes.ValidationError
	// Validate nested reference: spec
	{
		nested := s.Spec
		nestedResult := ValidateSpec(&nested)
		if !nestedResult.Valid {
			for _, e := range nestedResult.Errors {
				errors = append(errors, mcptypes.ValidationError{
					Field:   "spec.spec." + e.Field,
					Message: e.Message,
				})
			}
		}
	}
	// Validate array of references: stages
	for i, item := range s.Stages {
		nestedResult := ValidateDeclaredStage(&item)
		if !nestedResult.Valid {
			for _, e := range nestedResult.Errors {
				errors = append(errors, mcptypes.ValidationError{
					Field:   fmt.Sprintf("spec.stages[%d].%s", i, e.Field),
					Message: e.Message,
				})
			}
		}
	}

	if len(errors) > 0 {
		return &mcptypes.ConfigValidateOutput{
			Valid:  false,
			Errors: errors,
		}
	}

	return &mcptypes.ConfigValidateOutput{
		Valid: true,
	}
}

// Validate validates a Spec and returns validation results.
// This is the main entry point for validation.
func Validate(s *Spec) *mcptypes.ConfigValidateOutput {
	return ValidateSpec(s)
}

// ValidateMap validates a map[string]interface{} by first parsing it to a Spec.
// This is a convenience function for validating spec data from forge.yaml.
func ValidateMap(m map[string]interface{}) *mcptypes.ConfigValidateOutput {
	s, err := FromMap(m)
	if err != nil {
		return &mcptypes.ConfigValidateOutput{
			Valid: false,
			Errors: []mcptypes.ValidationError{
				{
					Field:   "spec",
					Message: err.Error(),
				},
			},
		}
	}

	return Validate(s)
}
