// Code generated by forge-dev. DO NOT EDIT.
// Source: spec.openapi.yaml
// SourceChecksum: sha256:5aab53dd416fad314f962bbd003d2784ba831092c5d7f1c9e128cc84fbd69095

package main

import (
	"fmt"
)

// DeclaredRepo represents the DeclaredRepo configuration.
// One repository of the pipeline, by the directory name it is checked out under.
type DeclaredRepo struct {
	Name string `json:"name"`
}

// Spec represents the Spec configuration.
// Engine specific configuration. The core model fixes the shape of a revision. Each engine keeps this block for its own internals, so ci-state-git takes a path and a DynamoDB engine takes a table and a region, and nothing in the core model knows about either.
type Spec map[string]interface{}

// DeclaredSubstage represents the DeclaredSubstage configuration.
// One substage of a stage, by name.
type DeclaredSubstage struct {
	// What to call this substage where a person reads it. Absent means the caller derives a title from the stage and substage names.
	DisplayName string `json:"displayName,omitempty"`
	Name        string `json:"name"`
	// Substages of the same stage that must advance before this one runs, for a compute engine that renders one job per substage and has to wire the order between them. Absent means none.
	Needs []string `json:"needs,omitempty"`
	// Substages of EARLIER stages, as <stage>/<substage>, whose built artifacts this one reads, for a compute engine that carries files between jobs and can then carry only these. Absent means everything every earlier stage built.
	Uses []string `json:"uses,omitempty"`
}

// Revision represents the Revision configuration.
// A tuple of repo commits at a moment in time. The id is derived from the tuple, so the same commits always give the same revision.
type Revision struct {
	// When the revision was resolved.
	CreatedAt string `json:"createdAt"`
	// Repos with uncommitted changes, sorted.
	Dirty []string `json:"dirty,omitempty"`
	// Content derived identifier. Suffixed with -dirty when any repo has uncommitted changes, because an uncommitted break must not reuse a passing run.
	Id string `json:"id"`
	// Repo name to commit SHA. Empty when the pipeline declares no repos.
	Repos map[string]string `json:"repos,omitempty"`
}

// StateGetOutput represents the StateGetOutput configuration.
// The result of a read. A missing record is found false, never an error.
type StateGetOutput struct {
	Found   bool   `json:"found"`
	Payload string `json:"payload,omitempty"`
}

// StateListOutput represents the StateListOutput configuration.
// The keys under one kind.
type StateListOutput struct {
	Keys []string `json:"keys"`
}

// Resource represents the Resource configuration.
// Something an engine needs to exist. Declared by engines, realized by managers.
type Resource struct {
	// Resource kind, for example directory or table.
	Kind string `json:"kind"`
	// Unique name within the kind.
	Name string `json:"name"`
	Spec Spec   `json:"spec,omitempty"`
}

// StateGetInput represents the StateGetInput configuration.
// Read one record, or list under one kind when key is a prefix.
type StateGetInput struct {
	// Identifies the record within its kind. Nested keys use slashes.
	Key string `json:"key,omitempty"`
	// The record family. revision, run or owned.
	Kind string `json:"kind"`
	Spec Spec   `json:"spec,omitempty"`
}

// StatePutInput represents the StatePutInput configuration.
// Write one record.
type StatePutInput struct {
	Key  string `json:"key"`
	Kind string `json:"kind"`
	// The record body. A string, not bytes. A byte array marshals to base64 and the generated MCP schema rejects it, which broke every state write while passing in process.
	Payload string `json:"payload"`
	Spec    Spec   `json:"spec,omitempty"`
}

// DeclaredStage represents the DeclaredStage configuration.
// One stage of the pipeline, by name, with its substages.
type DeclaredStage struct {
	// What to call this stage where a person reads it. Absent means the caller derives a title from the name, so a pipeline that says nothing still reads as words rather than as an identifier.
	DisplayName string             `json:"displayName,omitempty"`
	Name        string             `json:"name"`
	Substages   []DeclaredSubstage `json:"substages,omitempty"`
}

// DeclareOutput represents the DeclareOutput configuration.
// What an engine needs to exist. An engine with no infrastructure returns an empty list.
type DeclareOutput struct {
	Resources []Resource `json:"resources"`
}

// DeclareInput represents the DeclareInput configuration.
// What an engine is asked with when it reports what it needs. It carries the engine's own spec block and the pipeline root, because an engine declares its resources before any record exists to name.
type DeclareInput struct {
	// The pipeline's repositories by name, each a directory under the root, for a compute engine that keys a cache on what the run is built from - the same repositories the revision hashes. A state engine ignores them.
	Repos []DeclaredRepo `json:"repos,omitempty"`
	// The pipeline root on the local filesystem, for an engine whose spec names workspace files to read at declare time. Optional, so an engine that reads nothing keeps validating without it.
	Root string `json:"root,omitempty"`
	Spec Spec   `json:"spec,omitempty"`
	// The pipeline's stages by name, each with its substages, for a compute engine that renders the run as jobs. A state engine ignores them; they are here so the one declare input the core sends validates against every engine's schema.
	Stages []DeclaredStage `json:"stages,omitempty"`
}

// DeclaredRepoFromMap creates a DeclaredRepo from a map[string]interface{}.
func DeclaredRepoFromMap(m map[string]interface{}) (*DeclaredRepo, error) {
	if m == nil {
		return &DeclaredRepo{}, nil
	}

	s := &DeclaredRepo{}

	// A key the schema does not name is refused, by name, with the keys
	// it could have been. A spec that silently dropped it read as
	// configuration that took effect: forge's own ldflags on go-build was
	// exactly that for weeks.
	for key := range m {
		switch key {
		case "name":
		default:
			return nil, fmt.Errorf("field %s: not a key of DeclaredRepo; the keys are name", key)
		}
	}
	// Parse name
	if v, ok := m["name"]; ok && v != nil {
		if val, ok := v.(string); ok {
			s.Name = val
		} else {
			return nil, fmt.Errorf("field name: expected string, got %T", v)
		}
	}
	return s, nil
}

// SpecFromMap creates a Spec from a map[string]interface{}.
func SpecFromMap(m map[string]interface{}) (*Spec, error) {
	if m == nil {
		return &Spec{}, nil
	}

	s := &Spec{}

	// A key the schema does not name is refused, by name, with the keys
	// it could have been. A spec that silently dropped it read as
	// configuration that took effect: forge's own ldflags on go-build was
	// exactly that for weeks.
	for key := range m {
		switch key {
		default:
			return nil, fmt.Errorf("field %s: not a key of Spec; the keys are", key)
		}
	}
	return s, nil
}

// DeclaredSubstageFromMap creates a DeclaredSubstage from a map[string]interface{}.
func DeclaredSubstageFromMap(m map[string]interface{}) (*DeclaredSubstage, error) {
	if m == nil {
		return &DeclaredSubstage{}, nil
	}

	s := &DeclaredSubstage{}

	// A key the schema does not name is refused, by name, with the keys
	// it could have been. A spec that silently dropped it read as
	// configuration that took effect: forge's own ldflags on go-build was
	// exactly that for weeks.
	for key := range m {
		switch key {
		case "displayName":
		case "name":
		case "needs":
		case "uses":
		default:
			return nil, fmt.Errorf("field %s: not a key of DeclaredSubstage; the keys are displayName, name, needs, uses", key)
		}
	}
	// Parse displayName
	if v, ok := m["displayName"]; ok && v != nil {
		if val, ok := v.(string); ok {
			s.DisplayName = val
		} else {
			return nil, fmt.Errorf("field displayName: expected string, got %T", v)
		}
	}
	// Parse name
	if v, ok := m["name"]; ok && v != nil {
		if val, ok := v.(string); ok {
			s.Name = val
		} else {
			return nil, fmt.Errorf("field name: expected string, got %T", v)
		}
	}
	// Parse needs
	if v, ok := m["needs"]; ok && v != nil {
		if arr, ok := v.([]interface{}); ok {
			s.Needs = make([]string, 0, len(arr))
			for i, item := range arr {
				if str, ok := item.(string); ok {
					s.Needs = append(s.Needs, str)
				} else {
					return nil, fmt.Errorf("field needs[%d]: expected string, got %T", i, item)
				}
			}
		} else if arr, ok := v.([]string); ok {
			s.Needs = arr
		} else {
			return nil, fmt.Errorf("field needs: expected []string, got %T", v)
		}
	}
	// Parse uses
	if v, ok := m["uses"]; ok && v != nil {
		if arr, ok := v.([]interface{}); ok {
			s.Uses = make([]string, 0, len(arr))
			for i, item := range arr {
				if str, ok := item.(string); ok {
					s.Uses = append(s.Uses, str)
				} else {
					return nil, fmt.Errorf("field uses[%d]: expected string, got %T", i, item)
				}
			}
		} else if arr, ok := v.([]string); ok {
			s.Uses = arr
		} else {
			return nil, fmt.Errorf("field uses: expected []string, got %T", v)
		}
	}
	return s, nil
}

// RevisionFromMap creates a Revision from a map[string]interface{}.
func RevisionFromMap(m map[string]interface{}) (*Revision, error) {
	if m == nil {
		return &Revision{}, nil
	}

	s := &Revision{}

	// A key the schema does not name is refused, by name, with the keys
	// it could have been. A spec that silently dropped it read as
	// configuration that took effect: forge's own ldflags on go-build was
	// exactly that for weeks.
	for key := range m {
		switch key {
		case "createdAt":
		case "dirty":
		case "id":
		case "repos":
		default:
			return nil, fmt.Errorf("field %s: not a key of Revision; the keys are createdAt, dirty, id, repos", key)
		}
	}
	// Parse createdAt
	if v, ok := m["createdAt"]; ok && v != nil {
		if val, ok := v.(string); ok {
			s.CreatedAt = val
		} else {
			return nil, fmt.Errorf("field createdAt: expected string, got %T", v)
		}
	}
	// Parse dirty
	if v, ok := m["dirty"]; ok && v != nil {
		if arr, ok := v.([]interface{}); ok {
			s.Dirty = make([]string, 0, len(arr))
			for i, item := range arr {
				if str, ok := item.(string); ok {
					s.Dirty = append(s.Dirty, str)
				} else {
					return nil, fmt.Errorf("field dirty[%d]: expected string, got %T", i, item)
				}
			}
		} else if arr, ok := v.([]string); ok {
			s.Dirty = arr
		} else {
			return nil, fmt.Errorf("field dirty: expected []string, got %T", v)
		}
	}
	// Parse id
	if v, ok := m["id"]; ok && v != nil {
		if val, ok := v.(string); ok {
			s.Id = val
		} else {
			return nil, fmt.Errorf("field id: expected string, got %T", v)
		}
	}
	// Parse repos
	if v, ok := m["repos"]; ok && v != nil {
		if mapVal, ok := v.(map[string]interface{}); ok {
			s.Repos = make(map[string]string, len(mapVal))
			for key, val := range mapVal {
				if str, ok := val.(string); ok {
					s.Repos[key] = str
				} else {
					return nil, fmt.Errorf("field repos[%s]: expected string, got %T", key, val)
				}
			}
		} else if mapVal, ok := v.(map[string]string); ok {
			s.Repos = mapVal
		} else {
			return nil, fmt.Errorf("field repos: expected map[string]string, got %T", v)
		}
	}
	return s, nil
}

// StateGetOutputFromMap creates a StateGetOutput from a map[string]interface{}.
func StateGetOutputFromMap(m map[string]interface{}) (*StateGetOutput, error) {
	if m == nil {
		return &StateGetOutput{}, nil
	}

	s := &StateGetOutput{}

	// A key the schema does not name is refused, by name, with the keys
	// it could have been. A spec that silently dropped it read as
	// configuration that took effect: forge's own ldflags on go-build was
	// exactly that for weeks.
	for key := range m {
		switch key {
		case "found":
		case "payload":
		default:
			return nil, fmt.Errorf("field %s: not a key of StateGetOutput; the keys are found, payload", key)
		}
	}
	// Parse found
	if v, ok := m["found"]; ok && v != nil {
		if val, ok := v.(bool); ok {
			s.Found = val
		} else {
			return nil, fmt.Errorf("field found: expected bool, got %T", v)
		}
	}
	// Parse payload
	if v, ok := m["payload"]; ok && v != nil {
		if val, ok := v.(string); ok {
			s.Payload = val
		} else {
			return nil, fmt.Errorf("field payload: expected string, got %T", v)
		}
	}
	return s, nil
}

// StateListOutputFromMap creates a StateListOutput from a map[string]interface{}.
func StateListOutputFromMap(m map[string]interface{}) (*StateListOutput, error) {
	if m == nil {
		return &StateListOutput{}, nil
	}

	s := &StateListOutput{}

	// A key the schema does not name is refused, by name, with the keys
	// it could have been. A spec that silently dropped it read as
	// configuration that took effect: forge's own ldflags on go-build was
	// exactly that for weeks.
	for key := range m {
		switch key {
		case "keys":
		default:
			return nil, fmt.Errorf("field %s: not a key of StateListOutput; the keys are keys", key)
		}
	}
	// Parse keys
	if v, ok := m["keys"]; ok && v != nil {
		if arr, ok := v.([]interface{}); ok {
			s.Keys = make([]string, 0, len(arr))
			for i, item := range arr {
				if str, ok := item.(string); ok {
					s.Keys = append(s.Keys, str)
				} else {
					return nil, fmt.Errorf("field keys[%d]: expected string, got %T", i, item)
				}
			}
		} else if arr, ok := v.([]string); ok {
			s.Keys = arr
		} else {
			return nil, fmt.Errorf("field keys: expected []string, got %T", v)
		}
	}
	return s, nil
}

// ResourceFromMap creates a Resource from a map[string]interface{}.
func ResourceFromMap(m map[string]interface{}) (*Resource, error) {
	if m == nil {
		return &Resource{}, nil
	}

	s := &Resource{}

	// A key the schema does not name is refused, by name, with the keys
	// it could have been. A spec that silently dropped it read as
	// configuration that took effect: forge's own ldflags on go-build was
	// exactly that for weeks.
	for key := range m {
		switch key {
		case "kind":
		case "name":
		case "spec":
		default:
			return nil, fmt.Errorf("field %s: not a key of Resource; the keys are kind, name, spec", key)
		}
	}
	// Parse kind
	if v, ok := m["kind"]; ok && v != nil {
		if val, ok := v.(string); ok {
			s.Kind = val
		} else {
			return nil, fmt.Errorf("field kind: expected string, got %T", v)
		}
	}
	// Parse name
	if v, ok := m["name"]; ok && v != nil {
		if val, ok := v.(string); ok {
			s.Name = val
		} else {
			return nil, fmt.Errorf("field name: expected string, got %T", v)
		}
	}
	// Parse spec
	if v, ok := m["spec"]; ok && v != nil {
		if obj, ok := v.(map[string]interface{}); ok {
			ref, err := SpecFromMap(obj)
			if err != nil {
				return nil, fmt.Errorf("field spec: %w", err)
			}
			if ref != nil {
				s.Spec = *ref
			}
		} else {
			return nil, fmt.Errorf("field spec: expected object, got %T", v)
		}
	}
	return s, nil
}

// StateGetInputFromMap creates a StateGetInput from a map[string]interface{}.
func StateGetInputFromMap(m map[string]interface{}) (*StateGetInput, error) {
	if m == nil {
		return &StateGetInput{}, nil
	}

	s := &StateGetInput{}

	// A key the schema does not name is refused, by name, with the keys
	// it could have been. A spec that silently dropped it read as
	// configuration that took effect: forge's own ldflags on go-build was
	// exactly that for weeks.
	for key := range m {
		switch key {
		case "key":
		case "kind":
		case "spec":
		default:
			return nil, fmt.Errorf("field %s: not a key of StateGetInput; the keys are key, kind, spec", key)
		}
	}
	// Parse key
	if v, ok := m["key"]; ok && v != nil {
		if val, ok := v.(string); ok {
			s.Key = val
		} else {
			return nil, fmt.Errorf("field key: expected string, got %T", v)
		}
	}
	// Parse kind
	if v, ok := m["kind"]; ok && v != nil {
		if val, ok := v.(string); ok {
			s.Kind = val
		} else {
			return nil, fmt.Errorf("field kind: expected string, got %T", v)
		}
	}
	// Parse spec
	if v, ok := m["spec"]; ok && v != nil {
		if obj, ok := v.(map[string]interface{}); ok {
			ref, err := SpecFromMap(obj)
			if err != nil {
				return nil, fmt.Errorf("field spec: %w", err)
			}
			if ref != nil {
				s.Spec = *ref
			}
		} else {
			return nil, fmt.Errorf("field spec: expected object, got %T", v)
		}
	}
	return s, nil
}

// StatePutInputFromMap creates a StatePutInput from a map[string]interface{}.
func StatePutInputFromMap(m map[string]interface{}) (*StatePutInput, error) {
	if m == nil {
		return &StatePutInput{}, nil
	}

	s := &StatePutInput{}

	// A key the schema does not name is refused, by name, with the keys
	// it could have been. A spec that silently dropped it read as
	// configuration that took effect: forge's own ldflags on go-build was
	// exactly that for weeks.
	for key := range m {
		switch key {
		case "key":
		case "kind":
		case "payload":
		case "spec":
		default:
			return nil, fmt.Errorf("field %s: not a key of StatePutInput; the keys are key, kind, payload, spec", key)
		}
	}
	// Parse key
	if v, ok := m["key"]; ok && v != nil {
		if val, ok := v.(string); ok {
			s.Key = val
		} else {
			return nil, fmt.Errorf("field key: expected string, got %T", v)
		}
	}
	// Parse kind
	if v, ok := m["kind"]; ok && v != nil {
		if val, ok := v.(string); ok {
			s.Kind = val
		} else {
			return nil, fmt.Errorf("field kind: expected string, got %T", v)
		}
	}
	// Parse payload
	if v, ok := m["payload"]; ok && v != nil {
		if val, ok := v.(string); ok {
			s.Payload = val
		} else {
			return nil, fmt.Errorf("field payload: expected string, got %T", v)
		}
	}
	// Parse spec
	if v, ok := m["spec"]; ok && v != nil {
		if obj, ok := v.(map[string]interface{}); ok {
			ref, err := SpecFromMap(obj)
			if err != nil {
				return nil, fmt.Errorf("field spec: %w", err)
			}
			if ref != nil {
				s.Spec = *ref
			}
		} else {
			return nil, fmt.Errorf("field spec: expected object, got %T", v)
		}
	}
	return s, nil
}

// DeclaredStageFromMap creates a DeclaredStage from a map[string]interface{}.
func DeclaredStageFromMap(m map[string]interface{}) (*DeclaredStage, error) {
	if m == nil {
		return &DeclaredStage{}, nil
	}

	s := &DeclaredStage{}

	// A key the schema does not name is refused, by name, with the keys
	// it could have been. A spec that silently dropped it read as
	// configuration that took effect: forge's own ldflags on go-build was
	// exactly that for weeks.
	for key := range m {
		switch key {
		case "displayName":
		case "name":
		case "substages":
		default:
			return nil, fmt.Errorf("field %s: not a key of DeclaredStage; the keys are displayName, name, substages", key)
		}
	}
	// Parse displayName
	if v, ok := m["displayName"]; ok && v != nil {
		if val, ok := v.(string); ok {
			s.DisplayName = val
		} else {
			return nil, fmt.Errorf("field displayName: expected string, got %T", v)
		}
	}
	// Parse name
	if v, ok := m["name"]; ok && v != nil {
		if val, ok := v.(string); ok {
			s.Name = val
		} else {
			return nil, fmt.Errorf("field name: expected string, got %T", v)
		}
	}
	// Parse substages
	if v, ok := m["substages"]; ok && v != nil {
		if arr, ok := v.([]interface{}); ok {
			s.Substages = make([]DeclaredSubstage, 0, len(arr))
			for i, item := range arr {
				if obj, ok := item.(map[string]interface{}); ok {
					ref, err := DeclaredSubstageFromMap(obj)
					if err != nil {
						return nil, fmt.Errorf("field substages[%d]: %w", i, err)
					}
					if ref != nil {
						s.Substages = append(s.Substages, *ref)
					}
				} else {
					return nil, fmt.Errorf("field substages[%d]: expected object, got %T", i, item)
				}
			}
		} else {
			return nil, fmt.Errorf("field substages: expected []object, got %T", v)
		}
	}
	return s, nil
}

// DeclareOutputFromMap creates a DeclareOutput from a map[string]interface{}.
func DeclareOutputFromMap(m map[string]interface{}) (*DeclareOutput, error) {
	if m == nil {
		return &DeclareOutput{}, nil
	}

	s := &DeclareOutput{}

	// A key the schema does not name is refused, by name, with the keys
	// it could have been. A spec that silently dropped it read as
	// configuration that took effect: forge's own ldflags on go-build was
	// exactly that for weeks.
	for key := range m {
		switch key {
		case "resources":
		default:
			return nil, fmt.Errorf("field %s: not a key of DeclareOutput; the keys are resources", key)
		}
	}
	// Parse resources
	if v, ok := m["resources"]; ok && v != nil {
		if arr, ok := v.([]interface{}); ok {
			s.Resources = make([]Resource, 0, len(arr))
			for i, item := range arr {
				if obj, ok := item.(map[string]interface{}); ok {
					ref, err := ResourceFromMap(obj)
					if err != nil {
						return nil, fmt.Errorf("field resources[%d]: %w", i, err)
					}
					if ref != nil {
						s.Resources = append(s.Resources, *ref)
					}
				} else {
					return nil, fmt.Errorf("field resources[%d]: expected object, got %T", i, item)
				}
			}
		} else {
			return nil, fmt.Errorf("field resources: expected []object, got %T", v)
		}
	}
	return s, nil
}

// DeclareInputFromMap creates a DeclareInput from a map[string]interface{}.
func DeclareInputFromMap(m map[string]interface{}) (*DeclareInput, error) {
	if m == nil {
		return &DeclareInput{}, nil
	}

	s := &DeclareInput{}

	// A key the schema does not name is refused, by name, with the keys
	// it could have been. A spec that silently dropped it read as
	// configuration that took effect: forge's own ldflags on go-build was
	// exactly that for weeks.
	for key := range m {
		switch key {
		case "repos":
		case "root":
		case "spec":
		case "stages":
		default:
			return nil, fmt.Errorf("field %s: not a key of DeclareInput; the keys are repos, root, spec, stages", key)
		}
	}
	// Parse repos
	if v, ok := m["repos"]; ok && v != nil {
		if arr, ok := v.([]interface{}); ok {
			s.Repos = make([]DeclaredRepo, 0, len(arr))
			for i, item := range arr {
				if obj, ok := item.(map[string]interface{}); ok {
					ref, err := DeclaredRepoFromMap(obj)
					if err != nil {
						return nil, fmt.Errorf("field repos[%d]: %w", i, err)
					}
					if ref != nil {
						s.Repos = append(s.Repos, *ref)
					}
				} else {
					return nil, fmt.Errorf("field repos[%d]: expected object, got %T", i, item)
				}
			}
		} else {
			return nil, fmt.Errorf("field repos: expected []object, got %T", v)
		}
	}
	// Parse root
	if v, ok := m["root"]; ok && v != nil {
		if val, ok := v.(string); ok {
			s.Root = val
		} else {
			return nil, fmt.Errorf("field root: expected string, got %T", v)
		}
	}
	// Parse spec
	if v, ok := m["spec"]; ok && v != nil {
		if obj, ok := v.(map[string]interface{}); ok {
			ref, err := SpecFromMap(obj)
			if err != nil {
				return nil, fmt.Errorf("field spec: %w", err)
			}
			if ref != nil {
				s.Spec = *ref
			}
		} else {
			return nil, fmt.Errorf("field spec: expected object, got %T", v)
		}
	}
	// Parse stages
	if v, ok := m["stages"]; ok && v != nil {
		if arr, ok := v.([]interface{}); ok {
			s.Stages = make([]DeclaredStage, 0, len(arr))
			for i, item := range arr {
				if obj, ok := item.(map[string]interface{}); ok {
					ref, err := DeclaredStageFromMap(obj)
					if err != nil {
						return nil, fmt.Errorf("field stages[%d]: %w", i, err)
					}
					if ref != nil {
						s.Stages = append(s.Stages, *ref)
					}
				} else {
					return nil, fmt.Errorf("field stages[%d]: expected object, got %T", i, item)
				}
			}
		} else {
			return nil, fmt.Errorf("field stages: expected []object, got %T", v)
		}
	}
	return s, nil
}

// ToMap converts a DeclaredRepo to a map[string]interface{}.
func (s *DeclaredRepo) ToMap() map[string]interface{} {
	if s == nil {
		return nil
	}

	m := make(map[string]interface{})
	if s.Name != "" {
		m["name"] = s.Name
	}
	return m
}

// ToMap converts a Spec to a map[string]interface{}.
func (s *Spec) ToMap() map[string]interface{} {
	if s == nil {
		return nil
	}

	m := make(map[string]interface{})
	return m
}

// ToMap converts a DeclaredSubstage to a map[string]interface{}.
func (s *DeclaredSubstage) ToMap() map[string]interface{} {
	if s == nil {
		return nil
	}

	m := make(map[string]interface{})
	if s.DisplayName != "" {
		m["displayName"] = s.DisplayName
	}
	if s.Name != "" {
		m["name"] = s.Name
	}
	if len(s.Needs) > 0 {
		m["needs"] = s.Needs
	}
	if len(s.Uses) > 0 {
		m["uses"] = s.Uses
	}
	return m
}

// ToMap converts a Revision to a map[string]interface{}.
func (s *Revision) ToMap() map[string]interface{} {
	if s == nil {
		return nil
	}

	m := make(map[string]interface{})
	if s.CreatedAt != "" {
		m["createdAt"] = s.CreatedAt
	}
	if len(s.Dirty) > 0 {
		m["dirty"] = s.Dirty
	}
	if s.Id != "" {
		m["id"] = s.Id
	}
	if len(s.Repos) > 0 {
		m["repos"] = s.Repos
	}
	return m
}

// ToMap converts a StateGetOutput to a map[string]interface{}.
func (s *StateGetOutput) ToMap() map[string]interface{} {
	if s == nil {
		return nil
	}

	m := make(map[string]interface{})
	if s.Found {
		m["found"] = s.Found
	}
	if s.Payload != "" {
		m["payload"] = s.Payload
	}
	return m
}

// ToMap converts a StateListOutput to a map[string]interface{}.
func (s *StateListOutput) ToMap() map[string]interface{} {
	if s == nil {
		return nil
	}

	m := make(map[string]interface{})
	if len(s.Keys) > 0 {
		m["keys"] = s.Keys
	}
	return m
}

// ToMap converts a Resource to a map[string]interface{}.
func (s *Resource) ToMap() map[string]interface{} {
	if s == nil {
		return nil
	}

	m := make(map[string]interface{})
	if s.Kind != "" {
		m["kind"] = s.Kind
	}
	if s.Name != "" {
		m["name"] = s.Name
	}
	// Reference type Spec
	if refMap := s.Spec.ToMap(); len(refMap) > 0 {
		m["spec"] = refMap
	}
	return m
}

// ToMap converts a StateGetInput to a map[string]interface{}.
func (s *StateGetInput) ToMap() map[string]interface{} {
	if s == nil {
		return nil
	}

	m := make(map[string]interface{})
	if s.Key != "" {
		m["key"] = s.Key
	}
	if s.Kind != "" {
		m["kind"] = s.Kind
	}
	// Reference type Spec
	if refMap := s.Spec.ToMap(); len(refMap) > 0 {
		m["spec"] = refMap
	}
	return m
}

// ToMap converts a StatePutInput to a map[string]interface{}.
func (s *StatePutInput) ToMap() map[string]interface{} {
	if s == nil {
		return nil
	}

	m := make(map[string]interface{})
	if s.Key != "" {
		m["key"] = s.Key
	}
	if s.Kind != "" {
		m["kind"] = s.Kind
	}
	if s.Payload != "" {
		m["payload"] = s.Payload
	}
	// Reference type Spec
	if refMap := s.Spec.ToMap(); len(refMap) > 0 {
		m["spec"] = refMap
	}
	return m
}

// ToMap converts a DeclaredStage to a map[string]interface{}.
func (s *DeclaredStage) ToMap() map[string]interface{} {
	if s == nil {
		return nil
	}

	m := make(map[string]interface{})
	if s.DisplayName != "" {
		m["displayName"] = s.DisplayName
	}
	if s.Name != "" {
		m["name"] = s.Name
	}
	if len(s.Substages) > 0 {
		arr := make([]interface{}, 0, len(s.Substages))
		for _, item := range s.Substages {
			arr = append(arr, item.ToMap())
		}
		m["substages"] = arr
	}
	return m
}

// ToMap converts a DeclareOutput to a map[string]interface{}.
func (s *DeclareOutput) ToMap() map[string]interface{} {
	if s == nil {
		return nil
	}

	m := make(map[string]interface{})
	if len(s.Resources) > 0 {
		arr := make([]interface{}, 0, len(s.Resources))
		for _, item := range s.Resources {
			arr = append(arr, item.ToMap())
		}
		m["resources"] = arr
	}
	return m
}

// ToMap converts a DeclareInput to a map[string]interface{}.
func (s *DeclareInput) ToMap() map[string]interface{} {
	if s == nil {
		return nil
	}

	m := make(map[string]interface{})
	if len(s.Repos) > 0 {
		arr := make([]interface{}, 0, len(s.Repos))
		for _, item := range s.Repos {
			arr = append(arr, item.ToMap())
		}
		m["repos"] = arr
	}
	if s.Root != "" {
		m["root"] = s.Root
	}
	// Reference type Spec
	if refMap := s.Spec.ToMap(); len(refMap) > 0 {
		m["spec"] = refMap
	}
	if len(s.Stages) > 0 {
		arr := make([]interface{}, 0, len(s.Stages))
		for _, item := range s.Stages {
			arr = append(arr, item.ToMap())
		}
		m["stages"] = arr
	}
	return m
}

// FromMap creates a Spec from a map[string]interface{}.
// This is the main entry point for parsing the spec field from forge.yaml.
func FromMap(m map[string]interface{}) (*Spec, error) {
	return SpecFromMap(m)
}
