// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package gitadaptermock

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockGit creates a new instance of MockGit. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGit(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGit {
	mock := &MockGit{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockGit is an autogenerated mock type for the Git type
type MockGit struct {
	mock.Mock
}

type MockGit_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGit) EXPECT() *MockGit_Expecter {
	return &MockGit_Expecter{mock: &_m.Mock}
}

// Add provides a mock function for the type MockGit
func (_mock *MockGit) Add(ctx context.Context, dir string, path string) error {
	ret := _mock.Called(ctx, dir, path)

	if len(ret) == 0 {
		panic("no return value specified for Add")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, dir, path)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockGit_Add_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Add'
type MockGit_Add_Call struct {
	*mock.Call
}

// Add is a helper method to define mock.On call
//   - ctx context.Context
//   - dir string
//   - path string
func (_e *MockGit_Expecter) Add(ctx any, dir any, path any) *MockGit_Add_Call {
	return &MockGit_Add_Call{Call: _e.mock.On("Add", ctx, dir, path)}
}

func (_c *MockGit_Add_Call) Run(run func(ctx context.Context, dir string, path string)) *MockGit_Add_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockGit_Add_Call) Return(err error) *MockGit_Add_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockGit_Add_Call) RunAndReturn(run func(ctx context.Context, dir string, path string) error) *MockGit_Add_Call {
	_c.Call.Return(run)
	return _c
}

// Clone provides a mock function for the type MockGit
func (_mock *MockGit) Clone(ctx context.Context, url string, dir string) error {
	ret := _mock.Called(ctx, url, dir)

	if len(ret) == 0 {
		panic("no return value specified for Clone")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, url, dir)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockGit_Clone_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Clone'
type MockGit_Clone_Call struct {
	*mock.Call
}

// Clone is a helper method to define mock.On call
//   - ctx context.Context
//   - url string
//   - dir string
func (_e *MockGit_Expecter) Clone(ctx any, url any, dir any) *MockGit_Clone_Call {
	return &MockGit_Clone_Call{Call: _e.mock.On("Clone", ctx, url, dir)}
}

func (_c *MockGit_Clone_Call) Run(run func(ctx context.Context, url string, dir string)) *MockGit_Clone_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockGit_Clone_Call) Return(err error) *MockGit_Clone_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockGit_Clone_Call) RunAndReturn(run func(ctx context.Context, url string, dir string) error) *MockGit_Clone_Call {
	_c.Call.Return(run)
	return _c
}

// Commit provides a mock function for the type MockGit
func (_mock *MockGit) Commit(ctx context.Context, dir string, message string) error {
	ret := _mock.Called(ctx, dir, message)

	if len(ret) == 0 {
		panic("no return value specified for Commit")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, dir, message)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockGit_Commit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Commit'
type MockGit_Commit_Call struct {
	*mock.Call
}

// Commit is a helper method to define mock.On call
//   - ctx context.Context
//   - dir string
//   - message string
func (_e *MockGit_Expecter) Commit(ctx any, dir any, message any) *MockGit_Commit_Call {
	return &MockGit_Commit_Call{Call: _e.mock.On("Commit", ctx, dir, message)}
}

func (_c *MockGit_Commit_Call) Run(run func(ctx context.Context, dir string, message string)) *MockGit_Commit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockGit_Commit_Call) Return(err error) *MockGit_Commit_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockGit_Commit_Call) RunAndReturn(run func(ctx context.Context, dir string, message string) error) *MockGit_Commit_Call {
	_c.Call.Return(run)
	return _c
}

// HeadSHA provides a mock function for the type MockGit
func (_mock *MockGit) HeadSHA(ctx context.Context, dir string) (string, error) {
	ret := _mock.Called(ctx, dir)

	if len(ret) == 0 {
		panic("no return value specified for HeadSHA")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return returnFunc(ctx, dir)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = returnFunc(ctx, dir)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, dir)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGit_HeadSHA_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HeadSHA'
type MockGit_HeadSHA_Call struct {
	*mock.Call
}

// HeadSHA is a helper method to define mock.On call
//   - ctx context.Context
//   - dir string
func (_e *MockGit_Expecter) HeadSHA(ctx any, dir any) *MockGit_HeadSHA_Call {
	return &MockGit_HeadSHA_Call{Call: _e.mock.On("HeadSHA", ctx, dir)}
}

func (_c *MockGit_HeadSHA_Call) Run(run func(ctx context.Context, dir string)) *MockGit_HeadSHA_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGit_HeadSHA_Call) Return(s string, err error) *MockGit_HeadSHA_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockGit_HeadSHA_Call) RunAndReturn(run func(ctx context.Context, dir string) (string, error)) *MockGit_HeadSHA_Call {
	_c.Call.Return(run)
	return _c
}

// Init provides a mock function for the type MockGit
func (_mock *MockGit) Init(ctx context.Context, dir string) error {
	ret := _mock.Called(ctx, dir)

	if len(ret) == 0 {
		panic("no return value specified for Init")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, dir)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockGit_Init_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Init'
type MockGit_Init_Call struct {
	*mock.Call
}

// Init is a helper method to define mock.On call
//   - ctx context.Context
//   - dir string
func (_e *MockGit_Expecter) Init(ctx any, dir any) *MockGit_Init_Call {
	return &MockGit_Init_Call{Call: _e.mock.On("Init", ctx, dir)}
}

func (_c *MockGit_Init_Call) Run(run func(ctx context.Context, dir string)) *MockGit_Init_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGit_Init_Call) Return(err error) *MockGit_Init_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockGit_Init_Call) RunAndReturn(run func(ctx context.Context, dir string) error) *MockGit_Init_Call {
	_c.Call.Return(run)
	return _c
}

// IsRepo provides a mock function for the type MockGit
func (_mock *MockGit) IsRepo(ctx context.Context, dir string) (bool, error) {
	ret := _mock.Called(ctx, dir)

	if len(ret) == 0 {
		panic("no return value specified for IsRepo")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return returnFunc(ctx, dir)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = returnFunc(ctx, dir)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, dir)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGit_IsRepo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsRepo'
type MockGit_IsRepo_Call struct {
	*mock.Call
}

// IsRepo is a helper method to define mock.On call
//   - ctx context.Context
//   - dir string
func (_e *MockGit_Expecter) IsRepo(ctx any, dir any) *MockGit_IsRepo_Call {
	return &MockGit_IsRepo_Call{Call: _e.mock.On("IsRepo", ctx, dir)}
}

func (_c *MockGit_IsRepo_Call) Run(run func(ctx context.Context, dir string)) *MockGit_IsRepo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGit_IsRepo_Call) Return(b bool, err error) *MockGit_IsRepo_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockGit_IsRepo_Call) RunAndReturn(run func(ctx context.Context, dir string) (bool, error)) *MockGit_IsRepo_Call {
	_c.Call.Return(run)
	return _c
}

// LatestTag provides a mock function for the type MockGit
func (_mock *MockGit) LatestTag(ctx context.Context, dir string, prefix string) (string, error) {
	ret := _mock.Called(ctx, dir, prefix)

	if len(ret) == 0 {
		panic("no return value specified for LatestTag")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (string, error)); ok {
		return returnFunc(ctx, dir, prefix)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) string); ok {
		r0 = returnFunc(ctx, dir, prefix)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, dir, prefix)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGit_LatestTag_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LatestTag'
type MockGit_LatestTag_Call struct {
	*mock.Call
}

// LatestTag is a helper method to define mock.On call
//   - ctx context.Context
//   - dir string
//   - prefix string
func (_e *MockGit_Expecter) LatestTag(ctx any, dir any, prefix any) *MockGit_LatestTag_Call {
	return &MockGit_LatestTag_Call{Call: _e.mock.On("LatestTag", ctx, dir, prefix)}
}

func (_c *MockGit_LatestTag_Call) Run(run func(ctx context.Context, dir string, prefix string)) *MockGit_LatestTag_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockGit_LatestTag_Call) Return(s string, err error) *MockGit_LatestTag_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockGit_LatestTag_Call) RunAndReturn(run func(ctx context.Context, dir string, prefix string) (string, error)) *MockGit_LatestTag_Call {
	_c.Call.Return(run)
	return _c
}

// RemoteSHA provides a mock function for the type MockGit
func (_mock *MockGit) RemoteSHA(ctx context.Context, url string, ref string) (string, error) {
	ret := _mock.Called(ctx, url, ref)

	if len(ret) == 0 {
		panic("no return value specified for RemoteSHA")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (string, error)); ok {
		return returnFunc(ctx, url, ref)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) string); ok {
		r0 = returnFunc(ctx, url, ref)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, url, ref)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGit_RemoteSHA_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoteSHA'
type MockGit_RemoteSHA_Call struct {
	*mock.Call
}

// RemoteSHA is a helper method to define mock.On call
//   - ctx context.Context
//   - url string
//   - ref string
func (_e *MockGit_Expecter) RemoteSHA(ctx any, url any, ref any) *MockGit_RemoteSHA_Call {
	return &MockGit_RemoteSHA_Call{Call: _e.mock.On("RemoteSHA", ctx, url, ref)}
}

func (_c *MockGit_RemoteSHA_Call) Run(run func(ctx context.Context, url string, ref string)) *MockGit_RemoteSHA_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockGit_RemoteSHA_Call) Return(s string, err error) *MockGit_RemoteSHA_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockGit_RemoteSHA_Call) RunAndReturn(run func(ctx context.Context, url string, ref string) (string, error)) *MockGit_RemoteSHA_Call {
	_c.Call.Return(run)
	return _c
}

// Staged provides a mock function for the type MockGit
func (_mock *MockGit) Staged(ctx context.Context, dir string) (bool, error) {
	ret := _mock.Called(ctx, dir)

	if len(ret) == 0 {
		panic("no return value specified for Staged")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return returnFunc(ctx, dir)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = returnFunc(ctx, dir)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, dir)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGit_Staged_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Staged'
type MockGit_Staged_Call struct {
	*mock.Call
}

// Staged is a helper method to define mock.On call
//   - ctx context.Context
//   - dir string
func (_e *MockGit_Expecter) Staged(ctx any, dir any) *MockGit_Staged_Call {
	return &MockGit_Staged_Call{Call: _e.mock.On("Staged", ctx, dir)}
}

func (_c *MockGit_Staged_Call) Run(run func(ctx context.Context, dir string)) *MockGit_Staged_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGit_Staged_Call) Return(b bool, err error) *MockGit_Staged_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockGit_Staged_Call) RunAndReturn(run func(ctx context.Context, dir string) (bool, error)) *MockGit_Staged_Call {
	_c.Call.Return(run)
	return _c
}

// SubjectsSince provides a mock function for the type MockGit
func (_mock *MockGit) SubjectsSince(ctx context.Context, dir string, tag string) ([]string, error) {
	ret := _mock.Called(ctx, dir, tag)

	if len(ret) == 0 {
		panic("no return value specified for SubjectsSince")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) ([]string, error)); ok {
		return returnFunc(ctx, dir, tag)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) []string); ok {
		r0 = returnFunc(ctx, dir, tag)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, dir, tag)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGit_SubjectsSince_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SubjectsSince'
type MockGit_SubjectsSince_Call struct {
	*mock.Call
}

// SubjectsSince is a helper method to define mock.On call
//   - ctx context.Context
//   - dir string
//   - tag string
func (_e *MockGit_Expecter) SubjectsSince(ctx any, dir any, tag any) *MockGit_SubjectsSince_Call {
	return &MockGit_SubjectsSince_Call{Call: _e.mock.On("SubjectsSince", ctx, dir, tag)}
}

func (_c *MockGit_SubjectsSince_Call) Run(run func(ctx context.Context, dir string, tag string)) *MockGit_SubjectsSince_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockGit_SubjectsSince_Call) Return(strings []string, err error) *MockGit_SubjectsSince_Call {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *MockGit_SubjectsSince_Call) RunAndReturn(run func(ctx context.Context, dir string, tag string) ([]string, error)) *MockGit_SubjectsSince_Call {
	_c.Call.Return(run)
	return _c
}

// WorktreeHash provides a mock function for the type MockGit
func (_mock *MockGit) WorktreeHash(ctx context.Context, dir string) (string, error) {
	ret := _mock.Called(ctx, dir)

	if len(ret) == 0 {
		panic("no return value specified for WorktreeHash")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return returnFunc(ctx, dir)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = returnFunc(ctx, dir)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, dir)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGit_WorktreeHash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WorktreeHash'
type MockGit_WorktreeHash_Call struct {
	*mock.Call
}

// WorktreeHash is a helper method to define mock.On call
//   - ctx context.Context
//   - dir string
func (_e *MockGit_Expecter) WorktreeHash(ctx any, dir any) *MockGit_WorktreeHash_Call {
	return &MockGit_WorktreeHash_Call{Call: _e.mock.On("WorktreeHash", ctx, dir)}
}

func (_c *MockGit_WorktreeHash_Call) Run(run func(ctx context.Context, dir string)) *MockGit_WorktreeHash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGit_WorktreeHash_Call) Return(s string, err error) *MockGit_WorktreeHash_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockGit_WorktreeHash_Call) RunAndReturn(run func(ctx context.Context, dir string) (string, error)) *MockGit_WorktreeHash_Call {
	_c.Call.Return(run)
	return _c
}
