// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package gitadaptermock

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockGit creates a new instance of MockGit. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGit(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGit {
	mock := &MockGit{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockGit is an autogenerated mock type for the Git type
type MockGit struct {
	mock.Mock
}

type MockGit_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGit) EXPECT() *MockGit_Expecter {
	return &MockGit_Expecter{mock: &_m.Mock}
}

// Add provides a mock function for the type MockGit
func (_mock *MockGit) Add(ctx context.Context, dir string, path string) error {
	ret := _mock.Called(ctx, dir, path)

	if len(ret) == 0 {
		panic("no return value specified for Add")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, dir, path)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockGit_Add_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Add'
type MockGit_Add_Call struct {
	*mock.Call
}

// Add is a helper method to define mock.On call
//   - ctx context.Context
//   - dir string
//   - path string
func (_e *MockGit_Expecter) Add(ctx any, dir any, path any) *MockGit_Add_Call {
	return &MockGit_Add_Call{Call: _e.mock.On("Add", ctx, dir, path)}
}

func (_c *MockGit_Add_Call) Run(run func(ctx context.Context, dir string, path string)) *MockGit_Add_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockGit_Add_Call) Return(err error) *MockGit_Add_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockGit_Add_Call) RunAndReturn(run func(ctx context.Context, dir string, path string) error) *MockGit_Add_Call {
	_c.Call.Return(run)
	return _c
}

// Branch provides a mock function for the type MockGit
func (_mock *MockGit) Branch(ctx context.Context, dir string) (string, error) {
	ret := _mock.Called(ctx, dir)

	if len(ret) == 0 {
		panic("no return value specified for Branch")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return returnFunc(ctx, dir)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = returnFunc(ctx, dir)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, dir)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGit_Branch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Branch'
type MockGit_Branch_Call struct {
	*mock.Call
}

// Branch is a helper method to define mock.On call
//   - ctx context.Context
//   - dir string
func (_e *MockGit_Expecter) Branch(ctx any, dir any) *MockGit_Branch_Call {
	return &MockGit_Branch_Call{Call: _e.mock.On("Branch", ctx, dir)}
}

func (_c *MockGit_Branch_Call) Run(run func(ctx context.Context, dir string)) *MockGit_Branch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGit_Branch_Call) Return(s string, err error) *MockGit_Branch_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockGit_Branch_Call) RunAndReturn(run func(ctx context.Context, dir string) (string, error)) *MockGit_Branch_Call {
	_c.Call.Return(run)
	return _c
}

// Clone provides a mock function for the type MockGit
func (_mock *MockGit) Clone(ctx context.Context, url string, dir string) error {
	ret := _mock.Called(ctx, url, dir)

	if len(ret) == 0 {
		panic("no return value specified for Clone")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, url, dir)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockGit_Clone_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Clone'
type MockGit_Clone_Call struct {
	*mock.Call
}

// Clone is a helper method to define mock.On call
//   - ctx context.Context
//   - url string
//   - dir string
func (_e *MockGit_Expecter) Clone(ctx any, url any, dir any) *MockGit_Clone_Call {
	return &MockGit_Clone_Call{Call: _e.mock.On("Clone", ctx, url, dir)}
}

func (_c *MockGit_Clone_Call) Run(run func(ctx context.Context, url string, dir string)) *MockGit_Clone_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockGit_Clone_Call) Return(err error) *MockGit_Clone_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockGit_Clone_Call) RunAndReturn(run func(ctx context.Context, url string, dir string) error) *MockGit_Clone_Call {
	_c.Call.Return(run)
	return _c
}

// Commit provides a mock function for the type MockGit
func (_mock *MockGit) Commit(ctx context.Context, dir string, message string, paths ...string) error {
	// string
	_va := make([]any, len(paths))
	for _i := range paths {
		_va[_i] = paths[_i]
	}
	var _ca []any
	_ca = append(_ca, ctx, dir, message)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Commit")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, ...string) error); ok {
		r0 = returnFunc(ctx, dir, message, paths...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockGit_Commit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Commit'
type MockGit_Commit_Call struct {
	*mock.Call
}

// Commit is a helper method to define mock.On call
//   - ctx context.Context
//   - dir string
//   - message string
//   - paths ...string
func (_e *MockGit_Expecter) Commit(ctx any, dir any, message any, paths ...any) *MockGit_Commit_Call {
	return &MockGit_Commit_Call{Call: _e.mock.On("Commit",
		append([]any{ctx, dir, message}, paths...)...)}
}

func (_c *MockGit_Commit_Call) Run(run func(ctx context.Context, dir string, message string, paths ...string)) *MockGit_Commit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 []string
		variadicArgs := make([]string, len(args)-3)
		for i, a := range args[3:] {
			if a != nil {
				variadicArgs[i] = a.(string)
			}
		}
		arg3 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3...,
		)
	})
	return _c
}

func (_c *MockGit_Commit_Call) Return(err error) *MockGit_Commit_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockGit_Commit_Call) RunAndReturn(run func(ctx context.Context, dir string, message string, paths ...string) error) *MockGit_Commit_Call {
	_c.Call.Return(run)
	return _c
}

// HasRemote provides a mock function for the type MockGit
func (_mock *MockGit) HasRemote(ctx context.Context, dir string) (bool, error) {
	ret := _mock.Called(ctx, dir)

	if len(ret) == 0 {
		panic("no return value specified for HasRemote")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return returnFunc(ctx, dir)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = returnFunc(ctx, dir)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, dir)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGit_HasRemote_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HasRemote'
type MockGit_HasRemote_Call struct {
	*mock.Call
}

// HasRemote is a helper method to define mock.On call
//   - ctx context.Context
//   - dir string
func (_e *MockGit_Expecter) HasRemote(ctx any, dir any) *MockGit_HasRemote_Call {
	return &MockGit_HasRemote_Call{Call: _e.mock.On("HasRemote", ctx, dir)}
}

func (_c *MockGit_HasRemote_Call) Run(run func(ctx context.Context, dir string)) *MockGit_HasRemote_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGit_HasRemote_Call) Return(b bool, err error) *MockGit_HasRemote_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockGit_HasRemote_Call) RunAndReturn(run func(ctx context.Context, dir string) (bool, error)) *MockGit_HasRemote_Call {
	_c.Call.Return(run)
	return _c
}

// HeadSHA provides a mock function for the type MockGit
func (_mock *MockGit) HeadSHA(ctx context.Context, dir string) (string, error) {
	ret := _mock.Called(ctx, dir)

	if len(ret) == 0 {
		panic("no return value specified for HeadSHA")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return returnFunc(ctx, dir)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = returnFunc(ctx, dir)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, dir)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGit_HeadSHA_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HeadSHA'
type MockGit_HeadSHA_Call struct {
	*mock.Call
}

// HeadSHA is a helper method to define mock.On call
//   - ctx context.Context
//   - dir string
func (_e *MockGit_Expecter) HeadSHA(ctx any, dir any) *MockGit_HeadSHA_Call {
	return &MockGit_HeadSHA_Call{Call: _e.mock.On("HeadSHA", ctx, dir)}
}

func (_c *MockGit_HeadSHA_Call) Run(run func(ctx context.Context, dir string)) *MockGit_HeadSHA_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGit_HeadSHA_Call) Return(s string, err error) *MockGit_HeadSHA_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockGit_HeadSHA_Call) RunAndReturn(run func(ctx context.Context, dir string) (string, error)) *MockGit_HeadSHA_Call {
	_c.Call.Return(run)
	return _c
}

// Init provides a mock function for the type MockGit
func (_mock *MockGit) Init(ctx context.Context, dir string) error {
	ret := _mock.Called(ctx, dir)

	if len(ret) == 0 {
		panic("no return value specified for Init")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, dir)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockGit_Init_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Init'
type MockGit_Init_Call struct {
	*mock.Call
}

// Init is a helper method to define mock.On call
//   - ctx context.Context
//   - dir string
func (_e *MockGit_Expecter) Init(ctx any, dir any) *MockGit_Init_Call {
	return &MockGit_Init_Call{Call: _e.mock.On("Init", ctx, dir)}
}

func (_c *MockGit_Init_Call) Run(run func(ctx context.Context, dir string)) *MockGit_Init_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGit_Init_Call) Return(err error) *MockGit_Init_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockGit_Init_Call) RunAndReturn(run func(ctx context.Context, dir string) error) *MockGit_Init_Call {
	_c.Call.Return(run)
	return _c
}

// IsRepo provides a mock function for the type MockGit
func (_mock *MockGit) IsRepo(ctx context.Context, dir string) (bool, error) {
	ret := _mock.Called(ctx, dir)

	if len(ret) == 0 {
		panic("no return value specified for IsRepo")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return returnFunc(ctx, dir)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = returnFunc(ctx, dir)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, dir)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGit_IsRepo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsRepo'
type MockGit_IsRepo_Call struct {
	*mock.Call
}

// IsRepo is a helper method to define mock.On call
//   - ctx context.Context
//   - dir string
func (_e *MockGit_Expecter) IsRepo(ctx any, dir any) *MockGit_IsRepo_Call {
	return &MockGit_IsRepo_Call{Call: _e.mock.On("IsRepo", ctx, dir)}
}

func (_c *MockGit_IsRepo_Call) Run(run func(ctx context.Context, dir string)) *MockGit_IsRepo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGit_IsRepo_Call) Return(b bool, err error) *MockGit_IsRepo_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockGit_IsRepo_Call) RunAndReturn(run func(ctx context.Context, dir string) (bool, error)) *MockGit_IsRepo_Call {
	_c.Call.Return(run)
	return _c
}

// LFSInstall provides a mock function for the type MockGit
func (_mock *MockGit) LFSInstall(ctx context.Context, dir string) error {
	ret := _mock.Called(ctx, dir)

	if len(ret) == 0 {
		panic("no return value specified for LFSInstall")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, dir)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockGit_LFSInstall_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LFSInstall'
type MockGit_LFSInstall_Call struct {
	*mock.Call
}

// LFSInstall is a helper method to define mock.On call
//   - ctx context.Context
//   - dir string
func (_e *MockGit_Expecter) LFSInstall(ctx any, dir any) *MockGit_LFSInstall_Call {
	return &MockGit_LFSInstall_Call{Call: _e.mock.On("LFSInstall", ctx, dir)}
}

func (_c *MockGit_LFSInstall_Call) Run(run func(ctx context.Context, dir string)) *MockGit_LFSInstall_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGit_LFSInstall_Call) Return(err error) *MockGit_LFSInstall_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockGit_LFSInstall_Call) RunAndReturn(run func(ctx context.Context, dir string) error) *MockGit_LFSInstall_Call {
	_c.Call.Return(run)
	return _c
}

// LatestTag provides a mock function for the type MockGit
func (_mock *MockGit) LatestTag(ctx context.Context, dir string, prefix string) (string, error) {
	ret := _mock.Called(ctx, dir, prefix)

	if len(ret) == 0 {
		panic("no return value specified for LatestTag")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (string, error)); ok {
		return returnFunc(ctx, dir, prefix)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) string); ok {
		r0 = returnFunc(ctx, dir, prefix)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, dir, prefix)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGit_LatestTag_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LatestTag'
type MockGit_LatestTag_Call struct {
	*mock.Call
}

// LatestTag is a helper method to define mock.On call
//   - ctx context.Context
//   - dir string
//   - prefix string
func (_e *MockGit_Expecter) LatestTag(ctx any, dir any, prefix any) *MockGit_LatestTag_Call {
	return &MockGit_LatestTag_Call{Call: _e.mock.On("LatestTag", ctx, dir, prefix)}
}

func (_c *MockGit_LatestTag_Call) Run(run func(ctx context.Context, dir string, prefix string)) *MockGit_LatestTag_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockGit_LatestTag_Call) Return(s string, err error) *MockGit_LatestTag_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockGit_LatestTag_Call) RunAndReturn(run func(ctx context.Context, dir string, prefix string) (string, error)) *MockGit_LatestTag_Call {
	_c.Call.Return(run)
	return _c
}

// PullRebase provides a mock function for the type MockGit
func (_mock *MockGit) PullRebase(ctx context.Context, dir string, branch string) error {
	ret := _mock.Called(ctx, dir, branch)

	if len(ret) == 0 {
		panic("no return value specified for PullRebase")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, dir, branch)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockGit_PullRebase_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PullRebase'
type MockGit_PullRebase_Call struct {
	*mock.Call
}

// PullRebase is a helper method to define mock.On call
//   - ctx context.Context
//   - dir string
//   - branch string
func (_e *MockGit_Expecter) PullRebase(ctx any, dir any, branch any) *MockGit_PullRebase_Call {
	return &MockGit_PullRebase_Call{Call: _e.mock.On("PullRebase", ctx, dir, branch)}
}

func (_c *MockGit_PullRebase_Call) Run(run func(ctx context.Context, dir string, branch string)) *MockGit_PullRebase_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockGit_PullRebase_Call) Return(err error) *MockGit_PullRebase_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockGit_PullRebase_Call) RunAndReturn(run func(ctx context.Context, dir string, branch string) error) *MockGit_PullRebase_Call {
	_c.Call.Return(run)
	return _c
}

// Push provides a mock function for the type MockGit
func (_mock *MockGit) Push(ctx context.Context, dir string, branch string) error {
	ret := _mock.Called(ctx, dir, branch)

	if len(ret) == 0 {
		panic("no return value specified for Push")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, dir, branch)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockGit_Push_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Push'
type MockGit_Push_Call struct {
	*mock.Call
}

// Push is a helper method to define mock.On call
//   - ctx context.Context
//   - dir string
//   - branch string
func (_e *MockGit_Expecter) Push(ctx any, dir any, branch any) *MockGit_Push_Call {
	return &MockGit_Push_Call{Call: _e.mock.On("Push", ctx, dir, branch)}
}

func (_c *MockGit_Push_Call) Run(run func(ctx context.Context, dir string, branch string)) *MockGit_Push_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockGit_Push_Call) Return(err error) *MockGit_Push_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockGit_Push_Call) RunAndReturn(run func(ctx context.Context, dir string, branch string) error) *MockGit_Push_Call {
	_c.Call.Return(run)
	return _c
}

// RemoteSHA provides a mock function for the type MockGit
func (_mock *MockGit) RemoteSHA(ctx context.Context, url string, ref string) (string, error) {
	ret := _mock.Called(ctx, url, ref)

	if len(ret) == 0 {
		panic("no return value specified for RemoteSHA")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (string, error)); ok {
		return returnFunc(ctx, url, ref)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) string); ok {
		r0 = returnFunc(ctx, url, ref)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, url, ref)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGit_RemoteSHA_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoteSHA'
type MockGit_RemoteSHA_Call struct {
	*mock.Call
}

// RemoteSHA is a helper method to define mock.On call
//   - ctx context.Context
//   - url string
//   - ref string
func (_e *MockGit_Expecter) RemoteSHA(ctx any, url any, ref any) *MockGit_RemoteSHA_Call {
	return &MockGit_RemoteSHA_Call{Call: _e.mock.On("RemoteSHA", ctx, url, ref)}
}

func (_c *MockGit_RemoteSHA_Call) Run(run func(ctx context.Context, url string, ref string)) *MockGit_RemoteSHA_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockGit_RemoteSHA_Call) Return(s string, err error) *MockGit_RemoteSHA_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockGit_RemoteSHA_Call) RunAndReturn(run func(ctx context.Context, url string, ref string) (string, error)) *MockGit_RemoteSHA_Call {
	_c.Call.Return(run)
	return _c
}

// RemoteTagAt provides a mock function for the type MockGit
func (_mock *MockGit) RemoteTagAt(ctx context.Context, dir string, tag string) (string, bool, error) {
	ret := _mock.Called(ctx, dir, tag)

	if len(ret) == 0 {
		panic("no return value specified for RemoteTagAt")
	}

	var r0 string
	var r1 bool
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (string, bool, error)); ok {
		return returnFunc(ctx, dir, tag)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) string); ok {
		r0 = returnFunc(ctx, dir, tag)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) bool); ok {
		r1 = returnFunc(ctx, dir, tag)
	} else {
		r1 = ret.Get(1).(bool)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string, string) error); ok {
		r2 = returnFunc(ctx, dir, tag)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockGit_RemoteTagAt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoteTagAt'
type MockGit_RemoteTagAt_Call struct {
	*mock.Call
}

// RemoteTagAt is a helper method to define mock.On call
//   - ctx context.Context
//   - dir string
//   - tag string
func (_e *MockGit_Expecter) RemoteTagAt(ctx any, dir any, tag any) *MockGit_RemoteTagAt_Call {
	return &MockGit_RemoteTagAt_Call{Call: _e.mock.On("RemoteTagAt", ctx, dir, tag)}
}

func (_c *MockGit_RemoteTagAt_Call) Run(run func(ctx context.Context, dir string, tag string)) *MockGit_RemoteTagAt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockGit_RemoteTagAt_Call) Return(s string, b bool, err error) *MockGit_RemoteTagAt_Call {
	_c.Call.Return(s, b, err)
	return _c
}

func (_c *MockGit_RemoteTagAt_Call) RunAndReturn(run func(ctx context.Context, dir string, tag string) (string, bool, error)) *MockGit_RemoteTagAt_Call {
	_c.Call.Return(run)
	return _c
}

// Staged provides a mock function for the type MockGit
func (_mock *MockGit) Staged(ctx context.Context, dir string, paths ...string) (bool, error) {
	// string
	_va := make([]any, len(paths))
	for _i := range paths {
		_va[_i] = paths[_i]
	}
	var _ca []any
	_ca = append(_ca, ctx, dir)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Staged")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...string) (bool, error)); ok {
		return returnFunc(ctx, dir, paths...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...string) bool); ok {
		r0 = returnFunc(ctx, dir, paths...)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, ...string) error); ok {
		r1 = returnFunc(ctx, dir, paths...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGit_Staged_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Staged'
type MockGit_Staged_Call struct {
	*mock.Call
}

// Staged is a helper method to define mock.On call
//   - ctx context.Context
//   - dir string
//   - paths ...string
func (_e *MockGit_Expecter) Staged(ctx any, dir any, paths ...any) *MockGit_Staged_Call {
	return &MockGit_Staged_Call{Call: _e.mock.On("Staged",
		append([]any{ctx, dir}, paths...)...)}
}

func (_c *MockGit_Staged_Call) Run(run func(ctx context.Context, dir string, paths ...string)) *MockGit_Staged_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []string
		variadicArgs := make([]string, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(string)
			}
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockGit_Staged_Call) Return(b bool, err error) *MockGit_Staged_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockGit_Staged_Call) RunAndReturn(run func(ctx context.Context, dir string, paths ...string) (bool, error)) *MockGit_Staged_Call {
	_c.Call.Return(run)
	return _c
}

// SubjectsSince provides a mock function for the type MockGit
func (_mock *MockGit) SubjectsSince(ctx context.Context, dir string, tag string) ([]string, error) {
	ret := _mock.Called(ctx, dir, tag)

	if len(ret) == 0 {
		panic("no return value specified for SubjectsSince")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) ([]string, error)); ok {
		return returnFunc(ctx, dir, tag)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) []string); ok {
		r0 = returnFunc(ctx, dir, tag)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, dir, tag)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGit_SubjectsSince_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SubjectsSince'
type MockGit_SubjectsSince_Call struct {
	*mock.Call
}

// SubjectsSince is a helper method to define mock.On call
//   - ctx context.Context
//   - dir string
//   - tag string
func (_e *MockGit_Expecter) SubjectsSince(ctx any, dir any, tag any) *MockGit_SubjectsSince_Call {
	return &MockGit_SubjectsSince_Call{Call: _e.mock.On("SubjectsSince", ctx, dir, tag)}
}

func (_c *MockGit_SubjectsSince_Call) Run(run func(ctx context.Context, dir string, tag string)) *MockGit_SubjectsSince_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockGit_SubjectsSince_Call) Return(strings []string, err error) *MockGit_SubjectsSince_Call {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *MockGit_SubjectsSince_Call) RunAndReturn(run func(ctx context.Context, dir string, tag string) ([]string, error)) *MockGit_SubjectsSince_Call {
	_c.Call.Return(run)
	return _c
}

// Tag provides a mock function for the type MockGit
func (_mock *MockGit) Tag(ctx context.Context, dir string, tag string, sha string) error {
	ret := _mock.Called(ctx, dir, tag, sha)

	if len(ret) == 0 {
		panic("no return value specified for Tag")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = returnFunc(ctx, dir, tag, sha)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockGit_Tag_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Tag'
type MockGit_Tag_Call struct {
	*mock.Call
}

// Tag is a helper method to define mock.On call
//   - ctx context.Context
//   - dir string
//   - tag string
//   - sha string
func (_e *MockGit_Expecter) Tag(ctx any, dir any, tag any, sha any) *MockGit_Tag_Call {
	return &MockGit_Tag_Call{Call: _e.mock.On("Tag", ctx, dir, tag, sha)}
}

func (_c *MockGit_Tag_Call) Run(run func(ctx context.Context, dir string, tag string, sha string)) *MockGit_Tag_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockGit_Tag_Call) Return(err error) *MockGit_Tag_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockGit_Tag_Call) RunAndReturn(run func(ctx context.Context, dir string, tag string, sha string) error) *MockGit_Tag_Call {
	_c.Call.Return(run)
	return _c
}

// TagAt provides a mock function for the type MockGit
func (_mock *MockGit) TagAt(ctx context.Context, dir string, tag string) (string, bool, error) {
	ret := _mock.Called(ctx, dir, tag)

	if len(ret) == 0 {
		panic("no return value specified for TagAt")
	}

	var r0 string
	var r1 bool
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (string, bool, error)); ok {
		return returnFunc(ctx, dir, tag)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) string); ok {
		r0 = returnFunc(ctx, dir, tag)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) bool); ok {
		r1 = returnFunc(ctx, dir, tag)
	} else {
		r1 = ret.Get(1).(bool)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string, string) error); ok {
		r2 = returnFunc(ctx, dir, tag)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockGit_TagAt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TagAt'
type MockGit_TagAt_Call struct {
	*mock.Call
}

// TagAt is a helper method to define mock.On call
//   - ctx context.Context
//   - dir string
//   - tag string
func (_e *MockGit_Expecter) TagAt(ctx any, dir any, tag any) *MockGit_TagAt_Call {
	return &MockGit_TagAt_Call{Call: _e.mock.On("TagAt", ctx, dir, tag)}
}

func (_c *MockGit_TagAt_Call) Run(run func(ctx context.Context, dir string, tag string)) *MockGit_TagAt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockGit_TagAt_Call) Return(s string, b bool, err error) *MockGit_TagAt_Call {
	_c.Call.Return(s, b, err)
	return _c
}

func (_c *MockGit_TagAt_Call) RunAndReturn(run func(ctx context.Context, dir string, tag string) (string, bool, error)) *MockGit_TagAt_Call {
	_c.Call.Return(run)
	return _c
}

// WorktreeHash provides a mock function for the type MockGit
func (_mock *MockGit) WorktreeHash(ctx context.Context, dir string, exclude ...string) (string, error) {
	// string
	_va := make([]any, len(exclude))
	for _i := range exclude {
		_va[_i] = exclude[_i]
	}
	var _ca []any
	_ca = append(_ca, ctx, dir)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for WorktreeHash")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...string) (string, error)); ok {
		return returnFunc(ctx, dir, exclude...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...string) string); ok {
		r0 = returnFunc(ctx, dir, exclude...)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, ...string) error); ok {
		r1 = returnFunc(ctx, dir, exclude...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGit_WorktreeHash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WorktreeHash'
type MockGit_WorktreeHash_Call struct {
	*mock.Call
}

// WorktreeHash is a helper method to define mock.On call
//   - ctx context.Context
//   - dir string
//   - exclude ...string
func (_e *MockGit_Expecter) WorktreeHash(ctx any, dir any, exclude ...any) *MockGit_WorktreeHash_Call {
	return &MockGit_WorktreeHash_Call{Call: _e.mock.On("WorktreeHash",
		append([]any{ctx, dir}, exclude...)...)}
}

func (_c *MockGit_WorktreeHash_Call) Run(run func(ctx context.Context, dir string, exclude ...string)) *MockGit_WorktreeHash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []string
		variadicArgs := make([]string, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(string)
			}
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockGit_WorktreeHash_Call) Return(s string, err error) *MockGit_WorktreeHash_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockGit_WorktreeHash_Call) RunAndReturn(run func(ctx context.Context, dir string, exclude ...string) (string, error)) *MockGit_WorktreeHash_Call {
	_c.Call.Return(run)
	return _c
}
