// Code generated by forge-dev. DO NOT EDIT.
// Source: spec.openapi.yaml
// SourceChecksum: sha256:dbab7ffbf5836cdbb008beced5d7e54b0e4ea2c7a1fcc2b356518b7da8835248

package main

import (
	"context"
	"fmt"

	"github.com/alexandremahdhaoui/forge/pkg/mcpserver"
	"github.com/alexandremahdhaoui/forge/pkg/mcptypes"
	"github.com/alexandremahdhaoui/forge/pkg/mcputil"
	"github.com/modelcontextprotocol/go-sdk/mcp"
)

// DeclareFunc is the handler signature for the declare tool.
// Report the resources this trigger needs.
type DeclareFunc func(
	ctx context.Context,
	input DeclareInput,
) (*DeclareOutput, error)

// PollFunc is the handler signature for the poll tool.
// Fingerprint the watched repos and say whether they moved.
type PollFunc func(
	ctx context.Context,
	input DeclareInput,
) (*TriggerOutput, error)

// Handlers holds one implementation per tool declared in forge-dev.yaml.
// Every field is required. A nil field makes SetupMCPServer return an error
// rather than registering a tool that panics when called.
type Handlers struct {
	// Declare implements the declare tool.
	Declare DeclareFunc
	// Poll implements the poll tool.
	Poll PollFunc
}

// SetupMCPServer creates the MCP server and registers every declared tool plus
// config-validate.
func SetupMCPServer(name string, version string, handlers Handlers) (*mcpserver.Server, error) {
	server := mcpserver.New(name, version)

	if handlers.Declare == nil {
		return nil, fmt.Errorf("Handlers.Declare is required for the %q tool", "declare")
	}

	mcpserver.RegisterTool(server, &mcp.Tool{
		Name:        "declare",
		Description: "Report the resources this trigger needs.",
	}, wrapDeclare(handlers.Declare))

	if handlers.Poll == nil {
		return nil, fmt.Errorf("Handlers.Poll is required for the %q tool", "poll")
	}

	mcpserver.RegisterTool(server, &mcp.Tool{
		Name:        "poll",
		Description: "Fingerprint the watched repos and say whether they moved.",
	}, wrapPoll(handlers.Poll))

	mcpserver.RegisterTool(server, &mcp.Tool{
		Name:        "config-validate",
		Description: fmt.Sprintf("Validate %s engine-specific spec configuration.", name),
	}, handleConfigValidate)

	return server, nil
}

// wrapDeclare adapts DeclareFunc to the MCP tool handler shape.
func wrapDeclare(fn DeclareFunc) func(
	context.Context, *mcp.CallToolRequest, DeclareInput,
) (*mcp.CallToolResult, any, error) {
	return func(
		ctx context.Context,
		_ *mcp.CallToolRequest,
		input DeclareInput,
	) (*mcp.CallToolResult, any, error) {
		output, err := fn(ctx, input)
		if err != nil {
			return nil, nil, err
		}

		return nil, output, nil
	}
}

// wrapPoll adapts PollFunc to the MCP tool handler shape.
func wrapPoll(fn PollFunc) func(
	context.Context, *mcp.CallToolRequest, DeclareInput,
) (*mcp.CallToolResult, any, error) {
	return func(
		ctx context.Context,
		_ *mcp.CallToolRequest,
		input DeclareInput,
	) (*mcp.CallToolResult, any, error) {
		output, err := fn(ctx, input)
		if err != nil {
			return nil, nil, err
		}

		return nil, output, nil
	}
}

// handleConfigValidate handles the config-validate MCP tool.
func handleConfigValidate(
	_ context.Context,
	_ *mcp.CallToolRequest,
	input mcptypes.ConfigValidateInput,
) (*mcp.CallToolResult, any, error) {
	output := ValidateMap(input.Spec)

	if output.Valid {
		result, artifact := mcputil.SuccessResultWithArtifact("Configuration is valid", output)

		return result, artifact, nil
	}

	result, artifact := mcputil.SuccessResultWithArtifact(
		fmt.Sprintf("Configuration validation failed with %d error(s)", len(output.Errors)),
		output,
	)

	return result, artifact, nil
}
