// Code generated by forge-dev. DO NOT EDIT.
// Source: spec.openapi.yaml
// SourceChecksum: sha256:e7e3c6247342158d2ff56a0a62ea4ca6fc5e04e51e1961c0a3ea832647f6c172

package main

import (
	"fmt"
)

// ForgeArtifact represents the ForgeArtifact configuration.
// One artifact record from forge, carried verbatim. Its schema lives in forge for the same reason ForgeResult's does.
type ForgeArtifact map[string]interface{}

// Spec represents the Spec configuration.
// Engine specific configuration. forge-ci never reads inside it.
type Spec map[string]interface{}

// ArtifactOutput represents the ArtifactOutput configuration.
// What reached the outside world.
type ArtifactOutput struct {
	Published bool   `json:"published"`
	Reason    string `json:"reason,omitempty"`
	// Repos that carry the tag now.
	Tagged []string `json:"tagged,omitempty"`
	Url    string   `json:"url,omitempty"`
}

// ForgeResult represents the ForgeResult configuration.
// forge's own TestReport and Artifact records, carried verbatim. Their schema lives in forge and is not repeated here, because a copy drifts from what forge actually emits.
type ForgeResult map[string]interface{}

// Status represents an enum type.
type Status string

const (
	Statusfailed  Status = "failed"
	Statuspassed  Status = "passed"
	Statuspending Status = "pending"
	Statusrunning Status = "running"
)

// Ownership represents the Ownership configuration.
// Which manager created a resource. A second manager must not touch it.
type Ownership struct {
	// Alias of the manager that created it.
	Manager string `json:"manager"`
	// Resource id, kind slash name.
	Resource string `json:"resource"`
}

// PromotionOutput represents the PromotionOutput configuration.
// The decision, and why.
type PromotionOutput struct {
	Advance bool   `json:"advance"`
	Reason  string `json:"reason"`
}

// RepoCheckout represents the RepoCheckout configuration.
// One repo as the compute engine sees it.
type RepoCheckout struct {
	Name string `json:"name"`
	// Repos that must finish before this one starts, when a target runs in both. A compute engine groups a target's dirs into waves from these edges and runs a wave at once. With none declared every dir is its own wave, in the order given, which is one at a time.
	Needs []string `json:"needs,omitempty"`
	Path  string   `json:"path"`
	Sha   string   `json:"sha"`
}

// Target represents the Target configuration.
// One thing to run. Either a forge target or a forge-ci verb, never both.
type Target struct {
	Alias string `json:"alias"`
	// A forge target, run in each repo named by in.
	Forge string `json:"forge,omitempty"`
	// A forge-ci verb, run at the workspace root.
	ForgeCI string   `json:"forgeCI,omitempty"`
	In      []string `json:"in,omitempty"`
}

// TriggerOutput represents the TriggerOutput configuration.
// Whether the watched repos moved since the last fingerprint.
type TriggerOutput struct {
	Changed bool `json:"changed"`
	// Opaque. Handed back on the next poll as spec.previous.
	Fingerprint string `json:"fingerprint"`
	Reason      string `json:"reason,omitempty"`
}

// ArtifactInput represents the ArtifactInput configuration.
// What a release engine is handed once a stage proved a revision.
type ArtifactInput struct {
	// What forge built.
	Artifacts []ForgeArtifact `json:"artifacts,omitempty"`
	// Repo name to commit SHA.
	Repos map[string]string `json:"repos,omitempty"`
	// The revision being released.
	Revision string `json:"revision"`
	Spec     Spec   `json:"spec,omitempty"`
	// Namespaces the tag when one repo is released by more than one factory. Absent means the tag is the version.
	TagPrefix string `json:"tagPrefix,omitempty"`
	// The semver tag to publish under. Decided by the core and by nothing else. An engine that computes its own is a second authority, and two authorities is how every member of a workspace drifted onto a version line of its own.
	Version string `json:"version"`
}

// DeclareInput represents the DeclareInput configuration.
// What an engine is asked with when it reports what it needs. An engine declares before anything exists to name, so it carries the spec block and nothing else.
type DeclareInput struct {
	Spec Spec `json:"spec,omitempty"`
}

// Resource represents the Resource configuration.
// Something an engine needs to exist. Declared by engines, realized by managers.
type Resource struct {
	// Realized by a bootstrap and never by an apply.
	// For a resource that cannot be converged: a credential is written blind, because nothing can be read back to compare against, so "reconciling" one is just writing it again. Doing that on every run also means every run must hold the rights to rewrite it, which is a far wider blast radius than running a pipeline needs.
	// Credentials are the case this exists for. Only a bootstrap is responsible for them.
	//
	BootstrapOnly bool `json:"bootstrapOnly,omitempty"`
	// Resource kind, for example directory or table.
	Kind string `json:"kind"`
	// Unique name within the kind.
	Name string `json:"name"`
	Spec Spec   `json:"spec,omitempty"`
}

// GateResult represents the GateResult configuration.
// What one gate decided.
type GateResult struct {
	Alias   string `json:"alias"`
	Message string `json:"message,omitempty"`
	Status  Status `json:"status"`
}

// RunOutput represents the RunOutput configuration.
// What a compute engine came back with.
type RunOutput struct {
	Forge   ForgeResult `json:"forge,omitempty"`
	Message string      `json:"message,omitempty"`
	// The tail of what the command printed, kept for a failure.
	Output string `json:"output,omitempty"`
	Status Status `json:"status"`
}

// ReconcileOutput represents the ReconcileOutput configuration.
// What a manager made exist, and what it did.
type ReconcileOutput struct {
	// One line per thing done, for a human reading a report.
	Actions []string `json:"actions"`
	// Whether this manager found a difference between what was declared and what existed, and performed a change to close it.
	// A caller stops the run when this is true. The change is already durable - a manager that needs a separate act to make it so has done that act by the time it answers - so the next run reads the corrected state and this is false.
	// Not required. An older manager that never sets it reports false, which is the behaviour that predates the field.
	//
	Changed bool        `json:"changed,omitempty"`
	Owned   []Ownership `json:"owned"`
}

// RunInput represents the RunInput configuration.
// What a compute engine is asked to run.
type RunInput struct {
	// User defined values, templated into the targets.
	Params   map[string]string `json:"params,omitempty"`
	Repos    []RepoCheckout    `json:"repos,omitempty"`
	Revision string            `json:"revision"`
	Root     string            `json:"root"`
	Spec     Spec              `json:"spec,omitempty"`
	Stage    string            `json:"stage"`
	Substage string            `json:"substage"`
	Targets  []Target          `json:"targets"`
	// The number this apply would release under, derived before the first stage. A compute target stamps it into what it builds, so a binary reports the release it shipped in rather than the nearest tag its own repo happens to carry. Absent when the pipeline releases nothing.
	Version string `json:"version,omitempty"`
}

// DeclareOutput represents the DeclareOutput configuration.
// What an engine needs to exist. An engine with no infrastructure returns an empty list.
type DeclareOutput struct {
	Resources []Resource `json:"resources"`
}

// ReconcileInput represents the ReconcileInput configuration.
// What a manager is asked to make exist.
type ReconcileInput struct {
	// Whether this is the provisioning ceremony.
	// A resource marked bootstrapOnly is still handed over when this is false - the manager keeps owning it, which is what stops another manager claiming it - but the manager must not realize it.
	// Credentials are the case. Only a bootstrap writes one.
	//
	Bootstrap bool `json:"bootstrap,omitempty"`
	// Alias of the manager being asked.
	Manager string `json:"manager"`
	// What is already owned, so a manager refuses another's resource.
	Owned     []Ownership `json:"owned,omitempty"`
	Resources []Resource  `json:"resources"`
	Spec      Spec        `json:"spec,omitempty"`
}

// Run represents the Run configuration.
// One substage that ran, and what came of it.
type Run struct {
	// Seconds.
	Duration  float64      `json:"duration"`
	Engine    string       `json:"engine"`
	Forge     ForgeResult  `json:"forge,omitempty"`
	Gates     []GateResult `json:"gates,omitempty"`
	Message   string       `json:"message,omitempty"`
	Output    string       `json:"output,omitempty"`
	Revision  string       `json:"revision"`
	Stage     string       `json:"stage"`
	StartedAt string       `json:"startedAt"`
	Status    Status       `json:"status"`
	Substage  string       `json:"substage"`
}

// GateInput represents the GateInput configuration.
// A gate judges a run after it finished. A gate never runs before.
type GateInput struct {
	Run  Run  `json:"run"`
	Spec Spec `json:"spec,omitempty"`
}

// PromotionInput represents the PromotionInput configuration.
// Whether a stage advances, decided once over every substage outcome.
type PromotionInput struct {
	Runs  []Run  `json:"runs"`
	Spec  Spec   `json:"spec,omitempty"`
	Stage string `json:"stage"`
}

// ForgeArtifactFromMap creates a ForgeArtifact from a map[string]interface{}.
func ForgeArtifactFromMap(m map[string]interface{}) (*ForgeArtifact, error) {
	if m == nil {
		return &ForgeArtifact{}, nil
	}

	s := &ForgeArtifact{}
	return s, nil
}

// SpecFromMap creates a Spec from a map[string]interface{}.
func SpecFromMap(m map[string]interface{}) (*Spec, error) {
	if m == nil {
		return &Spec{}, nil
	}

	s := &Spec{}
	return s, nil
}

// ArtifactOutputFromMap creates a ArtifactOutput from a map[string]interface{}.
func ArtifactOutputFromMap(m map[string]interface{}) (*ArtifactOutput, error) {
	if m == nil {
		return &ArtifactOutput{}, nil
	}

	s := &ArtifactOutput{}
	// Parse published
	if v, ok := m["published"]; ok && v != nil {
		if val, ok := v.(bool); ok {
			s.Published = val
		} else {
			return nil, fmt.Errorf("field published: expected bool, got %T", v)
		}
	}
	// Parse reason
	if v, ok := m["reason"]; ok && v != nil {
		if val, ok := v.(string); ok {
			s.Reason = val
		} else {
			return nil, fmt.Errorf("field reason: expected string, got %T", v)
		}
	}
	// Parse tagged
	if v, ok := m["tagged"]; ok && v != nil {
		if arr, ok := v.([]interface{}); ok {
			s.Tagged = make([]string, 0, len(arr))
			for i, item := range arr {
				if str, ok := item.(string); ok {
					s.Tagged = append(s.Tagged, str)
				} else {
					return nil, fmt.Errorf("field tagged[%d]: expected string, got %T", i, item)
				}
			}
		} else if arr, ok := v.([]string); ok {
			s.Tagged = arr
		} else {
			return nil, fmt.Errorf("field tagged: expected []string, got %T", v)
		}
	}
	// Parse url
	if v, ok := m["url"]; ok && v != nil {
		if val, ok := v.(string); ok {
			s.Url = val
		} else {
			return nil, fmt.Errorf("field url: expected string, got %T", v)
		}
	}
	return s, nil
}

// ForgeResultFromMap creates a ForgeResult from a map[string]interface{}.
func ForgeResultFromMap(m map[string]interface{}) (*ForgeResult, error) {
	if m == nil {
		return &ForgeResult{}, nil
	}

	s := &ForgeResult{}
	return s, nil
}

// OwnershipFromMap creates a Ownership from a map[string]interface{}.
func OwnershipFromMap(m map[string]interface{}) (*Ownership, error) {
	if m == nil {
		return &Ownership{}, nil
	}

	s := &Ownership{}
	// Parse manager
	if v, ok := m["manager"]; ok && v != nil {
		if val, ok := v.(string); ok {
			s.Manager = val
		} else {
			return nil, fmt.Errorf("field manager: expected string, got %T", v)
		}
	}
	// Parse resource
	if v, ok := m["resource"]; ok && v != nil {
		if val, ok := v.(string); ok {
			s.Resource = val
		} else {
			return nil, fmt.Errorf("field resource: expected string, got %T", v)
		}
	}
	return s, nil
}

// PromotionOutputFromMap creates a PromotionOutput from a map[string]interface{}.
func PromotionOutputFromMap(m map[string]interface{}) (*PromotionOutput, error) {
	if m == nil {
		return &PromotionOutput{}, nil
	}

	s := &PromotionOutput{}
	// Parse advance
	if v, ok := m["advance"]; ok && v != nil {
		if val, ok := v.(bool); ok {
			s.Advance = val
		} else {
			return nil, fmt.Errorf("field advance: expected bool, got %T", v)
		}
	}
	// Parse reason
	if v, ok := m["reason"]; ok && v != nil {
		if val, ok := v.(string); ok {
			s.Reason = val
		} else {
			return nil, fmt.Errorf("field reason: expected string, got %T", v)
		}
	}
	return s, nil
}

// RepoCheckoutFromMap creates a RepoCheckout from a map[string]interface{}.
func RepoCheckoutFromMap(m map[string]interface{}) (*RepoCheckout, error) {
	if m == nil {
		return &RepoCheckout{}, nil
	}

	s := &RepoCheckout{}
	// Parse name
	if v, ok := m["name"]; ok && v != nil {
		if val, ok := v.(string); ok {
			s.Name = val
		} else {
			return nil, fmt.Errorf("field name: expected string, got %T", v)
		}
	}
	// Parse needs
	if v, ok := m["needs"]; ok && v != nil {
		if arr, ok := v.([]interface{}); ok {
			s.Needs = make([]string, 0, len(arr))
			for i, item := range arr {
				if str, ok := item.(string); ok {
					s.Needs = append(s.Needs, str)
				} else {
					return nil, fmt.Errorf("field needs[%d]: expected string, got %T", i, item)
				}
			}
		} else if arr, ok := v.([]string); ok {
			s.Needs = arr
		} else {
			return nil, fmt.Errorf("field needs: expected []string, got %T", v)
		}
	}
	// Parse path
	if v, ok := m["path"]; ok && v != nil {
		if val, ok := v.(string); ok {
			s.Path = val
		} else {
			return nil, fmt.Errorf("field path: expected string, got %T", v)
		}
	}
	// Parse sha
	if v, ok := m["sha"]; ok && v != nil {
		if val, ok := v.(string); ok {
			s.Sha = val
		} else {
			return nil, fmt.Errorf("field sha: expected string, got %T", v)
		}
	}
	return s, nil
}

// TargetFromMap creates a Target from a map[string]interface{}.
func TargetFromMap(m map[string]interface{}) (*Target, error) {
	if m == nil {
		return &Target{}, nil
	}

	s := &Target{}
	// Parse alias
	if v, ok := m["alias"]; ok && v != nil {
		if val, ok := v.(string); ok {
			s.Alias = val
		} else {
			return nil, fmt.Errorf("field alias: expected string, got %T", v)
		}
	}
	// Parse forge
	if v, ok := m["forge"]; ok && v != nil {
		if val, ok := v.(string); ok {
			s.Forge = val
		} else {
			return nil, fmt.Errorf("field forge: expected string, got %T", v)
		}
	}
	// Parse forgeCI
	if v, ok := m["forgeCI"]; ok && v != nil {
		if val, ok := v.(string); ok {
			s.ForgeCI = val
		} else {
			return nil, fmt.Errorf("field forgeCI: expected string, got %T", v)
		}
	}
	// Parse in
	if v, ok := m["in"]; ok && v != nil {
		if arr, ok := v.([]interface{}); ok {
			s.In = make([]string, 0, len(arr))
			for i, item := range arr {
				if str, ok := item.(string); ok {
					s.In = append(s.In, str)
				} else {
					return nil, fmt.Errorf("field in[%d]: expected string, got %T", i, item)
				}
			}
		} else if arr, ok := v.([]string); ok {
			s.In = arr
		} else {
			return nil, fmt.Errorf("field in: expected []string, got %T", v)
		}
	}
	return s, nil
}

// TriggerOutputFromMap creates a TriggerOutput from a map[string]interface{}.
func TriggerOutputFromMap(m map[string]interface{}) (*TriggerOutput, error) {
	if m == nil {
		return &TriggerOutput{}, nil
	}

	s := &TriggerOutput{}
	// Parse changed
	if v, ok := m["changed"]; ok && v != nil {
		if val, ok := v.(bool); ok {
			s.Changed = val
		} else {
			return nil, fmt.Errorf("field changed: expected bool, got %T", v)
		}
	}
	// Parse fingerprint
	if v, ok := m["fingerprint"]; ok && v != nil {
		if val, ok := v.(string); ok {
			s.Fingerprint = val
		} else {
			return nil, fmt.Errorf("field fingerprint: expected string, got %T", v)
		}
	}
	// Parse reason
	if v, ok := m["reason"]; ok && v != nil {
		if val, ok := v.(string); ok {
			s.Reason = val
		} else {
			return nil, fmt.Errorf("field reason: expected string, got %T", v)
		}
	}
	return s, nil
}

// ArtifactInputFromMap creates a ArtifactInput from a map[string]interface{}.
func ArtifactInputFromMap(m map[string]interface{}) (*ArtifactInput, error) {
	if m == nil {
		return &ArtifactInput{}, nil
	}

	s := &ArtifactInput{}
	// Parse artifacts
	if v, ok := m["artifacts"]; ok && v != nil {
		if arr, ok := v.([]interface{}); ok {
			s.Artifacts = make([]ForgeArtifact, 0, len(arr))
			for i, item := range arr {
				if obj, ok := item.(map[string]interface{}); ok {
					ref, err := ForgeArtifactFromMap(obj)
					if err != nil {
						return nil, fmt.Errorf("field artifacts[%d]: %w", i, err)
					}
					if ref != nil {
						s.Artifacts = append(s.Artifacts, *ref)
					}
				} else {
					return nil, fmt.Errorf("field artifacts[%d]: expected object, got %T", i, item)
				}
			}
		} else {
			return nil, fmt.Errorf("field artifacts: expected []object, got %T", v)
		}
	}
	// Parse repos
	if v, ok := m["repos"]; ok && v != nil {
		if mapVal, ok := v.(map[string]interface{}); ok {
			s.Repos = make(map[string]string, len(mapVal))
			for key, val := range mapVal {
				if str, ok := val.(string); ok {
					s.Repos[key] = str
				} else {
					return nil, fmt.Errorf("field repos[%s]: expected string, got %T", key, val)
				}
			}
		} else if mapVal, ok := v.(map[string]string); ok {
			s.Repos = mapVal
		} else {
			return nil, fmt.Errorf("field repos: expected map[string]string, got %T", v)
		}
	}
	// Parse revision
	if v, ok := m["revision"]; ok && v != nil {
		if val, ok := v.(string); ok {
			s.Revision = val
		} else {
			return nil, fmt.Errorf("field revision: expected string, got %T", v)
		}
	}
	// Parse spec
	if v, ok := m["spec"]; ok && v != nil {
		if obj, ok := v.(map[string]interface{}); ok {
			ref, err := SpecFromMap(obj)
			if err != nil {
				return nil, fmt.Errorf("field spec: %w", err)
			}
			if ref != nil {
				s.Spec = *ref
			}
		} else {
			return nil, fmt.Errorf("field spec: expected object, got %T", v)
		}
	}
	// Parse tagPrefix
	if v, ok := m["tagPrefix"]; ok && v != nil {
		if val, ok := v.(string); ok {
			s.TagPrefix = val
		} else {
			return nil, fmt.Errorf("field tagPrefix: expected string, got %T", v)
		}
	}
	// Parse version
	if v, ok := m["version"]; ok && v != nil {
		if val, ok := v.(string); ok {
			s.Version = val
		} else {
			return nil, fmt.Errorf("field version: expected string, got %T", v)
		}
	}
	return s, nil
}

// DeclareInputFromMap creates a DeclareInput from a map[string]interface{}.
func DeclareInputFromMap(m map[string]interface{}) (*DeclareInput, error) {
	if m == nil {
		return &DeclareInput{}, nil
	}

	s := &DeclareInput{}
	// Parse spec
	if v, ok := m["spec"]; ok && v != nil {
		if obj, ok := v.(map[string]interface{}); ok {
			ref, err := SpecFromMap(obj)
			if err != nil {
				return nil, fmt.Errorf("field spec: %w", err)
			}
			if ref != nil {
				s.Spec = *ref
			}
		} else {
			return nil, fmt.Errorf("field spec: expected object, got %T", v)
		}
	}
	return s, nil
}

// ResourceFromMap creates a Resource from a map[string]interface{}.
func ResourceFromMap(m map[string]interface{}) (*Resource, error) {
	if m == nil {
		return &Resource{}, nil
	}

	s := &Resource{}
	// Parse bootstrapOnly
	if v, ok := m["bootstrapOnly"]; ok && v != nil {
		if val, ok := v.(bool); ok {
			s.BootstrapOnly = val
		} else {
			return nil, fmt.Errorf("field bootstrapOnly: expected bool, got %T", v)
		}
	}
	// Parse kind
	if v, ok := m["kind"]; ok && v != nil {
		if val, ok := v.(string); ok {
			s.Kind = val
		} else {
			return nil, fmt.Errorf("field kind: expected string, got %T", v)
		}
	}
	// Parse name
	if v, ok := m["name"]; ok && v != nil {
		if val, ok := v.(string); ok {
			s.Name = val
		} else {
			return nil, fmt.Errorf("field name: expected string, got %T", v)
		}
	}
	// Parse spec
	if v, ok := m["spec"]; ok && v != nil {
		if obj, ok := v.(map[string]interface{}); ok {
			ref, err := SpecFromMap(obj)
			if err != nil {
				return nil, fmt.Errorf("field spec: %w", err)
			}
			if ref != nil {
				s.Spec = *ref
			}
		} else {
			return nil, fmt.Errorf("field spec: expected object, got %T", v)
		}
	}
	return s, nil
}

// GateResultFromMap creates a GateResult from a map[string]interface{}.
func GateResultFromMap(m map[string]interface{}) (*GateResult, error) {
	if m == nil {
		return &GateResult{}, nil
	}

	s := &GateResult{}
	// Parse alias
	if v, ok := m["alias"]; ok && v != nil {
		if val, ok := v.(string); ok {
			s.Alias = val
		} else {
			return nil, fmt.Errorf("field alias: expected string, got %T", v)
		}
	}
	// Parse message
	if v, ok := m["message"]; ok && v != nil {
		if val, ok := v.(string); ok {
			s.Message = val
		} else {
			return nil, fmt.Errorf("field message: expected string, got %T", v)
		}
	}
	// Parse status
	if v, ok := m["status"]; ok && v != nil {
		if str, ok := v.(string); ok {
			s.Status = Status(str)
		} else {
			return nil, fmt.Errorf("field status: expected string, got %T", v)
		}
	}
	return s, nil
}

// RunOutputFromMap creates a RunOutput from a map[string]interface{}.
func RunOutputFromMap(m map[string]interface{}) (*RunOutput, error) {
	if m == nil {
		return &RunOutput{}, nil
	}

	s := &RunOutput{}
	// Parse forge
	if v, ok := m["forge"]; ok && v != nil {
		if obj, ok := v.(map[string]interface{}); ok {
			ref, err := ForgeResultFromMap(obj)
			if err != nil {
				return nil, fmt.Errorf("field forge: %w", err)
			}
			if ref != nil {
				s.Forge = *ref
			}
		} else {
			return nil, fmt.Errorf("field forge: expected object, got %T", v)
		}
	}
	// Parse message
	if v, ok := m["message"]; ok && v != nil {
		if val, ok := v.(string); ok {
			s.Message = val
		} else {
			return nil, fmt.Errorf("field message: expected string, got %T", v)
		}
	}
	// Parse output
	if v, ok := m["output"]; ok && v != nil {
		if val, ok := v.(string); ok {
			s.Output = val
		} else {
			return nil, fmt.Errorf("field output: expected string, got %T", v)
		}
	}
	// Parse status
	if v, ok := m["status"]; ok && v != nil {
		if str, ok := v.(string); ok {
			s.Status = Status(str)
		} else {
			return nil, fmt.Errorf("field status: expected string, got %T", v)
		}
	}
	return s, nil
}

// ReconcileOutputFromMap creates a ReconcileOutput from a map[string]interface{}.
func ReconcileOutputFromMap(m map[string]interface{}) (*ReconcileOutput, error) {
	if m == nil {
		return &ReconcileOutput{}, nil
	}

	s := &ReconcileOutput{}
	// Parse actions
	if v, ok := m["actions"]; ok && v != nil {
		if arr, ok := v.([]interface{}); ok {
			s.Actions = make([]string, 0, len(arr))
			for i, item := range arr {
				if str, ok := item.(string); ok {
					s.Actions = append(s.Actions, str)
				} else {
					return nil, fmt.Errorf("field actions[%d]: expected string, got %T", i, item)
				}
			}
		} else if arr, ok := v.([]string); ok {
			s.Actions = arr
		} else {
			return nil, fmt.Errorf("field actions: expected []string, got %T", v)
		}
	}
	// Parse changed
	if v, ok := m["changed"]; ok && v != nil {
		if val, ok := v.(bool); ok {
			s.Changed = val
		} else {
			return nil, fmt.Errorf("field changed: expected bool, got %T", v)
		}
	}
	// Parse owned
	if v, ok := m["owned"]; ok && v != nil {
		if arr, ok := v.([]interface{}); ok {
			s.Owned = make([]Ownership, 0, len(arr))
			for i, item := range arr {
				if obj, ok := item.(map[string]interface{}); ok {
					ref, err := OwnershipFromMap(obj)
					if err != nil {
						return nil, fmt.Errorf("field owned[%d]: %w", i, err)
					}
					if ref != nil {
						s.Owned = append(s.Owned, *ref)
					}
				} else {
					return nil, fmt.Errorf("field owned[%d]: expected object, got %T", i, item)
				}
			}
		} else {
			return nil, fmt.Errorf("field owned: expected []object, got %T", v)
		}
	}
	return s, nil
}

// RunInputFromMap creates a RunInput from a map[string]interface{}.
func RunInputFromMap(m map[string]interface{}) (*RunInput, error) {
	if m == nil {
		return &RunInput{}, nil
	}

	s := &RunInput{}
	// Parse params
	if v, ok := m["params"]; ok && v != nil {
		if mapVal, ok := v.(map[string]interface{}); ok {
			s.Params = make(map[string]string, len(mapVal))
			for key, val := range mapVal {
				if str, ok := val.(string); ok {
					s.Params[key] = str
				} else {
					return nil, fmt.Errorf("field params[%s]: expected string, got %T", key, val)
				}
			}
		} else if mapVal, ok := v.(map[string]string); ok {
			s.Params = mapVal
		} else {
			return nil, fmt.Errorf("field params: expected map[string]string, got %T", v)
		}
	}
	// Parse repos
	if v, ok := m["repos"]; ok && v != nil {
		if arr, ok := v.([]interface{}); ok {
			s.Repos = make([]RepoCheckout, 0, len(arr))
			for i, item := range arr {
				if obj, ok := item.(map[string]interface{}); ok {
					ref, err := RepoCheckoutFromMap(obj)
					if err != nil {
						return nil, fmt.Errorf("field repos[%d]: %w", i, err)
					}
					if ref != nil {
						s.Repos = append(s.Repos, *ref)
					}
				} else {
					return nil, fmt.Errorf("field repos[%d]: expected object, got %T", i, item)
				}
			}
		} else {
			return nil, fmt.Errorf("field repos: expected []object, got %T", v)
		}
	}
	// Parse revision
	if v, ok := m["revision"]; ok && v != nil {
		if val, ok := v.(string); ok {
			s.Revision = val
		} else {
			return nil, fmt.Errorf("field revision: expected string, got %T", v)
		}
	}
	// Parse root
	if v, ok := m["root"]; ok && v != nil {
		if val, ok := v.(string); ok {
			s.Root = val
		} else {
			return nil, fmt.Errorf("field root: expected string, got %T", v)
		}
	}
	// Parse spec
	if v, ok := m["spec"]; ok && v != nil {
		if obj, ok := v.(map[string]interface{}); ok {
			ref, err := SpecFromMap(obj)
			if err != nil {
				return nil, fmt.Errorf("field spec: %w", err)
			}
			if ref != nil {
				s.Spec = *ref
			}
		} else {
			return nil, fmt.Errorf("field spec: expected object, got %T", v)
		}
	}
	// Parse stage
	if v, ok := m["stage"]; ok && v != nil {
		if val, ok := v.(string); ok {
			s.Stage = val
		} else {
			return nil, fmt.Errorf("field stage: expected string, got %T", v)
		}
	}
	// Parse substage
	if v, ok := m["substage"]; ok && v != nil {
		if val, ok := v.(string); ok {
			s.Substage = val
		} else {
			return nil, fmt.Errorf("field substage: expected string, got %T", v)
		}
	}
	// Parse targets
	if v, ok := m["targets"]; ok && v != nil {
		if arr, ok := v.([]interface{}); ok {
			s.Targets = make([]Target, 0, len(arr))
			for i, item := range arr {
				if obj, ok := item.(map[string]interface{}); ok {
					ref, err := TargetFromMap(obj)
					if err != nil {
						return nil, fmt.Errorf("field targets[%d]: %w", i, err)
					}
					if ref != nil {
						s.Targets = append(s.Targets, *ref)
					}
				} else {
					return nil, fmt.Errorf("field targets[%d]: expected object, got %T", i, item)
				}
			}
		} else {
			return nil, fmt.Errorf("field targets: expected []object, got %T", v)
		}
	}
	// Parse version
	if v, ok := m["version"]; ok && v != nil {
		if val, ok := v.(string); ok {
			s.Version = val
		} else {
			return nil, fmt.Errorf("field version: expected string, got %T", v)
		}
	}
	return s, nil
}

// DeclareOutputFromMap creates a DeclareOutput from a map[string]interface{}.
func DeclareOutputFromMap(m map[string]interface{}) (*DeclareOutput, error) {
	if m == nil {
		return &DeclareOutput{}, nil
	}

	s := &DeclareOutput{}
	// Parse resources
	if v, ok := m["resources"]; ok && v != nil {
		if arr, ok := v.([]interface{}); ok {
			s.Resources = make([]Resource, 0, len(arr))
			for i, item := range arr {
				if obj, ok := item.(map[string]interface{}); ok {
					ref, err := ResourceFromMap(obj)
					if err != nil {
						return nil, fmt.Errorf("field resources[%d]: %w", i, err)
					}
					if ref != nil {
						s.Resources = append(s.Resources, *ref)
					}
				} else {
					return nil, fmt.Errorf("field resources[%d]: expected object, got %T", i, item)
				}
			}
		} else {
			return nil, fmt.Errorf("field resources: expected []object, got %T", v)
		}
	}
	return s, nil
}

// ReconcileInputFromMap creates a ReconcileInput from a map[string]interface{}.
func ReconcileInputFromMap(m map[string]interface{}) (*ReconcileInput, error) {
	if m == nil {
		return &ReconcileInput{}, nil
	}

	s := &ReconcileInput{}
	// Parse bootstrap
	if v, ok := m["bootstrap"]; ok && v != nil {
		if val, ok := v.(bool); ok {
			s.Bootstrap = val
		} else {
			return nil, fmt.Errorf("field bootstrap: expected bool, got %T", v)
		}
	}
	// Parse manager
	if v, ok := m["manager"]; ok && v != nil {
		if val, ok := v.(string); ok {
			s.Manager = val
		} else {
			return nil, fmt.Errorf("field manager: expected string, got %T", v)
		}
	}
	// Parse owned
	if v, ok := m["owned"]; ok && v != nil {
		if arr, ok := v.([]interface{}); ok {
			s.Owned = make([]Ownership, 0, len(arr))
			for i, item := range arr {
				if obj, ok := item.(map[string]interface{}); ok {
					ref, err := OwnershipFromMap(obj)
					if err != nil {
						return nil, fmt.Errorf("field owned[%d]: %w", i, err)
					}
					if ref != nil {
						s.Owned = append(s.Owned, *ref)
					}
				} else {
					return nil, fmt.Errorf("field owned[%d]: expected object, got %T", i, item)
				}
			}
		} else {
			return nil, fmt.Errorf("field owned: expected []object, got %T", v)
		}
	}
	// Parse resources
	if v, ok := m["resources"]; ok && v != nil {
		if arr, ok := v.([]interface{}); ok {
			s.Resources = make([]Resource, 0, len(arr))
			for i, item := range arr {
				if obj, ok := item.(map[string]interface{}); ok {
					ref, err := ResourceFromMap(obj)
					if err != nil {
						return nil, fmt.Errorf("field resources[%d]: %w", i, err)
					}
					if ref != nil {
						s.Resources = append(s.Resources, *ref)
					}
				} else {
					return nil, fmt.Errorf("field resources[%d]: expected object, got %T", i, item)
				}
			}
		} else {
			return nil, fmt.Errorf("field resources: expected []object, got %T", v)
		}
	}
	// Parse spec
	if v, ok := m["spec"]; ok && v != nil {
		if obj, ok := v.(map[string]interface{}); ok {
			ref, err := SpecFromMap(obj)
			if err != nil {
				return nil, fmt.Errorf("field spec: %w", err)
			}
			if ref != nil {
				s.Spec = *ref
			}
		} else {
			return nil, fmt.Errorf("field spec: expected object, got %T", v)
		}
	}
	return s, nil
}

// RunFromMap creates a Run from a map[string]interface{}.
func RunFromMap(m map[string]interface{}) (*Run, error) {
	if m == nil {
		return &Run{}, nil
	}

	s := &Run{}
	// Parse duration
	if v, ok := m["duration"]; ok && v != nil {
		switch val := v.(type) {
		case float64:
			s.Duration = val
		case int:
			s.Duration = float64(val)
		case int64:
			s.Duration = float64(val)
		default:
			return nil, fmt.Errorf("field duration: expected float64, got %T", v)
		}
	}
	// Parse engine
	if v, ok := m["engine"]; ok && v != nil {
		if val, ok := v.(string); ok {
			s.Engine = val
		} else {
			return nil, fmt.Errorf("field engine: expected string, got %T", v)
		}
	}
	// Parse forge
	if v, ok := m["forge"]; ok && v != nil {
		if obj, ok := v.(map[string]interface{}); ok {
			ref, err := ForgeResultFromMap(obj)
			if err != nil {
				return nil, fmt.Errorf("field forge: %w", err)
			}
			if ref != nil {
				s.Forge = *ref
			}
		} else {
			return nil, fmt.Errorf("field forge: expected object, got %T", v)
		}
	}
	// Parse gates
	if v, ok := m["gates"]; ok && v != nil {
		if arr, ok := v.([]interface{}); ok {
			s.Gates = make([]GateResult, 0, len(arr))
			for i, item := range arr {
				if obj, ok := item.(map[string]interface{}); ok {
					ref, err := GateResultFromMap(obj)
					if err != nil {
						return nil, fmt.Errorf("field gates[%d]: %w", i, err)
					}
					if ref != nil {
						s.Gates = append(s.Gates, *ref)
					}
				} else {
					return nil, fmt.Errorf("field gates[%d]: expected object, got %T", i, item)
				}
			}
		} else {
			return nil, fmt.Errorf("field gates: expected []object, got %T", v)
		}
	}
	// Parse message
	if v, ok := m["message"]; ok && v != nil {
		if val, ok := v.(string); ok {
			s.Message = val
		} else {
			return nil, fmt.Errorf("field message: expected string, got %T", v)
		}
	}
	// Parse output
	if v, ok := m["output"]; ok && v != nil {
		if val, ok := v.(string); ok {
			s.Output = val
		} else {
			return nil, fmt.Errorf("field output: expected string, got %T", v)
		}
	}
	// Parse revision
	if v, ok := m["revision"]; ok && v != nil {
		if val, ok := v.(string); ok {
			s.Revision = val
		} else {
			return nil, fmt.Errorf("field revision: expected string, got %T", v)
		}
	}
	// Parse stage
	if v, ok := m["stage"]; ok && v != nil {
		if val, ok := v.(string); ok {
			s.Stage = val
		} else {
			return nil, fmt.Errorf("field stage: expected string, got %T", v)
		}
	}
	// Parse startedAt
	if v, ok := m["startedAt"]; ok && v != nil {
		if val, ok := v.(string); ok {
			s.StartedAt = val
		} else {
			return nil, fmt.Errorf("field startedAt: expected string, got %T", v)
		}
	}
	// Parse status
	if v, ok := m["status"]; ok && v != nil {
		if str, ok := v.(string); ok {
			s.Status = Status(str)
		} else {
			return nil, fmt.Errorf("field status: expected string, got %T", v)
		}
	}
	// Parse substage
	if v, ok := m["substage"]; ok && v != nil {
		if val, ok := v.(string); ok {
			s.Substage = val
		} else {
			return nil, fmt.Errorf("field substage: expected string, got %T", v)
		}
	}
	return s, nil
}

// GateInputFromMap creates a GateInput from a map[string]interface{}.
func GateInputFromMap(m map[string]interface{}) (*GateInput, error) {
	if m == nil {
		return &GateInput{}, nil
	}

	s := &GateInput{}
	// Parse run
	if v, ok := m["run"]; ok && v != nil {
		if obj, ok := v.(map[string]interface{}); ok {
			ref, err := RunFromMap(obj)
			if err != nil {
				return nil, fmt.Errorf("field run: %w", err)
			}
			if ref != nil {
				s.Run = *ref
			}
		} else {
			return nil, fmt.Errorf("field run: expected object, got %T", v)
		}
	}
	// Parse spec
	if v, ok := m["spec"]; ok && v != nil {
		if obj, ok := v.(map[string]interface{}); ok {
			ref, err := SpecFromMap(obj)
			if err != nil {
				return nil, fmt.Errorf("field spec: %w", err)
			}
			if ref != nil {
				s.Spec = *ref
			}
		} else {
			return nil, fmt.Errorf("field spec: expected object, got %T", v)
		}
	}
	return s, nil
}

// PromotionInputFromMap creates a PromotionInput from a map[string]interface{}.
func PromotionInputFromMap(m map[string]interface{}) (*PromotionInput, error) {
	if m == nil {
		return &PromotionInput{}, nil
	}

	s := &PromotionInput{}
	// Parse runs
	if v, ok := m["runs"]; ok && v != nil {
		if arr, ok := v.([]interface{}); ok {
			s.Runs = make([]Run, 0, len(arr))
			for i, item := range arr {
				if obj, ok := item.(map[string]interface{}); ok {
					ref, err := RunFromMap(obj)
					if err != nil {
						return nil, fmt.Errorf("field runs[%d]: %w", i, err)
					}
					if ref != nil {
						s.Runs = append(s.Runs, *ref)
					}
				} else {
					return nil, fmt.Errorf("field runs[%d]: expected object, got %T", i, item)
				}
			}
		} else {
			return nil, fmt.Errorf("field runs: expected []object, got %T", v)
		}
	}
	// Parse spec
	if v, ok := m["spec"]; ok && v != nil {
		if obj, ok := v.(map[string]interface{}); ok {
			ref, err := SpecFromMap(obj)
			if err != nil {
				return nil, fmt.Errorf("field spec: %w", err)
			}
			if ref != nil {
				s.Spec = *ref
			}
		} else {
			return nil, fmt.Errorf("field spec: expected object, got %T", v)
		}
	}
	// Parse stage
	if v, ok := m["stage"]; ok && v != nil {
		if val, ok := v.(string); ok {
			s.Stage = val
		} else {
			return nil, fmt.Errorf("field stage: expected string, got %T", v)
		}
	}
	return s, nil
}

// ToMap converts a ForgeArtifact to a map[string]interface{}.
func (s *ForgeArtifact) ToMap() map[string]interface{} {
	if s == nil {
		return nil
	}

	m := make(map[string]interface{})
	return m
}

// ToMap converts a Spec to a map[string]interface{}.
func (s *Spec) ToMap() map[string]interface{} {
	if s == nil {
		return nil
	}

	m := make(map[string]interface{})
	return m
}

// ToMap converts a ArtifactOutput to a map[string]interface{}.
func (s *ArtifactOutput) ToMap() map[string]interface{} {
	if s == nil {
		return nil
	}

	m := make(map[string]interface{})
	if s.Published {
		m["published"] = s.Published
	}
	if s.Reason != "" {
		m["reason"] = s.Reason
	}
	if len(s.Tagged) > 0 {
		m["tagged"] = s.Tagged
	}
	if s.Url != "" {
		m["url"] = s.Url
	}
	return m
}

// ToMap converts a ForgeResult to a map[string]interface{}.
func (s *ForgeResult) ToMap() map[string]interface{} {
	if s == nil {
		return nil
	}

	m := make(map[string]interface{})
	return m
}

// ToMap converts a Ownership to a map[string]interface{}.
func (s *Ownership) ToMap() map[string]interface{} {
	if s == nil {
		return nil
	}

	m := make(map[string]interface{})
	if s.Manager != "" {
		m["manager"] = s.Manager
	}
	if s.Resource != "" {
		m["resource"] = s.Resource
	}
	return m
}

// ToMap converts a PromotionOutput to a map[string]interface{}.
func (s *PromotionOutput) ToMap() map[string]interface{} {
	if s == nil {
		return nil
	}

	m := make(map[string]interface{})
	if s.Advance {
		m["advance"] = s.Advance
	}
	if s.Reason != "" {
		m["reason"] = s.Reason
	}
	return m
}

// ToMap converts a RepoCheckout to a map[string]interface{}.
func (s *RepoCheckout) ToMap() map[string]interface{} {
	if s == nil {
		return nil
	}

	m := make(map[string]interface{})
	if s.Name != "" {
		m["name"] = s.Name
	}
	if len(s.Needs) > 0 {
		m["needs"] = s.Needs
	}
	if s.Path != "" {
		m["path"] = s.Path
	}
	if s.Sha != "" {
		m["sha"] = s.Sha
	}
	return m
}

// ToMap converts a Target to a map[string]interface{}.
func (s *Target) ToMap() map[string]interface{} {
	if s == nil {
		return nil
	}

	m := make(map[string]interface{})
	if s.Alias != "" {
		m["alias"] = s.Alias
	}
	if s.Forge != "" {
		m["forge"] = s.Forge
	}
	if s.ForgeCI != "" {
		m["forgeCI"] = s.ForgeCI
	}
	if len(s.In) > 0 {
		m["in"] = s.In
	}
	return m
}

// ToMap converts a TriggerOutput to a map[string]interface{}.
func (s *TriggerOutput) ToMap() map[string]interface{} {
	if s == nil {
		return nil
	}

	m := make(map[string]interface{})
	if s.Changed {
		m["changed"] = s.Changed
	}
	if s.Fingerprint != "" {
		m["fingerprint"] = s.Fingerprint
	}
	if s.Reason != "" {
		m["reason"] = s.Reason
	}
	return m
}

// ToMap converts a ArtifactInput to a map[string]interface{}.
func (s *ArtifactInput) ToMap() map[string]interface{} {
	if s == nil {
		return nil
	}

	m := make(map[string]interface{})
	if len(s.Artifacts) > 0 {
		arr := make([]interface{}, 0, len(s.Artifacts))
		for _, item := range s.Artifacts {
			arr = append(arr, item.ToMap())
		}
		m["artifacts"] = arr
	}
	if len(s.Repos) > 0 {
		m["repos"] = s.Repos
	}
	if s.Revision != "" {
		m["revision"] = s.Revision
	}
	// Reference type Spec
	if refMap := s.Spec.ToMap(); len(refMap) > 0 {
		m["spec"] = refMap
	}
	if s.TagPrefix != "" {
		m["tagPrefix"] = s.TagPrefix
	}
	if s.Version != "" {
		m["version"] = s.Version
	}
	return m
}

// ToMap converts a DeclareInput to a map[string]interface{}.
func (s *DeclareInput) ToMap() map[string]interface{} {
	if s == nil {
		return nil
	}

	m := make(map[string]interface{})
	// Reference type Spec
	if refMap := s.Spec.ToMap(); len(refMap) > 0 {
		m["spec"] = refMap
	}
	return m
}

// ToMap converts a Resource to a map[string]interface{}.
func (s *Resource) ToMap() map[string]interface{} {
	if s == nil {
		return nil
	}

	m := make(map[string]interface{})
	if s.BootstrapOnly {
		m["bootstrapOnly"] = s.BootstrapOnly
	}
	if s.Kind != "" {
		m["kind"] = s.Kind
	}
	if s.Name != "" {
		m["name"] = s.Name
	}
	// Reference type Spec
	if refMap := s.Spec.ToMap(); len(refMap) > 0 {
		m["spec"] = refMap
	}
	return m
}

// ToMap converts a GateResult to a map[string]interface{}.
func (s *GateResult) ToMap() map[string]interface{} {
	if s == nil {
		return nil
	}

	m := make(map[string]interface{})
	if s.Alias != "" {
		m["alias"] = s.Alias
	}
	if s.Message != "" {
		m["message"] = s.Message
	}
	// Status is an enum, which is a string and has no ToMap.
	if s.Status != "" {
		m["status"] = string(s.Status)
	}
	return m
}

// ToMap converts a RunOutput to a map[string]interface{}.
func (s *RunOutput) ToMap() map[string]interface{} {
	if s == nil {
		return nil
	}

	m := make(map[string]interface{})
	// Reference type ForgeResult
	if refMap := s.Forge.ToMap(); len(refMap) > 0 {
		m["forge"] = refMap
	}
	if s.Message != "" {
		m["message"] = s.Message
	}
	if s.Output != "" {
		m["output"] = s.Output
	}
	// Status is an enum, which is a string and has no ToMap.
	if s.Status != "" {
		m["status"] = string(s.Status)
	}
	return m
}

// ToMap converts a ReconcileOutput to a map[string]interface{}.
func (s *ReconcileOutput) ToMap() map[string]interface{} {
	if s == nil {
		return nil
	}

	m := make(map[string]interface{})
	if len(s.Actions) > 0 {
		m["actions"] = s.Actions
	}
	if s.Changed {
		m["changed"] = s.Changed
	}
	if len(s.Owned) > 0 {
		arr := make([]interface{}, 0, len(s.Owned))
		for _, item := range s.Owned {
			arr = append(arr, item.ToMap())
		}
		m["owned"] = arr
	}
	return m
}

// ToMap converts a RunInput to a map[string]interface{}.
func (s *RunInput) ToMap() map[string]interface{} {
	if s == nil {
		return nil
	}

	m := make(map[string]interface{})
	if len(s.Params) > 0 {
		m["params"] = s.Params
	}
	if len(s.Repos) > 0 {
		arr := make([]interface{}, 0, len(s.Repos))
		for _, item := range s.Repos {
			arr = append(arr, item.ToMap())
		}
		m["repos"] = arr
	}
	if s.Revision != "" {
		m["revision"] = s.Revision
	}
	if s.Root != "" {
		m["root"] = s.Root
	}
	// Reference type Spec
	if refMap := s.Spec.ToMap(); len(refMap) > 0 {
		m["spec"] = refMap
	}
	if s.Stage != "" {
		m["stage"] = s.Stage
	}
	if s.Substage != "" {
		m["substage"] = s.Substage
	}
	if len(s.Targets) > 0 {
		arr := make([]interface{}, 0, len(s.Targets))
		for _, item := range s.Targets {
			arr = append(arr, item.ToMap())
		}
		m["targets"] = arr
	}
	if s.Version != "" {
		m["version"] = s.Version
	}
	return m
}

// ToMap converts a DeclareOutput to a map[string]interface{}.
func (s *DeclareOutput) ToMap() map[string]interface{} {
	if s == nil {
		return nil
	}

	m := make(map[string]interface{})
	if len(s.Resources) > 0 {
		arr := make([]interface{}, 0, len(s.Resources))
		for _, item := range s.Resources {
			arr = append(arr, item.ToMap())
		}
		m["resources"] = arr
	}
	return m
}

// ToMap converts a ReconcileInput to a map[string]interface{}.
func (s *ReconcileInput) ToMap() map[string]interface{} {
	if s == nil {
		return nil
	}

	m := make(map[string]interface{})
	if s.Bootstrap {
		m["bootstrap"] = s.Bootstrap
	}
	if s.Manager != "" {
		m["manager"] = s.Manager
	}
	if len(s.Owned) > 0 {
		arr := make([]interface{}, 0, len(s.Owned))
		for _, item := range s.Owned {
			arr = append(arr, item.ToMap())
		}
		m["owned"] = arr
	}
	if len(s.Resources) > 0 {
		arr := make([]interface{}, 0, len(s.Resources))
		for _, item := range s.Resources {
			arr = append(arr, item.ToMap())
		}
		m["resources"] = arr
	}
	// Reference type Spec
	if refMap := s.Spec.ToMap(); len(refMap) > 0 {
		m["spec"] = refMap
	}
	return m
}

// ToMap converts a Run to a map[string]interface{}.
func (s *Run) ToMap() map[string]interface{} {
	if s == nil {
		return nil
	}

	m := make(map[string]interface{})
	if s.Duration != 0 {
		m["duration"] = s.Duration
	}
	if s.Engine != "" {
		m["engine"] = s.Engine
	}
	// Reference type ForgeResult
	if refMap := s.Forge.ToMap(); len(refMap) > 0 {
		m["forge"] = refMap
	}
	if len(s.Gates) > 0 {
		arr := make([]interface{}, 0, len(s.Gates))
		for _, item := range s.Gates {
			arr = append(arr, item.ToMap())
		}
		m["gates"] = arr
	}
	if s.Message != "" {
		m["message"] = s.Message
	}
	if s.Output != "" {
		m["output"] = s.Output
	}
	if s.Revision != "" {
		m["revision"] = s.Revision
	}
	if s.Stage != "" {
		m["stage"] = s.Stage
	}
	if s.StartedAt != "" {
		m["startedAt"] = s.StartedAt
	}
	// Status is an enum, which is a string and has no ToMap.
	if s.Status != "" {
		m["status"] = string(s.Status)
	}
	if s.Substage != "" {
		m["substage"] = s.Substage
	}
	return m
}

// ToMap converts a GateInput to a map[string]interface{}.
func (s *GateInput) ToMap() map[string]interface{} {
	if s == nil {
		return nil
	}

	m := make(map[string]interface{})
	// Reference type Run
	if refMap := s.Run.ToMap(); len(refMap) > 0 {
		m["run"] = refMap
	}
	// Reference type Spec
	if refMap := s.Spec.ToMap(); len(refMap) > 0 {
		m["spec"] = refMap
	}
	return m
}

// ToMap converts a PromotionInput to a map[string]interface{}.
func (s *PromotionInput) ToMap() map[string]interface{} {
	if s == nil {
		return nil
	}

	m := make(map[string]interface{})
	if len(s.Runs) > 0 {
		arr := make([]interface{}, 0, len(s.Runs))
		for _, item := range s.Runs {
			arr = append(arr, item.ToMap())
		}
		m["runs"] = arr
	}
	// Reference type Spec
	if refMap := s.Spec.ToMap(); len(refMap) > 0 {
		m["spec"] = refMap
	}
	if s.Stage != "" {
		m["stage"] = s.Stage
	}
	return m
}

// FromMap creates a Spec from a map[string]interface{}.
// This is the main entry point for parsing the spec field from forge.yaml.
func FromMap(m map[string]interface{}) (*Spec, error) {
	return SpecFromMap(m)
}
