// Code generated by forge-dev. DO NOT EDIT.
// Source: spec.openapi.yaml
// SourceChecksum: sha256:e4ad4a58702e212a330a24aa76deda43bc7c865630acc8cf380ce6d86004cb67

package main

import (
	"context"
	"fmt"

	"github.com/alexandremahdhaoui/forge/pkg/mcpserver"
	"github.com/alexandremahdhaoui/forge/pkg/mcptypes"
	"github.com/alexandremahdhaoui/forge/pkg/mcputil"
	"github.com/modelcontextprotocol/go-sdk/mcp"
)

// DeclareFunc is the handler signature for the declare tool.
// Report the resources this release needs. It needs none.
type DeclareFunc func(
	ctx context.Context,
	input DeclareInput,
) (*DeclareOutput, error)

// PublishFunc is the handler signature for the publish tool.
// Tag every repo of the revision and create the release.
type PublishFunc func(
	ctx context.Context,
	input ArtifactInput,
) (*ArtifactOutput, error)

// Handlers holds one implementation per tool declared in forge-dev.yaml.
// Every field is required. A nil field makes SetupMCPServer return an error
// rather than registering a tool that panics when called.
type Handlers struct {
	// Declare implements the declare tool.
	Declare DeclareFunc
	// Publish implements the publish tool.
	Publish PublishFunc
}

// SetupMCPServer creates the MCP server and registers every declared tool plus
// config-validate.
func SetupMCPServer(name string, version string, handlers Handlers) (*mcpserver.Server, error) {
	server := mcpserver.New(name, version)

	if handlers.Declare == nil {
		return nil, fmt.Errorf("Handlers.Declare is required for the %q tool", "declare")
	}

	mcpserver.RegisterTool(server, &mcp.Tool{
		Name:        "declare",
		Description: "Report the resources this release needs. It needs none.",
	}, wrapDeclare(handlers.Declare))

	if handlers.Publish == nil {
		return nil, fmt.Errorf("Handlers.Publish is required for the %q tool", "publish")
	}

	mcpserver.RegisterTool(server, &mcp.Tool{
		Name:        "publish",
		Description: "Tag every repo of the revision and create the release.",
	}, wrapPublish(handlers.Publish))

	mcpserver.RegisterTool(server, &mcp.Tool{
		Name:        "config-validate",
		Description: fmt.Sprintf("Validate %s engine-specific spec configuration.", name),
	}, handleConfigValidate)

	return server, nil
}

// wrapDeclare adapts DeclareFunc to the MCP tool handler shape.
func wrapDeclare(fn DeclareFunc) func(
	context.Context, *mcp.CallToolRequest, DeclareInput,
) (*mcp.CallToolResult, any, error) {
	return func(
		ctx context.Context,
		_ *mcp.CallToolRequest,
		input DeclareInput,
	) (*mcp.CallToolResult, any, error) {
		output, err := fn(ctx, input)
		if err != nil {
			return nil, nil, err
		}

		return nil, output, nil
	}
}

// wrapPublish adapts PublishFunc to the MCP tool handler shape.
func wrapPublish(fn PublishFunc) func(
	context.Context, *mcp.CallToolRequest, ArtifactInput,
) (*mcp.CallToolResult, any, error) {
	return func(
		ctx context.Context,
		_ *mcp.CallToolRequest,
		input ArtifactInput,
	) (*mcp.CallToolResult, any, error) {
		output, err := fn(ctx, input)
		if err != nil {
			return nil, nil, err
		}

		return nil, output, nil
	}
}

// handleConfigValidate handles the config-validate MCP tool.
func handleConfigValidate(
	_ context.Context,
	_ *mcp.CallToolRequest,
	input mcptypes.ConfigValidateInput,
) (*mcp.CallToolResult, any, error) {
	output := ValidateMap(input.Spec)

	if output.Valid {
		result, artifact := mcputil.SuccessResultWithArtifact("Configuration is valid", output)

		return result, artifact, nil
	}

	result, artifact := mcputil.SuccessResultWithArtifact(
		fmt.Sprintf("Configuration validation failed with %d error(s)", len(output.Errors)),
		output,
	)

	return result, artifact, nil
}
