// Code generated by forge-dev. DO NOT EDIT.
// Source: forge-dev.yaml + spec.openapi.yaml
// SourceChecksum: sha256:2afc53026a249d57ebdc9e390d9bea59bfb00d9b8ced33288a7dd437d5ffff3b

package main

import (
	"context"
	"fmt"

	"github.com/alexandremahdhaoui/forge/pkg/enginecli"
)

// Name is the engine name.
const Name = "ci-compute-local"

// Version information (set via ldflags during build).
// Default is "dev" so GetEffectiveVersion() reads actual version from Go's debug.ReadBuildInfo()
// when running via "go run module@version".
var (
	Version        = "dev"
	CommitSHA      = "unknown"
	BuildTimestamp = "unknown"
)

// main is the entry point for the ci-compute-local engine.
func main() {
	enginecli.Bootstrap(enginecli.Config{
		Name:           Name,
		Version:        Version,
		CommitSHA:      CommitSHA,
		BuildTimestamp: BuildTimestamp,
		RunCLI:         nil, // Generated engines are MCP-only
		RunMCP:         runMCPServer,
		DocsConfig:     docsConfig,
	})
}

// runMCPServer creates and runs the MCP server.
func runMCPServer() error {
	server, err := SetupMCPServer(Name, Version, NewHandlers())
	if err != nil {
		return fmt.Errorf("setting up MCP server: %w", err)
	}

	// Register docs MCP tools (docs-list, docs-get)
	if err := RegisterDocsMCPTools(server); err != nil {
		return fmt.Errorf("registering docs MCP tools: %w", err)
	}

	if err := server.Run(context.Background()); err != nil {
		return fmt.Errorf("running MCP server: %w", err)
	}

	return nil
}

// NewHandlers must be implemented by the engine author in a separate file.
// It returns one implementation per tool declared in forge-dev.yaml:
//
//	func NewHandlers() Handlers {
//		return Handlers{
//			Declare: func(ctx context.Context, input DeclareInput) (*DeclareOutput, error) {
//				panic("declare is not implemented")
//			},
//			Run: func(ctx context.Context, input RunInput) (*RunOutput, error) {
//				panic("run is not implemented")
//			},
//		}
//	}
