// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package machineconfigcontrollermock

import (
	"github.com/alexandremahdhaoui/forge-ci/internal/adapter/talossecretsadapter"
	"github.com/alexandremahdhaoui/forge-ci/pkg/citypes"
	mock "github.com/stretchr/testify/mock"
)

// NewMockRenderer creates a new instance of MockRenderer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRenderer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRenderer {
	mock := &MockRenderer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRenderer is an autogenerated mock type for the Renderer type
type MockRenderer struct {
	mock.Mock
}

type MockRenderer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRenderer) EXPECT() *MockRenderer_Expecter {
	return &MockRenderer_Expecter{mock: &_m.Mock}
}

// Load provides a mock function for the type MockRenderer
func (_mock *MockRenderer) Load(bundle citypes.Secret) (citypes.Secret, error) {
	ret := _mock.Called(bundle)

	if len(ret) == 0 {
		panic("no return value specified for Load")
	}

	var r0 citypes.Secret
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(citypes.Secret) (citypes.Secret, error)); ok {
		return returnFunc(bundle)
	}
	if returnFunc, ok := ret.Get(0).(func(citypes.Secret) citypes.Secret); ok {
		r0 = returnFunc(bundle)
	} else {
		r0 = ret.Get(0).(citypes.Secret)
	}
	if returnFunc, ok := ret.Get(1).(func(citypes.Secret) error); ok {
		r1 = returnFunc(bundle)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRenderer_Load_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Load'
type MockRenderer_Load_Call struct {
	*mock.Call
}

// Load is a helper method to define mock.On call
//   - bundle citypes.Secret
func (_e *MockRenderer_Expecter) Load(bundle any) *MockRenderer_Load_Call {
	return &MockRenderer_Load_Call{Call: _e.mock.On("Load", bundle)}
}

func (_c *MockRenderer_Load_Call) Run(run func(bundle citypes.Secret)) *MockRenderer_Load_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 citypes.Secret
		if args[0] != nil {
			arg0 = args[0].(citypes.Secret)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRenderer_Load_Call) Return(secret citypes.Secret, err error) *MockRenderer_Load_Call {
	_c.Call.Return(secret, err)
	return _c
}

func (_c *MockRenderer_Load_Call) RunAndReturn(run func(bundle citypes.Secret) (citypes.Secret, error)) *MockRenderer_Load_Call {
	_c.Call.Return(run)
	return _c
}

// MachineConfig provides a mock function for the type MockRenderer
func (_mock *MockRenderer) MachineConfig(bundle citypes.Secret, cluster talossecretsadapter.Cluster, patch string) (citypes.Secret, error) {
	ret := _mock.Called(bundle, cluster, patch)

	if len(ret) == 0 {
		panic("no return value specified for MachineConfig")
	}

	var r0 citypes.Secret
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(citypes.Secret, talossecretsadapter.Cluster, string) (citypes.Secret, error)); ok {
		return returnFunc(bundle, cluster, patch)
	}
	if returnFunc, ok := ret.Get(0).(func(citypes.Secret, talossecretsadapter.Cluster, string) citypes.Secret); ok {
		r0 = returnFunc(bundle, cluster, patch)
	} else {
		r0 = ret.Get(0).(citypes.Secret)
	}
	if returnFunc, ok := ret.Get(1).(func(citypes.Secret, talossecretsadapter.Cluster, string) error); ok {
		r1 = returnFunc(bundle, cluster, patch)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRenderer_MachineConfig_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MachineConfig'
type MockRenderer_MachineConfig_Call struct {
	*mock.Call
}

// MachineConfig is a helper method to define mock.On call
//   - bundle citypes.Secret
//   - cluster talossecretsadapter.Cluster
//   - patch string
func (_e *MockRenderer_Expecter) MachineConfig(bundle any, cluster any, patch any) *MockRenderer_MachineConfig_Call {
	return &MockRenderer_MachineConfig_Call{Call: _e.mock.On("MachineConfig", bundle, cluster, patch)}
}

func (_c *MockRenderer_MachineConfig_Call) Run(run func(bundle citypes.Secret, cluster talossecretsadapter.Cluster, patch string)) *MockRenderer_MachineConfig_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 citypes.Secret
		if args[0] != nil {
			arg0 = args[0].(citypes.Secret)
		}
		var arg1 talossecretsadapter.Cluster
		if args[1] != nil {
			arg1 = args[1].(talossecretsadapter.Cluster)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRenderer_MachineConfig_Call) Return(secret citypes.Secret, err error) *MockRenderer_MachineConfig_Call {
	_c.Call.Return(secret, err)
	return _c
}

func (_c *MockRenderer_MachineConfig_Call) RunAndReturn(run func(bundle citypes.Secret, cluster talossecretsadapter.Cluster, patch string) (citypes.Secret, error)) *MockRenderer_MachineConfig_Call {
	_c.Call.Return(run)
	return _c
}
