// Code generated by forge-dev. DO NOT EDIT.
// Source: spec.openapi.yaml
// SourceChecksum: sha256:286bca41a3aa29fb02119020667575b867f105d9992c648f46ef8b3a0867d3db

package main

import (
	"context"
	"fmt"

	"github.com/alexandremahdhaoui/forge/pkg/mcpserver"
	"github.com/alexandremahdhaoui/forge/pkg/mcptypes"
	"github.com/alexandremahdhaoui/forge/pkg/mcputil"
	"github.com/modelcontextprotocol/go-sdk/mcp"
)

// DeclareFunc is the handler signature for the declare tool.
// Report every GitHub resource the spec implies.
type DeclareFunc func(
	ctx context.Context,
	input DeclareInput,
) (*DeclareOutput, error)

// RunFunc is the handler signature for the run tool.
// Dispatch the runner workflow, correlate the run by marker, and poll it to conclusion.
type RunFunc func(
	ctx context.Context,
	input RunInput,
) (*RunOutput, error)

// Handlers holds one implementation per tool declared in forge-dev.yaml.
// Every field is required. A nil field makes SetupMCPServer return an error
// rather than registering a tool that panics when called.
type Handlers struct {
	// Declare implements the declare tool.
	Declare DeclareFunc
	// Run implements the run tool.
	Run RunFunc
}

// SetupMCPServer creates the MCP server and registers every declared tool plus
// config-validate.
func SetupMCPServer(name string, version string, handlers Handlers) (*mcpserver.Server, error) {
	server := mcpserver.New(name, version)

	if handlers.Declare == nil {
		return nil, fmt.Errorf("Handlers.Declare is required for the %q tool", "declare")
	}

	mcpserver.RegisterTool(server, &mcp.Tool{
		Name:        "declare",
		Description: "Report every GitHub resource the spec implies.",
	}, wrapDeclare(handlers.Declare))

	if handlers.Run == nil {
		return nil, fmt.Errorf("Handlers.Run is required for the %q tool", "run")
	}

	mcpserver.RegisterTool(server, &mcp.Tool{
		Name:        "run",
		Description: "Dispatch the runner workflow, correlate the run by marker, and poll it to conclusion.",
	}, wrapRun(handlers.Run))

	mcpserver.RegisterTool(server, &mcp.Tool{
		Name:        "config-validate",
		Description: fmt.Sprintf("Validate %s engine-specific spec configuration.", name),
	}, handleConfigValidate)

	return server, nil
}

// wrapDeclare adapts DeclareFunc to the MCP tool handler shape.
func wrapDeclare(fn DeclareFunc) func(
	context.Context, *mcp.CallToolRequest, DeclareInput,
) (*mcp.CallToolResult, any, error) {
	return func(
		ctx context.Context,
		_ *mcp.CallToolRequest,
		input DeclareInput,
	) (*mcp.CallToolResult, any, error) {
		output, err := fn(ctx, input)
		if err != nil {
			return nil, nil, err
		}

		return nil, output, nil
	}
}

// wrapRun adapts RunFunc to the MCP tool handler shape.
func wrapRun(fn RunFunc) func(
	context.Context, *mcp.CallToolRequest, RunInput,
) (*mcp.CallToolResult, any, error) {
	return func(
		ctx context.Context,
		_ *mcp.CallToolRequest,
		input RunInput,
	) (*mcp.CallToolResult, any, error) {
		output, err := fn(ctx, input)
		if err != nil {
			return nil, nil, err
		}

		return nil, output, nil
	}
}

// handleConfigValidate handles the config-validate MCP tool.
func handleConfigValidate(
	_ context.Context,
	_ *mcp.CallToolRequest,
	input mcptypes.ConfigValidateInput,
) (*mcp.CallToolResult, any, error) {
	output := ValidateMap(input.Spec)

	if output.Valid {
		result, artifact := mcputil.SuccessResultWithArtifact("Configuration is valid", output)

		return result, artifact, nil
	}

	result, artifact := mcputil.SuccessResultWithArtifact(
		fmt.Sprintf("Configuration validation failed with %d error(s)", len(output.Errors)),
		output,
	)

	return result, artifact, nil
}
