// Code generated by forge-dev. DO NOT EDIT.
// Source: forge-dev.yaml
// SourceChecksum: sha256:33a5b38b4da061cf072f2371956d61b82b512012cb2a054c082da0b808d6781a

package main

import (
	"github.com/alexandremahdhaoui/forge/pkg/enginedocs"
	"github.com/alexandremahdhaoui/forge/pkg/mcpserver"
)

// docsConfig is the configuration for documentation tools.
var docsConfig = &enginedocs.Config{
	EngineName:   "ci-manager-github",
	LocalDir:     "cmd/ci-manager-github/docs",
	BaseURL:      "https://raw.githubusercontent.com/alexandremahdhaoui/forge-ci/refs/heads/main",
	RequiredDocs: []string{"usage", "schema"},
}

// RegisterDocsMCPTools registers the docs-list and docs-get MCP tools.
func RegisterDocsMCPTools(server *mcpserver.Server) error {
	return enginedocs.RegisterDocsTools(server, *docsConfig)
}
